### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#1]
![fisherman-logo-gray](https://cloud.githubusercontent.com/assets/8317250/10864865/87b79ed6-803e-11e5-8e7d-5aeb760d5e44.png)
> https://cloud.githubusercontent.com/assets/8317250/10864865/87b79ed6-803e-11e5-8e7d-5aeb760d5e44.png

**Comment by lordlycastle** [comment]
My vote: Second one!

**Comment by bucaran** [comment]
@lordlycastle I think the last one may look better against a white background, but maybe the second one is best in smaller sizes. We need to experiment a bit.

**Comment by bucaran** [comment]
![fisherman-logo org-white-bg](https://cloud.githubusercontent.com/assets/8317250/11473523/45214736-97b6-11e5-9f85-a0810e22d1fc.png)

![fisherman-logo org](https://cloud.githubusercontent.com/assets/8317250/11473522/451ec4c0-97b6-11e5-9cd3-fc41ef49391e.png)

**Comment by bucaran** [comment]
![fisherman-logo org-bg](https://cloud.githubusercontent.com/assets/8317250/11590183/cdf00db8-9ad1-11e5-8132-b8392e910384.png)

**Comment by bucaran** [comment]
![fisherman-logo org](https://cloud.githubusercontent.com/assets/8317250/11600567/dc59ca9e-9b10-11e5-927f-05e4ed70cb9c.png)

**Comment by martoranod** [comment]
:+1:
