### ISSUE TITLE
Extract spin (formerly known as `wait`) into its own plugin

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#100]
Move `wait` (will be renamed to `spin` from now on) into a plugin that users can install if they want. By default, Fisherman will use `__fisher_spin` which will in turn use `spin` if available, otherwise it will use a minimal `spin` implementation that always shows the same spinner and is simpler to maintain.

**Comment by pickfire** [comment]
Weird, when I had reinstall fisherman by deleting it's folder and clearing it from config.fish and run the `curl` command.

I didn't get that fancy output (spin), what I get is:
```
fish_indent: src/proc.cpp:129: int get_is_interactive(): Assertion `is_interactive >= 0' failed.
 ✓ Downloading Fisherman to XDG_DATA/fisherman
fish_indent: src/proc.cpp:129: int get_is_interactive(): Assertion `is_interactive >= 0' failed.
 ✓ Creating the configuration in XDG_CONFIG/fisherman
fish_indent: src/proc.cpp:129: int get_is_interactive(): Assertion `is_interactive >= 0' failed.
 ✓ Updating the registry index
fish_indent: src/proc.cpp:129: int get_is_interactive(): Assertion `is_interactive >= 0' failed.
 ✓ Installing CLI dependencies
 ✓ Done!

Enter fisher to begin or visit one of the links below:

 → Quickstart Guide http://start.fisherman.sh
 → Slack Community  http://slack.fisherman.sh
 → Plugins Market   http://plugins.fisherman.sh
```

**Comment by bucaran** [comment]
Thanks for reporting this.

Do you have any trouble displaying colors?

This is the output you should get.

![](https://cloud.githubusercontent.com/assets/8317250/13040276/5f0e5350-d3ed-11e5-8994-3488f80c6494.gif)

> fish_indent: src/proc.cpp:129: int get_is_interactive(): Assertion `is_interactive >= 0' failed.

What's this? and also what is your operating system and fish version?

**Comment by pickfire** [comment]
The colors are displayed. It seems like fisher isn't installed after I got those message (Done!), but actually nothing is added to the ~/.config/, no git clone, nothing is added to config.fish.

`uname -a`:
```
Linux alarmpi 4.1.17-3-ARCH #1 SMP Sat Feb 13 17:57:30 MST 2016 armv7l GNU/Linux
```
`fish -v`:
```
fish, version df8c4ce
```

**Comment by bucaran** [comment]
Try running the installer `try me` mode and see what you get `curl -sL get.fisherman.sh | env TRY_ME=true fish`.

Also, here is the code: https://github.com/fisherman/install/blob/master/install.fish

The installer has tests that pass in Linux and OS X.

**Comment by bucaran** [comment]
Note: I see you are running a fairly recent fish build `df8c4ce`, I am running 2.2.0, maybe the problem is there?

**Comment by bucaran** [comment]
@pickfire Please open a new issue to track your issue with the strange error message. #100 is official implemented so we should close here.

**Comment by laughedelic** [comment]
Hi, I'm not opening a new issue, because I just have a question about spin. What happened in the end with this? Is it a plugin or a builtin command? 
I see the https://github.com/fisherman/spin repo, but I cannot install spin with `fisher install spin`, also `fisher search spin` doesn't yield anything. It's not in the list of installed plugins, but there is a command `spin`. The `--style` option doesn't work as described in the help, and as I see from the code, there is only one default style.

**Comment by bucaran** [comment]
@laughedelic It's a plugin, that's the correct URL too. 

If we provide spin as a separate plugin, we need to provide a `spin` function stub with the same signature as the spin plugin because what if the user uninstalls it?

We have changed how fisherman is installed a few times over the course of the history of the project, so it was not always clear whether we should provide it out of the box, or not. I think the simplest thing to do is bundle spin with fisherman.

> fisher search spin doesn't yield anything.

That's because spin is not in the index. I have updated spin's README to show the correct install instructions now.

**Comment by laughedelic** [comment]
@bucaran thanks for clarifying 👍 
I completely understand the point of having it as a separate plugin, but bundled with fisherman. 

Sorry for annoyance, but I have a couple more questions about spin:
- Is there a reason, why the issues are closed in the spin repo? Are you gathering all issues here? Or no complaints are allowed, only solutions (pull-requests)?  😅 
- Still, the example in the spin readme shows `--style=pipe` and the man page: `--style=mix|arc|star|pipe|flip|bounce|bar1~3`. Could you remove that to avoid confusion?

**Comment by bucaran** [comment]
No reason, I must have disabled issues by mistake.

I'll fix the other things right away.
