### ISSUE TITLE
The fish_promt is having unrendered chars (question mask)

### ISSUE THREAD

**Issue by chengguangnan** [fisherman/fisherman#102]
![screen shot 2016-02-17 at 10 16 21 am](https://cloud.githubusercontent.com/assets/861069/13097817/8279205e-d55f-11e5-996c-4085d6ebc892.png)

On a local git repo, the fish prompt is like this, I'm on os x el captain, latest iterm 2, also tried the system terminal, tried different font, encoding is utf-8. 

Some other emnoji chars did show up correctly. Is this a known issue?

**Comment by bucaran** [comment]
@chengguangnan It looks like you are missing the Powerline fonts: https://github.com/powerline/fonts

What prompt/theme are you using?

**Comment by chengguangnan** [comment]
Oh I see. Thanks. I'm a first time shellder user. shellder is the prompt. 

Also, now I noticed that, remember to change to Non-ASCII font to a powerline patched font, not the Regular Font.

**Comment by bucaran** [comment]
@chengguangnan So, are things working well now? :smile:

**Comment by chengguangnan** [comment]
Yeah, turns out that I don't like shellder, so I switched back to my own theme.

**Comment by bucaran** [comment]
I mean, the font issue, is it fixed?

>  I switched back to my own theme

Cool. Can you share it? :smile:

**Comment by chengguangnan** [comment]
Yeah, the font issues is fixed. My theme is just some simple text. 

![screen shot 2016-02-17 at 11 34 17 am](https://cloud.githubusercontent.com/assets/861069/13099145/684af274-d56a-11e5-81da-0097ea6395fc.png)

**Comment by bucaran** [comment]
>  My theme is just some simple text.

Sometimes that's all you need.

> Yeah, the font issues is fixed

Great.
