### ISSUE TITLE
missing /wiki/About-the-Logo page

### ISSUE THREAD

**Issue by edouard-lopez** [fisherman/fisherman#106]
### Description

At the bottom of fisherman/fisherman#69 you got a broken link:

> We have a cool home page and a solid **brand**.

The link target [/wiki/About-the-Logo](https://github.com/fisherman/fisherman/wiki/About-the-Logo]) while it should link to the [fisherman/logo repo](https://github.com/fisherman/logo).

### Solution

Either:

1. Fix the link in fisherman/fisherman#69 ;
1. Add a redirect in [/wiki/About-the-Logo](https://github.com/fisherman/fisherman/wiki/About-the-Logo]).

**Comment by bucaran** [comment]
Thanks @edouard-lopez, I went ahead and fixed the dead link and fixed other bits here are there! :+1:
