### ISSUE TITLE
Improve installer and support for  2.1.2 — (Original: Dry run install errors on fish 2.1.2)

### ISSUE THREAD

**Issue by jonscottclark** [fisherman/fisherman#108]
I had an old version of fish (2.1.2) and tried this: `curl -sL get.fisherman.sh | env TRY_ME=true fish`

Received 5 lines of this: `fish_indent: unrecognized option '--ansi'`

Updated to 2.2.0 to make it work properly. Appears in the 2.2.0 changelog here: https://fishshell.com/release_notes.html

**Comment by bucaran** [comment]
@jonscottclark Thanks!

I have updated the installer to include the following new features:

* `fisher_indent --ansi` does not fail anymore if you `fish` build that does not support the `--ansi` flag.

* Warn you about an "out of date" fish (`< 2.2.0`), but _still_ let you install Fisherman.

![outdate](https://cloud.githubusercontent.com/assets/8317250/13163066/1c308de8-d6ed-11e5-88ad-42ee2845a6f3.gif)

* Revamp reinstalling instructions.

![already-installed](https://cloud.githubusercontent.com/assets/8317250/13163068/23c560e2-d6ed-11e5-879e-b47cd4cac410.gif)


* Improve color output.

![untitled](https://cloud.githubusercontent.com/assets/8317250/13163132/d44e0cfc-d6ed-11e5-9df8-644daaa56eff.png)

**Comment by jonscottclark** [comment]
Perfect :) But in the "revamp reinstallation instructions", I'd change to "Remove **the following** configuration..."

The 3 lines underneath didn't immediately make sense, they seemed to be separate from the two lines above.

**Comment by bucaran** [comment]
Fair suggestion. I

See https://github.com/fisherman/install/commit/eb07f09e8b5ffd8eaa52015d45dc55cfbc06e1ed

Two small changes:

* Add your suggestion, now it reads "Remove the **following** configuration..."
* Only show that message if `config.fish` _actually_ has the Fisherman configuration in it.

**Comment by jonscottclark** [comment]
Nice! :shipit:

**Comment by pickfire** [comment]
@bucaran The 3d image looks nice, how do you do it?

Ah, fisherman support for older version of fish, looks nice.
