### ISSUE TITLE
Installing non-existent Oh My Fish plugin yields errors

### ISSUE THREAD

**Issue by jonscottclark** [fisherman/fisherman#109]
I tried to install an Oh My Fish plugin, and got some errors, thought it might have to do with the omf plugin itself, but it was actually due to the fact that I got the name wrong... Here's an example:

`fisher install omf/sijfojafsfjsakf`

Yields:

```bash
Installing >> sijfojafsfjsakf
cd: The directory '/Users/jonclark/.config/fisherman/cache/sijfojafsfjsakf' does not exist
/usr/local/Cellar/fish/2.2.0/share/fish/functions/cd.fish (line 9): 		builtin cd $argv
                                                                    		^
in function 'cd'
	called on line 14 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/pushd.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sijfojafsfjsakf'

in function 'pushd'
	called on line 9 of file ~/.local/share/fisherman/functions/__fisher_url_from_path.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sijfojafsfjsakf'

in function '__fisher_url_from_path'
	called on line 4 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sijfojafsfjsakf'

in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish

in function '__fisher_plugin_enable'
	called on line 120 of file ~/.local/share/fisherman/functions/fisher_install.fish
	with parameter list 'sijfojafsfjsakf /Users/jonclark/.config/fisherman/cache/sijfojafsfjsakf'

in function 'fisher_install'
	called on line 1 of file -
	with parameter list 'omf/sijfojafsfjsakf'

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 59 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'install omf/sijfojafsfjsakf'

Aye! 1 plugin/s installed in 1s
```

**Comment by bucaran** [comment]
I can't reproduce, what was the fish version you were using when you received this error.



<img width="1085" alt="screen shot 2016-02-19 at 10 17 30 am" src="https://cloud.githubusercontent.com/assets/8317250/13163633/022e6384-d6f2-11e5-99cd-435c31e874de.png">

**Comment by jonscottclark** [comment]
Ok.. I think I figured it out.

I followed the backtrace and found this: https://github.com/fisherman/fisherman/blob/master/functions/fisher_install.fish#L120-L122

That triggered a `git clone`: https://github.com/fisherman/fisherman/blob/master/functions/__fisher_url_clone.fish#L2

I tried to manually run this command, in this case `git clone -q --depth=1 https://github.com/oh-my-fish/sijfojafsfjsakf`, and it prompted me for my Github credentials. So I typed in my username/password and then it gave me the errors that you produced above, "Repository not found".

I then tried cloning other repos that I knew existed, and it didn't prompt me for my password. Then I tried another repository that I knew didn't exist, and it prompted me again. It seems as if Git does some kind of check that the repo is public, and if it is found it will just clone it if the user is authenticated. But if it's not public, it might be a private repo so it then prompts the user for their password.

I assume it may be working for you because you store your Github credentials (https://help.github.com/articles/caching-your-github-password-in-git/) — but for users who don't, they will never get the STDERR that comes with a repo not being found.

**Comment by bucaran** [comment]
I am trying to test this on a different machine in which I am not authenticated, but I am not getting the desired results, meaning I still can't reproduce this.

For the record, what is the version of Git you are using?

One more thing, none of the repositories listed above are private, does Git treat unexisting repos as private kinda?

**Comment by jonscottclark** [comment]
> One more thing, none of the repositories listed above are private, does Git treat unexisting repos as private kinda?

Right, but this is just a guess on my part. I just know that even _after_ I authenticated, it prompted me for authentication again when I tried cloning non-existent repos.

**Comment by jonscottclark** [comment]
git version 2.4.5

**Comment by jonscottclark** [comment]
This is after upgrading to git 2.7.1:

```bash
fisher_install Validate 'omf/sdijfiojfizoe' 0ms
fisher_install Install from a URL or path 'https://github.com/oh-my-fish/sdijfiojfizoe' 36ms
Installing >> sdijfiojfizoe
fisher_install Download 'https://github.com/oh-my-fish/sdijfiojfizoe' 40ms
__fisher_deps_install Install dependencies in '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe' 450ms
__fisher_plugin_walk Walk tree in '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe' 36ms
cd: The directory '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe' does not exist
/usr/local/Cellar/fish/2.2.0/share/fish/functions/cd.fish (line 9): 		builtin cd $argv
                                                                    		^
in function 'cd'
	called on line 14 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/pushd.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe'

in function 'pushd'
	called on line 9 of file ~/.local/share/fisherman/functions/__fisher_url_from_path.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe'

in function '__fisher_url_from_path'
	called on line 4 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish
	with parameter list '/Users/jonclark/.config/fisherman/cache/sdijfiojfizoe'

in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish

in function '__fisher_plugin_enable'
	called on line 133 of file ~/.local/share/fisherman/functions/fisher_install.fish
	with parameter list 'sdijfiojfizoe /Users/jonclark/.config/fisherman/cache/sdijfiojfizoe'

in function 'fisher_install'
	called on line 1 of file -
	with parameter list 'omf/sdijfiojfizoe'

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 59 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'install omf/sdijfiojfizoe'

__fisher_plugin_enable Skip '' already in fishfile 53ms
fisher_install Pre-reset completions and key bindings 42ms
fisher_install Post-reset completions and key bindings 156ms
Aye! 1 plugin/s installed in 0s
```

**Comment by jonscottclark** [comment]
p.s., Ran into this error when making sure I was all up to date: https://github.com/fisherman/fisherman/issues/118

**Comment by bucaran** [comment]
@jonscottclark Thanks! Thank you for enabling debug mode, that was helpful. This definitely seems like a bug in Fisherman, and a very exciting one! :smile:

**Comment by bucaran** [comment]
> I assume it may be working for you because you store your Github credentials (https://help.github.com/articles/caching-your-github-password-in-git/) — but for users who don't, they will never get the STDERR that comes with a repo not being found.

This. Where do you store your Git credentials?

I think this can be solved easily by writing an error message inside `__fisher_url_clone` if Git fails.

**Comment by bucaran** [comment]
@jonscottclark I was able to reproduce this in a new machine. The problem is just as you described it.

Maybe related:

* https://github.com/fisherman/fisherman/issues/89
* https://github.com/fisherman/fisherman/issues/117

**Comment by bucaran** [comment]
@jonscottclark I think I might have just fixed this.

Can you check again?

**Comment by jonscottclark** [comment]
I'm now getting:

```bash
⟩ fisher install omf/asdfjklgsfdg
Installing >> asdfjklgsfdg
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/oh-my-fish/asdfjklgsfdg/'
No plugins were installed.
```

Much better than before, even though the messaging isn't accurate :)

**Comment by bucaran** [comment]
Good news! :relieved: 

Agreed. We need to improve the error message in the future. Not just this error, but all errors, so I think we are done with this issue.

Can we close?

**Comment by jonscottclark** [comment]
Yup, I think you've got everything you need from me :)

**Comment by bucaran** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8317250/13275568/b192d52a-daf9-11e5-9ef0-2abb35e28876.png)
