### ISSUE TITLE
Add something to Wiki about switching from Oh My Fish

### ISSUE THREAD

**Issue by jonscottclark** [fisherman/fisherman#110]
I was unsure of what would happen when ran the fisherman install after already having Oh My Fish installed.

I didn't know that the Fisherman installer would prepend some lines to my config.fish vs. replacing it completely. And I had to remember that I should remove my OMF stuff:

```bash
set -gx OMF_PATH "/Users/jonclark/.local/share/omf"
source $OMF_PATH/init.fish
```

Simple stuff to figure out but would probably be helpful for people who may be wary of existing config being overwritten.

**Comment by bucaran** [comment]
Yes, this should be added to the Wiki.

Also, make sure you see the revamp installer that tells you how to remove Fisherman if it's already installed.

https://github.com/fisherman/fisherman/issues/108#issuecomment-185996296

**Comment by jonscottclark** [comment]
Did you pull that quote from somewhere, or write it just now?

**Comment by bucaran** [comment]
Wrote it just now.

**Comment by jonscottclark** [comment]
Ok good, thought I missed it in the docs :)

I still think "modifies" is vague and still would make me wonder if I would lose any of my current config, maybe "adds some commands to", instead? Here's how I would edit it:

> Fisherman adds some commands to your existing `config.fish` after installing itself. If you're currently using another framework like Oh My Fish or Wahoo, make sure you remove (or comment out) any lines in your `config.fish` that load those frameworks so that they don't conflict with Fisherman.

I think that should be sufficient for the level of user who would be installing this stuff :)

**Comment by bucaran** [comment]
@jonscottclark Sounds, good. How should we formulate the question?

Also, despite of Fisherman being an upgrade for OMF/Wahoo, there is actually nothing preventing you from using both or all of them simultaneously, so the text you wrote can be misleading if we want to get super technical.

**Comment by bucaran** [comment]
What do you think about it now?

```
### How can I upgrade from an existing Oh My Fish! or Wahoo installation?

1. Backup your [dotfiles](https://en.wikipedia.org/wiki/Dot-file) and other sensitive data first.
2. Remove Oh My Fish! `$OMF_PATH` and `$OMF_CONFIG` directories.
  
  ```fish
  rm -rf {$OMF_PATH,$OMF_CONFIG}
  ```

3. Install Fisherman.

  ```fish
  curl -sL get.fisherman.sh | fish
  ```

> This will add some commands to your existing `config.fish`. To completely remove Oh My Fish! or Wahoo, make sure you remove (or comment out) any lines in your `config.fish` that load those frameworks.

```

**Comment by bucaran** [comment]
Closing as fixed :+1:
