### ISSUE TITLE
Q: is `fisher install` the only way to switch themes?

### ISSUE THREAD

**Issue by jonscottclark** [fisherman/fisherman#111]
I have a few themes installed and when I want to switch, the only way I see to do it is `fisher install mytheme`, which makes sense because it just grabs from the cache and activates it. Maybe some clarification is needed in the docs about **the dual nature of `fisher install`**, especially when it comes to themes, instead of making another command like `fisher activate mytheme` which would seem really unnecessary and would just be an alias of `fisher install` anyway.

**Comment by bucaran** [comment]
As you have already discovered, in Fisherman, we make no real distinction from plugins or themes, but maybe I should make this clearer in the docs?

I think people upgrading from OMF may be confused, but I am not sure if that would be the case for newbies too. 

What do you say we add this to the wiki?

**Comment by jonscottclark** [comment]
Maybe just say that if you install a theme, it will become active immediately; and to activate a theme you already have installed, just run `fisher install` again and it will grab it from the cache and activate it.

How you word this is up to you, but I think that would clear up any confusion.

**Comment by bucaran** [comment]
@jonscottclark Here is a [start](https://github.com/fisherman/fisherman/wiki/FAQ#how-do-i-switch-prompts). How can we make that answer more useful and stay concise at the same time?

**Comment by jonscottclark** [comment]
I would change the order of the described actions:

From:

> Installing a prompt or theme is the same as switching themes.

To:

> Switch to a prompt or theme by running the `install` command again.

The "again" will remind people that it's something they already know.

**Comment by bucaran** [comment]
Sounds better to me too. 

[Done](https://github.com/fisherman/fisherman/wiki/FAQ#how-do-i-switch-prompts).
