### ISSUE TITLE
Installation error on Raspberry Pi

### ISSUE THREAD

**Issue by adaigre** [fisherman/fisherman#113]
I've just installed the lasted Raspbian lite on my raspberry and build Fish from source.
When I try to install fisherman I get : 

> alexandre@jim ~> curl -sL get.fisherman.sh | fish
 ✓ Downloading Fisherman to ~/.local/share/fisherman
 ✓ Creating the configuration in ~/.config/fisherman
 ✓ Updating the registry index
 × Installing CLI dependencies

> Sorry, but I couldn't install Fisherman. Some things you can try:

> → Upgrade your Git version (^2.0)
 → Upgrade your Fish version (^2.2.0)
 → Make sure you can write to
 → Make sure you are connected to the Internet

For more help visit http://issues.fisherman.sh
Does the installer write logs somewhere ?
Any idea ?

**Comment by pickfire** [comment]
@adaigre, I am using raspberry pi 2 with archlinux arm all the time, I don't found any issue installing fisherman with fish 2.2.0 and the latest git. (note that some version before that current latest git might have problem installing fisherman)

What is your `uname -a` and `fish -v`? Can you please try out the latest fish git if you have found any issues?

**Comment by bucaran** [comment]
@pickfire It seems that the OP fish version is fine, probably, the problem is `fisher` failing to download the two deps it currently uses (spin and debug). 

@adaigre The installer does not write logs anywhere. I'll work on that for Fisherman 0.9.0 :smile:

**Comment by adaigre** [comment]
@pickfire I used the latest git to build 
`git --version` -> `git version 2.1.4`
`uname -a` -> `Linux jim 4.1.17-v7+ #838 SMP Tue Feb 9 13:15:09 GMT 2016 armv7l GNU/Linux`
`fish -v` -> `fish, version 2.2.0-622-g613739b-dirty`

**Comment by bucaran** [comment]
@adaigre Have you tried installing Fisherman again? Maybe there was a problem with the two deps that are pulled after installing Fisherman (debug and spin).

**Comment by adaigre** [comment]
@bucaran Yes I tried few seconds ago from a different network connection and same result.

**Comment by bucaran** [comment]
However, it seems you were able to get past installing Fisherman itself. So, do you have the `fisher` command? If you do, try `fisher install spin`.

**Comment by pickfire** [comment]
@adaigre Can you try `fisher update` and `fisher install spin` like @bucaran said.

I can't reproduce this in archlinux arm.

**Comment by adaigre** [comment]
It seems that I have an issue with my Fish anyway 
`fish: Unknown command 'bc'` appears on autocompletion

**Comment by pickfire** [comment]
@adaigre I recall that problem in fish issues, let me check.

**Comment by bucaran** [comment]
@adaigre Make sure you have fish 2.2.0 and `bc` in your system and let us know if that got everything fixed (likely).

**Comment by bucaran** [comment]
@adaigre Do you happen to have `$fish_debug` variable set? Most probably not the problem here, but I just pushed a fix.

https://github.com/fisherman/install/commit/117f696e3c44412ecddc698f04c356cf03978abf

**Comment by adaigre** [comment]
I install the `bc` package and re-run the fisherman install and it works !
Sorry for the inconvenience.

**Comment by bucaran** [comment]
Glad to know you got things working. :+1:

**Comment by pickfire** [comment]
Good luck and have a nice day!
