### ISSUE TITLE
Add --color option to fisher search or make fisher search use color by default and add --no-color option.

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#115]
Add --color option to fisher search

### or 

make fisher search use color by default and add --no-color option.

If we choose the latter, is more fun, but some updates need to be made in all commands using `search` internally.

**Comment by pickfire** [comment]
@bucaran, probably color should be enabled all the time, except during a pipe.

**Comment by bucaran** [comment]
@pickfire We use `eval` to evaluate sub commands, so I believe there is no easy way to do this. I'll try, but I am almost sure this is impossible.

**Comment by pickfire** [comment]
I have used `eval` in bash a few times (no choice or I wouldn't do it) but I doesn't know any info about adding this option currently, probably need some research.

**Comment by bucaran** [comment]
In fish you use `isatty`, but inside `fisher_search` `isatty` will wrongly tell us we are inside a pipe even if we are not. I could be wrong, but if I recall correctly and the above is true, then like I said, it's not possible. But in any case, using a `--no-color` flag is also ok.

**Comment by pickfire** [comment]
@bucaran, yeah, of course. I did `isatty | echo $status` in a terminal:
```
0
```
It seems like it doesn't know that it is in a pipe.

**Comment by bucaran** [comment]
@pickfire I think we are discussing two different things!

Detecting the pipe is possible, but buggy in my experience (I will try again though) if the case was:

```fish
STDIN | fisher search
```

But our case is:

```
fisher search | PARSE_OUTPUT
```

How does `fisher search` know that its output will be piped into `PARSE_OUTPUT`. 

Which is why I think we need a `fisher search --no-color` option if we were to use color **by default** in search in the future.

**Comment by pickfire** [comment]
Ah, I know more about it now, fisher doesn't know what will happen in the future.

**Comment by bucaran** [comment]
@pickfire Yeah, maybe we can make it know in time for 1.0 :smile: (jk)
