### ISSUE TITLE
Creating nvm plugin 

### ISSUE THREAD

**Issue by ericwooley** [fisherman/fisherman#117]
I am trying to create an nvm wrapper that depends on bass and I get an error about a cache/nvm folder not existing. 

```bash
Installing >> nvm
Now using node v5.7.0 (npm v3.6.0)
cd: The directory '/Users/ericwooley/.config/fisherman/cache/nvm' does not exist
/usr/local/Cellar/fish/HEAD/share/fish/functions/cd.fish (line 9): 		builtin cd $argv
                                                                   		^
in function 'cd'
	called on line 72 of file /usr/local/Cellar/fish/HEAD/share/fish/functions/pushd.fish
	with parameter list '/Users/ericwooley/.config/fisherman/cache/nvm'

in function 'pushd'
	called on line 9 of file ~/.local/share/fisherman/functions/__fisher_url_from_path.fish
	with parameter list '/Users/ericwooley/.config/fisherman/cache/nvm'

in function '__fisher_url_from_path'
	called on line 4 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish
	with parameter list '/Users/ericwooley/.config/fisherman/cache/nvm'

in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/__fisher_plugin_enable.fish

in function '__fisher_plugin_enable'
	called on line 133 of file ~/.local/share/fisherman/functions/fisher_install.fish
	with parameter list 'nvm /Users/ericwooley/.config/fisherman/cache/nvm'

in function 'fisher_install'
	called on line 1 of file -
	with parameter list 'ericwooley/fisher-nvm'

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/HEAD/share/fish/functions/eval.fish

in function 'eval'
	called on line 59 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'install ericwooley/fisher-nvm'

Aye! 1 plugin/s installed in 3s
```

My repo is here (it's a pretty basic setup)  https://github.com/ericwooley/fisherman-nvm

I noticed that `fisher install omf/nvm` yeilds a very similar result.

Anyone know more about this?

**Comment by bucaran** [comment]
@ericwooley Thanks! I think this could be related to https://github.com/fisherman/fisherman/issues/109

In the mean time a few tips:

* Do not use the `fisherman` prefix to name your repo as it has nothing to do with Fisherman. Think of it this way, Fisherman is a universal installer, it will work with any of the existing plugin systems (OMF, Wahoo, Tackle, and the extensions added by `__fisher_*`). I suggest `fish-nvm` :smile: 

* Also, there is no `omf/nvm`. Did you mean https://github.com/derekstavis/plugin-nvm?

**Comment by ericwooley** [comment]
@bucaran 
maybe! shoot, I wonder if that was the problem!

durp durp durp. https://github.com/derekstavis/plugin-nvm runs fine.

**Comment by bucaran** [comment]
@ericwooley You are welcome to continue developing your wrapper using Bass though, or rather, use just bass? 

Let me know if you need help with anything and if you need to troubleshoot something → <http://join.fisherman.sh>

**Comment by ericwooley** [comment]
@bucaran Thanks, I really just wanted to be able to use this nvm command, and thought it would be a fine opportunity to make a plugin. Since I thought the other nvm plugin wasn't working.

I'll make another plugin someday, but I need to think of something useful first.

**Comment by bucaran** [comment]
:+1: Cool!

**Comment by shangsunset** [comment]
does `plugin-nvm` work in fisherman? i installed in with fisherman but got `bash: nvm: No such file or directory`

**Comment by bucaran** [comment]
@shangsunset I think most people use [`bass`](https://github.com/edc/bass), because it's a universal utility that works not just for nvm, but for other bash scripts too and developers don't like to reinvent the wheel. 

I use [`n`](https://github.com/tj/n), which I find simpler than nvm and has been working well for me since day 1.

I personally don't like plugin-nvm because it teaches you the wrong thing and it's not the _fishy_ way of accomplishing nvm integration. Plus, you are also forced to install omf, and that will make your shell awfully slow as you start using more plugins.

EDIT: So the reason plugin-nvm does not work on fisherman is because that plugin is deliberately made to work only with omf, it's all a dirty game that does not benefit anyone. 

@jethrokuan What do you use?

**Comment by jethrokuan** [comment]
I don't version node, I always just use the latest node/nvm arch gives me.

**Comment by bucaran** [comment]
@jethrokuan That's interesting.

@shangsunset I really recommend you check out [tj/n](https://github.com/tj/n).

**Comment by shangsunset** [comment]
@bucaran I heard when using `n`, whenever you switch node version some npm modules will stop working. Thats my only concern.

**Comment by decors** [comment]
@shangsunset 
`derekstavis/plugin-nvm` needs $nvm_prefix variable.

please try
```
set nvm_prefix /path/to/nvm/dir
nvm
```

**Comment by bucaran** [comment]
@decors Are you running `plugin-nvm` with fisherman? 

@shangsunset I think `n`'s only issue is when working with **global** modules. Maybe @qw3rtman can kindly clarify for us.

**Comment by decors** [comment]
@bucaran Yes. its works for me.

**Comment by bucaran** [comment]
@decors Interesting.

@orangecms What did you end up doing btw?

**Comment by shangsunset** [comment]
@decors @bucaran I tried setting nvm_prefix and defining that nvm function and they make nvm work but installed node and npm wont work on shell startup

**Comment by bucaran** [comment]
@shangsunset When fish starts it sources your ~/.config/fish/config.fish (if there is any). In that file we initialize fisherman which will do 2 things:

* add its function path to fish_function_path
* source every file inside `$fisher_config/conf.d`

So, to run your code at startup you need to add it to config.fish or write a plugin that does it for you, if you write that plugin then you can even share it and help others that were in your same position.

I could help you more easily if you come http://join.fisherman.sh

**Comment by shangsunset** [comment]
@bucaran thanks. i did add that function in `config.fish` which made nvm command working but not for node or npm.

**Comment by bucaran** [comment]
@shangsunset I think it's better if you join the chat, it seems to me you are fundamentally confused about how fish works, which is probably causing you to become desperate and run to install the first thing that seems to work.

Nothing wrong with that, we all started somewhere, but this thread is not going anywhere. Come over to the chat and I will walk you through every step of the process.

**Comment by shangsunset** [comment]
@bucaran yea you are right :) joined the chat. thanks for the invite!
