### ISSUE TITLE
Add --rollback option to `fisher update` to make updates potentially less frustrating

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman#119]
This gives users a chance to try new updates. If the update breaks their config, they can simply rollback to the previously installed version.

**Comment by bucaran** [comment]
Interesting idea. What do @daenney @pickfire @jonscottclark @josegonzalez @colstrom and @kballard   @alphapapa and @jethrokuan think about this?

**Comment by pickfire** [comment]
@bucaran Looks nice, but it might be difficult to setup as there is a lot of differences between versions. And it might be even hard to rollback twice.

**Comment by jethrokuan** [comment]
@pickfire this would simply involve copying and backing up the current folder, i.e. simply caching the current working plugin. Rolling back would then be simple file manipulation. Rolling back twice is something that someone would be unlikely to do, can you think of someone's use case for that?

**Comment by pickfire** [comment]
@jethrokuan, that's a special case, it's possible.

**Comment by bucaran** [comment]
> rollback twice

This is funny, especially because users should only be able to roll back to the first version that introduced the roll back feature.

I agree with @jethrokuan, this is actually simpler than it seems.

```
fisher update
# save copy of fisher_home inside cache
# update as usual
...
# something is broken and the user wants to roll back
fisher update --roll-back
# blow up fisher_home, replace with copy, delete existing backup to 
# indicate roll-back feature we have reached the end of the recorded
# backup history
```

**Comment by jethrokuan** [comment]
@bucaran wrt encouragement of rolling back, at best we could only encourage reporting of such incidents. This could be facilitated with another flag, or simply just printing a plea to report whatever bug they're seeing so we can see to it.

**Comment by bucaran** [comment]
@jethrokuan I am starting to think this should be a plugin. @pickfire ?

**Comment by jethrokuan** [comment]
@bucaran definitely a possibility, but should it be opt in or should it come by default?

**Comment by bucaran** [comment]
Maybe? Or users can simply `fisher install *it*`.

**Comment by josegonzalez** [comment]
I like it, though as a default plugin.

**Comment by bucaran** [comment]
Closing as likely, but later and as plugin.

**Comment by alphapapa** [comment]
I'm not sure I understand the idea here.  But it seems to me that the solution is to use git.  Operations like trialing and rolling back configurations are essentially branching and merging.  That's what git is designed for.  IMO any such feature that doesn't use git is doing it wrong.  :)

For example, I use Homeshick and git to manage my dotfiles.  If I wanted to test some kind of Fish stuff, I would just:
```
$ cd ~/.config/fish
$ git checkout -b testing-fish-stuff
$ # install and test stuff
```
Then, if I wanted to keep it, I'd:
```
$ git add .
$ git commit
$ git checkout master
$ git merge testing-fish-stuff
```
Or if I wanted to "rollback", I would:
```
$ git checkout -f master
$ git branch -d testing-fish-stuff
```
...followed by a `git clean` if necessary.

Copying directories around is very messy and error-prone.

Having said all of that, maybe this idea is actually out-of-scope for Fisherman.  Maybe the right answer is to tell people to store their configs in git and do their own rollbacks.  :)

**Comment by bucaran** [comment]
@alphapapa I totally agree with you here.

> Maybe the right answer is to tell people to store their configs in git and do their own rollbacks. :)

Absolutely.

**Comment by jethrokuan** [comment]
I agree that git is a good solution, but it might not be the all-encompassing solution. Right now updates try to be completed gracefully, but if not it'll do a hard reset and pull from master. In the latter case I don't think git can save you. This is something that is not within fisher's control.

**Comment by pickfire** [comment]
Not sure about this but I currently don't have any experience with rollback, it's only nice for those people who have break fisherman. I will be here once fisherman is broken.
