### ISSUE TITLE
Add --changelog option to `fisher update` to show changes after updates (both in fisherman and in plugins)

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman#120]
The changelog file can be parsed and presented. Knowing what changes are made can be very helpful in self-debugging. Also, being transparent about what has changed can put the user at ease.

**Comment by pickfire** [comment]
@jethrokuan, a NEWS file will do, nobody might know about `--changelog` based on my humble opinion.

**Comment by jethrokuan** [comment]
@pickfire `--changelog` is still syntax that is still largely undecided. Do you have any suggestions? Also, how would the `NEWS` file look different from the `CHANGELOG.md` file currently in the root directory? We would definitely have to be more choosy about phrasing stuff in there.

**Comment by bucaran** [comment]
NEWS is fine, but we already chose CHANGELOG and there would be no problem in making `fisher update --news` shadow the behavior of `fisher update --changelog` if that was the CLI we decide.

**Comment by pickfire** [comment]
No, that's my only suggestion, `NEWS.md` is shorter than `CHANGELOG.md`. Well, both seems to have a similar meaning, I don't have any opinion about that. Need @bucaran's opinion for this.

**Comment by bucaran** [comment]
NEWS is shorter and I think I considered using one instead of CHANGELOG for the novelty effect, but while I don't have any data to back this up, I will go out on a limb and suggest that a CHANGELOG file is way more common than a NEWS file.

**Comment by bucaran** [comment]
While this would be a nice feature, it seems that the idea showed up too late. After 1.0, which (is the next milestone) I expect Fisherman to become lock to major changes and hope to focus on the ecosystem.

I will honor this issue request by adding a little more information when Fisherman updates plugins, the index and / or itself, but nothing too fancy.

**Comment by bucaran** [comment]
Closing as won't fix. If someone wants to take a stab at I won't complain, but I would like to focus on plugins now.
