### ISSUE TITLE
Plugin initialization throws error

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#123]
After a recent update I see the following

```
$ fisher install omf/plugin-thefuck
Installing >> thefuck
fish: Unknown command '__tf_updt'
~/.config/fisherman/conf.d/thefuck.init.fish (line 2):     set -q __tf_func; or __tf_updt
                                                                                ^
in function 'init'
	called on line 1 of file ~/.config/fisherman/conf.d/thefuck.init.fish
	with parameter list '/Users/domoritz/.config/fisherman/conf.d'

in event handler: handler for generic event 'init_thefuck'

Aye! 1 plugin/s installed in **2s**
```

**Comment by bucaran** [comment]
No problem here. 

Did you install `autoinit`?

<img width="733" alt="screen shot 2016-02-25 at 1 59 17 pm" src="https://cloud.githubusercontent.com/assets/8317250/13310294/1dde876e-dbc8-11e5-8819-7b73daa92ba4.png">
<img width="688" alt="screen shot 2016-02-25 at 2 00 17 pm" src="https://cloud.githubusercontent.com/assets/8317250/13310295/1f05e344-dbc8-11e5-98fe-ea796ccb7d9a.png">

**Comment by domoritz** [comment]
Interesting. In a new shell everything works. I guess it was because something from the new version has not been initialized yet. Sorry about that. Will test more carefully next time. 

* Try again
* Uninstall/ install plugin
* Create a new shell
* Try again

**Comment by bucaran** [comment]
It seems that plugin-thefuck was updated recently, this change brought new functions: 

* https://github.com/oh-my-fish/plugin-thefuck/blob/master/functions/__tf_updt.fish

It's possible that Fisherman is evaluating `init.fish` before the functions are properly registered, which would explain you running into that problem, but it being fixed once the functions are loaded.

If you `fisher uninstall plugin-thefuck -f`, reload your shell and try to install again, what happens?

I will try myself too.

**Comment by bucaran** [comment]
I can't reproduce it.

<img width="1192" alt="screen shot 2016-02-25 at 2 11 10 pm" src="https://cloud.githubusercontent.com/assets/8317250/13310491/bd33051e-dbc9-11e5-8237-1e07ec9514ab.png">


If you get this again, please reopen*!*.

**Comment by domoritz** [comment]
Yeah, I force uninstalled since you told me about it when we talked on slack. The issue was only in an old shell but it works fine once I start a new session so it's fine.

**Comment by bucaran** [comment]
Great.
