### ISSUE TITLE
install scripts should not override `fisher_config` and `fisher_home`

### ISSUE THREAD

**Issue by luan** [fisherman/fisherman#127]
I want to be able to:

```fish
set -x fisher_config ~/.dotfiles/fisherman
set -x fisher_home /usr/local/share/fisherman
curl -sL get.fisherman.sh | fish
```

And have my `config.fish` be generated accordingly, pointing to the write customized directories.

Thoughts?

CC @bucaran @jethrokuan

**Comment by bucaran** [comment]
Sounds good to me. You want to export those variables, otherwise the child `fish` process won't pick them up, but other than that :+1: from me.

**Comment by luan** [comment]
Like that?

**Comment by bucaran** [comment]
Yes. @luan This feature is shipping in 0.9.0, but I would like to bring your attention to another issue here.

Why do you want to commit the entire config directory to your dotfiles? In Fisherman there are [fishfiles] → `$fisher_file`. This gentleman stores what plugins/prompts you have enabled / "activated". 

That's all I need to commit to my dotfiles personally.

[fishfile]: https://github.com/fisherman/fisherman/blob/master/man/man5/fisher-fishfile.md

**Comment by luan** [comment]
That's a fair point, I currently have an `init.fish` file inside the `conf.d` directory there, where I set some variables such as `GIT_EDITOR` and such. I also have a couple of `.fish` files in the `functions` directory where I have a few utility functions that help me with day to day things.

I really need to version those few things, but they're now mixed up with all the plugins.

**Comment by bucaran** [comment]
About init files, you don't have to name your files in any special way, if there are inside `conf.d` they will run. Now, if you want to name it `init` and put it inside `conf.d`, then that's alright.

By functions directory, do you mean ~/.config/fish/functions? If so, then great, that is where you should put those files.

There is no single best way to version everything. Maybe you will eventually come up with a flow that others can benefit later, but here are some ideas:

* Make everything a plugin. Share them, or not, but have them up somewhere, for example a Gist. The use Fisherman to install them. They will go into your fishfile and that's who you want to _version_.

* Create a symlink to your fishfile inside `$fisher_config/fishfile` in ~/.config/fish/functions, or change the `$fisher_file` variable to point to a new file inside that directory like:

```
set -g fisher_file ~/.config/fish/functions/fishfile
```

Then version the entire directory.

**Comment by pickfire** [comment]
@luan Like this:
```fish
rm -rf $fisher_config $fisher_home
set -e fisher_config
set -e fisher_home
set -Ux fisher_config ~/.dotfiles/fisherman
set -Ux fisher_home /usr/local/share/fisherman
curl -sL get.fisherman.sh | fish
```
Or the soft link way:
```fish
mv $fisher_config ~/.dotfiles/fisherman
mv $fisher_home /usr/local/share/fisherman
ln -s ~/.dotfiles/fisherman $fisher_config
ln -s /usr/local/share/fisherman $fisher_home
```

**Comment by daenney** [comment]
It's indeed possible to do it by simply using a universal variable though I dislike those for the simple reason that you can't "see" where they're being set, contrary to an entry in `config.fish`. For installation purposes it would work.

I did it the other way around, simply looked at what the install script would do and then applied that myself to my `config.fish` since I didn't want it wiping out all my things.

**Comment by bucaran** [comment]
@luan Done, but not exactly like you proposed.

To modify fisher_home, export FISHER_HOME.
To modify fisher_config, export FISHER_CONFIG.

The reason we used the variable in upper case is for consistency with the Makefile and to not interfere with an existing installation.
