### ISSUE TITLE
Beautify man pages

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#129]
- [x] Beautify those ascii tree diagram
- [x] [Words to avoid](https://github.com/nicholaides/words-to-avoid.vim) in those articles
- [x] Misc fixes / forgotten updates

**Comment by bucaran** [comment]
+1 for words to avoid and I am sure I can think of more things.

One more thing I am trying actively to avoid is using adverbs.

As for the ascii tree diagram, I recall my `man` would not display unicode characters, so I desisted.

**Comment by pickfire** [comment]
> As for the ascii tree diagram, I recall my man would not display unicode characters, so I desisted.

Of course, I always know that and I will make that my first policy, I just want to say that the ascii tree diagram still looks a bit ugly and some part needs some fix.

> One more thing I am trying actively to avoid is using adverbs.

I am not sure what you mean here, one more thing that I am doing is to make those sentences as short as possible as long as the original meanings remain.

**Comment by bucaran** [comment]
Cool. Go for it.

**Comment by bucaran** [comment]
@pickfire Now that Fisherman API is essentially locked, I will go over the documentation and rewrite and fix as much as possible too. In addition, I will simplify the Wiki, re-shoot gifs with the current Fisherman and consolidate as much as possible in preparation for 1.0.

**Comment by pickfire** [comment]
I need to go through all the docs, give me some time. At the moment, you can work on the wiki.

**Comment by bucaran** [comment]
@pickfire If you haven't started, then leave that up to me, and you can review it after I push the new version. I will be doing this from now, over the next few hours. I would love if you can fix anything after that.

**Comment by pickfire** [comment]
I have started since last night, assign this to me and the other parallel thing (haven't started).

**Comment by bucaran** [comment]
Well, the thing is, I will remove some of the docs and consolidate them into one or two documents. I wrote too much docs to begin with.
