### ISSUE TITLE
*.config.fish files in $fish_function_path cause fish to believe a function named *.config.fish exists

### ISSUE THREAD

**Issue by faho** [fisherman/fisherman#13]
In [config.fish](https://github.com/fisherman/fisherman/blob/3386ed052ae4a84338c340d37b98c1742f8a45f6/config.fish#L9-L11), fisherman currently sources everything in $fisher_config/functions that is named *.config.fish.

Only because $fisher_config/functions is in $fish_function_path, this causes an issue:

- fish will complete *.config (e.g. "banana.config" if you have a file called "banana.config.fish")

- fish will mark it as a valid command via syntax highlighting, and only fail once it is executed

What you want to do is the same thing I proposed in https://github.com/fish-shell/fish-shell/pull/2498: Make a new directory for these kinds of always-sourced non-autoloaded non-function files that is _not_ in $fish_function_path.

**Comment by bucaran** [comment]
Thanks @faho!

I propose calling the directory either `load` or `config` and putting it inside `$fisher_config`.
