### ISSUE TITLE
Update, root of plugin manager

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#130]
- [ ] Add `fisher update all` to update *all* plugins **concurrently**

**Comment by bucaran** [comment]
What's wrong with

```
fisher -l | fisher update
```

**Comment by jethrokuan** [comment]
nothing is wrong with `fisher -l | fisher update`, but I'm expecting some users who are not proficient with the cli to struggle with this.

Anyway, i'd suggest `fisher update --all` or `fisher update -A` instead, `fisher update foo` should be reserved for updating the `foo` plugin.

**Comment by pickfire** [comment]
@jethrokuan, I suggest `fisher update all` which @bucaran suggest to me.

@bucaran, I did some research, the **report** is here:

Using `xargs`, `-P` means `--max-procs`:

    fisher -l | cut -c 2- | xargs -n 1 -P 0 fish -c 'fisher update'

Using `parallel` (not installed by default in many distros probably):

    setenv PARALLEL_ENV (functions fisher_update|perl -pe 's/\n/\001/')
    fisher -l | cut -c 2- | parallel fisher_update

Differences (some taken from `man parallel`):

1. xargs deals badly with special characters (such as space, ' and ")
2. xargs can run a given number of jobs in parallel, but has no support for
   running number-of-cpu-cores jobs in parallel.
3. In my humble opinion, I think parallel is probably a bit slower than xargs
4. parallel have stupid ads during first startup

**Comment by bucaran** [comment]
@pickfire Looks amazing to be honest. Have you actually tried that? What were your results? Maybe try running some benchmarks.

:+1:

**Comment by jethrokuan** [comment]
@pickfire great stuff! parallel doesn't come with my distro. I'd personally like `xargs` as default, and `parallel` as part of a variable that can be set to choose the parallelization option.

**Comment by pickfire** [comment]
I think I like `xargs` more as `parallel` have longer startup time (what they said so) but too bad `xargs` doesn't have any support for `functions`.

**Comment by pickfire** [comment]
It seems like the `xargs` command still doesn't work, the parallel command works instead:
```fish
fisher -l | cut -c 2- | parallel fisher_update
```

**Comment by pickfire** [comment]
For the current benchmarking:

1. `fisher -l | cut -c 2- | parallel fisher_update`: 14s
2. `fisher -l | cut -c 2- | fisher_update -`: 24s
3. `fisher -l | cut -c 2- | xargs -d "\n" -P0 -I {} fish -c 'fisher_update {}'`: Command too long (FAIL)

I have 4 cores, updating `debug`, `fishtape` and `spin`.

**Comment by bucaran** [comment]
@pickfire Make sure you always use `fisher_update -`.

**Comment by pickfire** [comment]
@bucaran As I said, it won't work as there is `*` in front of the words, I really hope that it is deleted. Output:
```fish
> fisher l | fisher u -
fisher: ' debug' is not a valid name, path or URL.
fisher: ' fishtape' is not a valid name, path or URL.
fisher: ' spin' is not a valid name, path or URL.
No plugins were updated.
```

**Comment by bucaran** [comment]
@pickfire That's a bug in 1.0.0-rc, and it's now fixed in my local build. We'll be pushing VERY soon :smile:

**Comment by pickfire** [comment]
Ah, this works:
```fish
> fisher l -b | fisher u -
Updating >> debug
Updating >> fishtape
make: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
Updating >> spin
Aye! 3 plugin/s updated in 25s
```

**Comment by bucaran** [comment]
@pickfire That's sweet. If only `parallel` was installed by default everywhere.

**Comment by pickfire** [comment]
Okay, I will submit a pull request for this.

**Comment by jethrokuan** [comment]
I'm not sure if this will work: `fisher list | xargs -n 1 -P20 fish -c "fisher u -"`

It says for me:
```
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
No plugins were updated.
```

**Comment by pickfire** [comment]
@jethrokuan, it won't work, there is no input for that.

**Comment by pickfire** [comment]
For this, only parallelism for `fisher update all` is useless, I think I will add support the update feature.
And I need to split another update function to just update a single plugin.

I am not sure how to use the `debug` thing, for me I need to split:
```fish
            if set -q plugins[1]
                printf "%s\n" $plugins
            else
                __fisher_file
            end | __fisher_update_plugin
```

So that it can update concurrently but there is a fallback which is that those variables won't be shared with other functions.

**Comment by bucaran** [comment]
@pickfire Update has an --all option now which is why I closed this issue. But we can create a new one to track the parallel feature. I can assign it to you too if you wish.
