### ISSUE TITLE
Error when installing plugin from folder with whitespace

### ISSUE THREAD

**Issue by iONsky** [fisherman/fisherman#132]
I tried to install a plugin/theme from a folder that contains a whitespace but sadly fisherman exits with an error.

Folder: 
> /Users/Test/Downloads/theme master/

Output: `fisher install .`
> Installing >> master theme master
> fatal: repository '/Users/Test/Downloads/theme' does not exist
> No plugins were installed.

**Comment by pickfire** [comment]
I can reproduce this.

**Comment by bucaran** [comment]
@iONsky Thanks. The validation should catch this is an invalid name and provide a better error message.

**Comment by iONsky** [comment]
@bucaran You mean the name or the folder can't contain any whitespace?

**Comment by bucaran** [comment]
@iONsky At the moment, it can't... but if we can figure out a way to extract the name of the plugin from the directory's name, then sure. 

In this case, what do you want to use as the name for your plugin?

**Comment by jethrokuan** [comment]
In my opinion, while fisherman can be accommodating with folder names like these, I think the appropriate action here is to only allow certain folder naming conventions and provide readable error messages if otherwise. Having a convention for things like these will ultimate minimize work done to provide support, so we can focus on the key features of fisherman.

**Comment by bucaran** [comment]
Already fixed locally, ships in 1.0. Basically, we detect the invalid path and print an error message.

**Comment by iONsky** [comment]
I noticed something else...the problem occurs even if the **path** contains a whitespace.
For example `/Users/Test/Development Tools/theme/`

**Comment by bucaran** [comment]
@iONsky Nice catch. Ah, this is tricky. It's fixed now and ships with 1.0, but if please keep reporting problems if you keep finding them.

**Comment by iONsky** [comment]
@bucaran Awesome :+1:
