### ISSUE TITLE
Allow users change the current prompt using fish_config

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#133]
Thanks to Gary, for [reporting](https://twitter.com/gaswold/status/703772914294902785) this.

Currently, you can't change your prompt using fish_config, as Fisherman is _before_ in $fish_function_path. You can `fisher uninstall $fisher_prompt` and then use fish_config, but Fisherman can detect if the user used fish_config and uninstall $fisher_prompt for them.

This is basically done, the solution involves overriding `fish_config` and comparing the check sum of fish_prompt.fish before and after fish_config is launched.

```fish
function fish_config -d "Launch fish's web based configuration" -a tab
    set -l config ~/.config

    if set -q XDG_CONFIG_HOME
        set config $XDG_CONFIG_HOME
    end

    set -l path $config/fish/functions
    set -l sum_before (cksum $path/fish_prompt.fish ^ /dev/null | awk '{ print $1 }')

    debug "fish_config start"

    eval $__fish_datadir/tools/web_config/webconfig.py $tab
    
    debug "fish_config end"

    if test ! -z "$fisher_prompt"
        set -l sum_after (cksum $path/fish_prompt.fish ^ /dev/null | awk '{ print $1 }')

        debug "fish_prompt check sum before: %s" $sum_before
        debug "fish_prompt check sum after: %s" $sum_after

        if test "$sum_before" != "$sum_after"
            debug "Uninstall %s" "$fisher_prompt"
            fisher_uninstall "$fisher_prompt" -q
        end
    end
end
```

@jethrokuan Ping

**Comment by bucaran** [comment]
![s](https://cloud.githubusercontent.com/assets/8317250/13387486/54f1ef9a-defa-11e5-8e98-b86017c8f409.gif)

**Comment by jethrokuan** [comment]
:+1: good fix. Moving forward I think we should encourage having all config managed by fisherman. I'm not sure what `segment` looks like now, but I hope it can replace `fish_config prompt`.

**Comment by bucaran** [comment]
> all config managed by fisherman

Plugins!
