### ISSUE TITLE
"fisher search --tags=theme" returns no result

### ISSUE THREAD

**Issue by predmijat** [fisherman/fisherman#137]
"fisher search --tags=theme" returns no result and I'm not sure how to debug it.
Note: it's not a fresh install, but I'd really like to know why it doesn't work now, any way to debug it?

**Comment by bucaran** [comment]
@predmijat The correct search query is `fisher search --tag=prompt`.

> **Rationale** I am trying to avoid the term "theme", so no plugins use this tag. The reason is that themes are no different from other plugins, they may define any functions and if one or two happen to be `fish_prompt` or `fish_right_prompt` then we think of it as theme, but fish calls them `prompt` not themes and the function name does not say `theme` anywhere either.

**Comment by predmijat** [comment]
:+1:
