### ISSUE TITLE
Parallel fish_update

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#138]
For work to be done easier:

1. The `fisher update --all` should be something like the following to upgrade each plugin easily:
```fish
fisher_list --enabled | tr '\n' ' ' | fisher_update -
```
2. There should be a `__fisher_update_plugin` so that I can easily do something like:
```fish
            if set -q plugins[1]
                printf "%s\n" $plugins
            else
                __fisher_file
            end | while read -l item path

                ( debug "Validate %s" $item

                if not set item (__fisher_plugin_validate $item)
                    debug "Validate fail %s" $item
                    printf "fisher: '%s' is not a valid name, path or URL.\n" $item > $stderr
                    continue
                end

                debug "Validate ok %s" $item

                if not set path (__fisher_path_from_plugin $item)
                    set total (math $total - 1)
                    printf "fisher: '%s' not found.\n" $item > $stderr
                    continue
                end

                set -l name (printf "%s\n" $path | __fisher_name)

                printf "$indicator Updating " > $stderr

                switch $total
                    case 0 1
                        printf "%s\n" $name > $stderr

                    case \*
                        printf "(%s of %s) %s\n" $index $total $name > $stderr
                        set index (math $index + 1)
                end

                if test ! -L $path
                    debug "Update start %s" "$name"

                    if not spin "__fisher_path_update $path" --error=$stderr -f "  @\r"
                        debug "Update fail %s" "$path"
                        continue
                    end
                end

                debug "Update ok %s" "$name"

                if __fisher_plugin_can_enable "$name" "$path"
                    debug "Enable %s" "$name"

                    fisher_install --quiet --force -- $name
                end ) &

                set count (math $count + 1)

		math $count % $cores == 0
		and wait
            end
```

I really don't know what needs to be done at the current case, there is too much needed to be changed, I don't have any idea how to update it now unless the function is really separated.

**Comment by bucaran** [comment]
If you need to write a `__fisher_update_plugin` function go ahead.

**Comment by pickfire** [comment]
@bucaran Assign this to me, don't work on this yet, it seems like there is some bugs with fish.

**Comment by pickfire** [comment]
@bucaran I tried to write it but it seems like it can't share the variables, any help here?

**Comment by bucaran** [comment]
Another problem I see here is, how are we going to reset completions and key bindings within the same shell process.

I think this is going to be hard.

**Comment by pickfire** [comment]
@bucaran Oh, I forgot it needs to reset completions and key bindings. I think we can probably do something like:
```fish
echo >> /tmp/key.fish
```

After that:
```fish
mv /tmp/key.fish file
```

Is that okay, I don't think it would be that bad that two files are writing on top of each other simultaneously.

Second solution:
```fish
echo >> /tmp/keys/$i.fish
```
Then:
```fish
cat /tmp/keys/* > file
```
The second approach might be better.

**Comment by pickfire** [comment]
@bucaran Oh, I forgot it needs to reset completions and key bindings. I think we can probably do something like:
```fish
echo >> /tmp/key.fish
```

After that:
```fish
mv /tmp/key.fish file
```

Is that okay, I don't think it would be that bad that two files are writing on top of each other simultaneously.

Second solution:
```fish
echo >> /tmp/keys/$i.fish
```
Then:
```fish
cat /tmp/keys/* > file
```
The second approach might be better.

**Comment by bucaran** [comment]
@pickfire And TBH it's unlikely fish will implement a way to background functions in the near future, so I'll leave it up to you to decide to close or keep open.

**Comment by pickfire** [comment]
@bucaran I will keep it open and make this the oldest issue, hehe.

By the way, I am a bit busy setting up my static site generator in github, I hope I can remember this issue.

**Comment by pickfire** [comment]
This issue won't be solved any sooner as there are some issues with fish-shell/fish-shell#2782, I think you should check it there.

**Comment by bucaran** [comment]
2587ca9aebf59592c1d8ee5932bfa7260359e96c

Done.
