### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by nklmilojevic** [fisherman/fisherman#140]
Hi,

I'm having this error. I'm using fish 2.2.0 from homebrew.

nkl@Nikolas-MacBook-Pro ~> curl -sL get.fisherman.sh | fish
Assertion failed: (is_interactive >= 0), function get_is_interactive, file proc.cpp, line 141.
 ✓ Downloading Fisherman to ~/.local/share/fisherman
Assertion failed: (is_interactive >= 0), function get_is_interactive, file proc.cpp, line 141.
 ✓ Creating the configuration in ~/.config/fisherman
Assertion failed: (is_interactive >= 0), function get_is_interactive, file proc.cpp, line 141.
 ✓ Updating the registry index
Assertion failed: (is_interactive >= 0), function get_is_interactive, file proc.cpp, line 141.
 ✓ Installing CLI utilities
 ✓ Done!

Does anyone have a solution?

Thanks,

Nikola

**Comment by bucaran** [comment]
I think @pickfire was having the exact same issue at one point.

@faho Would you mind commenting on this issue?

**Comment by faho** [comment]
This is fish issue [2280](https://github.com/fish-shell/fish-shell/issues/2280) - fish_indent may call something meant for interactive use, tripping an assertion.

You'll want [81cdceddd33bf831d206f6cd167c6bae5ef81225](https://github.com/fish-shell/fish-shell/commit/81cdceddd33bf831d206f6cd167c6bae5ef81225), which will be in the next release.

**Comment by faho** [comment]
Or otherwise, you'll want to not override your normal locale via LC_ALL.

**Comment by bucaran** [comment]
@faho Thanks. @nklmilojevic Let me know if this works for you!

**Comment by pickfire** [comment]
@nklmilojevic Try the latest fish git or fish 2.2.0, both works. But at some point between both of it, fails.

**Comment by bucaran** [comment]
@nklmilojevic Ping.

**Comment by nklmilojevic** [comment]
Sorry for not responding. Works ok now, thanks!

**Comment by bucaran** [comment]
:+1: Thanks.

Closing as resolved.
