### ISSUE TITLE
Plugin wishlist

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#143]
Now that 1.0 is out, more plugins can be ported to fisherman. 

### Wishlist

- [x] [grc](https://github.com/oh-my-fish/plugin-grc) command output highlighting. Seems to work in the session where the plugin in installed but not in new sessions.
- [x] More "native" plugins that do not incur cost of event handling
- [ ] Plugin to give suggestions for unknown commands

### Cancelled 

* ~~Make plugins compatible with other shells/applications~~
* ~~Plugin to improve the display of suggestions~~

**Comment by domoritz** [comment]
More explanations for grc:

Installing it causes the following issue

```
$ fisher install omf/plugin-grc
▸ Installing grc
fish: Could not autoload item 'grc', it is already being autoloaded. This is a
circular dependency in the autoloading scripts, please remove it.
1 plugin/s installed in 1s
```

**Comment by bucaran** [comment]
@domoritz In the case of `grc` the fix is simple, we just need to ask the maintainers of the plugin to change the name `grc.fish` to `init.fish`.

![xxxxx](https://cloud.githubusercontent.com/assets/8317250/13451400/0155bf40-e082-11e5-8e0f-c0dd87ef71c9.jpg)

**Comment by bucaran** [comment]
Good idea, let's keep track of that plugin wishlist here. :+1:

**Comment by pickfire** [comment]
- [ ] Make plugins compatible with other shells/applications

**Comment by bucaran** [comment]
@domoritz Any other plugins in the wish list?

**Comment by domoritz** [comment]
Right now I'm using a mix is omf and fisherman plugins. fasd, thefuck, grc, bobthefish, osx, and spin. I'm not quite sure what the performance impact of some of the non-fisherman plugins is but I haven't had any major problems. 

I'm quite happy right now but if I had to name some improvements to my terminal it would be better autocorrection as done by zsh. Fish only prints `fish: Unknown command` if it doesn't know a command. Zsh suggests alternatives `zsh: correct ?? to ?? [nyae]?`. I can use thefuck to correct the command but it's another command I have to type. Another improvement I brought up with fish shell directly is the presentation of suggestions (https://github.com/fish-shell/fish-shell/issues/2698). However, I think that's beyond what a plugin can do. 

I updated the original issue description.

**Comment by bucaran** [comment]
Thanks for the update! I have deprecated autoinit and the legacy plugins as all OMF plugins work now out of the box with Fisherman and without any hacks.

I'll check out your suggestions and try to come up with something.

**Comment by bucaran** [comment]
@pickfire 

> Make plugins compatible with other shells/applications

Do you mean porting the existing plugins to Zsh, etc?

**Comment by pickfire** [comment]
@bucaran, I mean like make it usable on other platform like bash/zsh/mksh or maybe even in programming languages such as C.

**Comment by bucaran** [comment]
@pickfire I see. Well, that's a nice idea, but certainly out of the scope of Fisherman, so we should remove that one from the list.

**Comment by bucaran** [comment]
Also, I am scratching number 2 as well, since OMF plugins work out of the box in Fisherman now. 
 https://github.com/fisherman/fisherman/issues/143#issuecomment-195863402

**Comment by bucaran** [comment]
That leaves only 3.

Tracking in #155.
