### ISSUE TITLE
Review new simplified docs and align with README

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#151]
With the exception of individial command help, all the docs have been integrated into a single document. The README has been updated to include this document too.

+ [x] Revise and proof-read man/man1/fisher.md
+ [x] Update README accordingly.
+ [ ] Add animated Gifs to the README.
+ [ ] ~~Emphasize $fisher_ variables.~~

Proof-read help wanted.

/cc @pickfire @jethrokuan

**Comment by pickfire** [comment]
proof-read?

**Comment by bucaran** [comment]
Read and mark errors or inconsistencies.

**Comment by pickfire** [comment]
I think it is better to put the `code` as another color (type):
![2016-03-09-231417_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/13639715/fc6f2f72-e64c-11e5-8052-a501f91ad6d3.png)

**Comment by bucaran** [comment]
For the README right? Yes, I agree. 

Also, I think the README should be a simplified version of `fisher.1`.

**Comment by pickfire** [comment]
No, I mean for the man page.

**Comment by bucaran** [comment]
You can't change the color in the man page.

**Comment by pickfire** [comment]
You can use something like:
```man
.RS
.B spt -e 'aplay alarm.wav' -n 'notify-send'
.RE
```

**Comment by bucaran** [comment]
Ha! Nice trick. I am using ronn to generate the *.1* files so those would be overwritten.

**Comment by pickfire** [comment]
@bucaran, I know about that but I think there might be some method to do that in `ronn`, not sure about ronn, haven't used it.

And the `VARIABLES` like `$fisher_home` should be underlined or emphasized.

Idea: A bug section.

```
BUGS
       Bugs? You must be kidding; there is no bugs in this software. But if we happened to be wrong, please report the bugs!
```

**Comment by bucaran** [comment]
Noted.

**Comment by jethrokuan** [comment]
Issues:
1. `fisher help --all` is not a legitimate command. Documentation should read `fisher help` for showing help.
2. Update all plugins in cache should be `fisher update -a`
3. Steps to manually submitting plugins are incorrect (need to fork, push, then send PR)

**Comment by bucaran** [comment]
Closing as mostly resolved.
