### ISSUE TITLE
Dangling symbolic link

### ISSUE THREAD

**Issue by decors** [fisherman/fisherman#153]
Hi @bucaran 
man/man1/fisher-tutorial.1 is a dangling link.

https://github.com/fisherman/fisherman/blob/master/man/man1/fisher-tutorial.1

**Comment by bucaran** [comment]
@decors I think this is on purpose, see https://github.com/fisherman/fisherman/blob/master/completions/fisher.fish#L5

The idea is that users could:

```
fisher help<TAB>
```

and get `tutorial` as one of the options.

<img width="1280" alt="screen shot 2016-03-10 at 12 28 21 pm" src="https://cloud.githubusercontent.com/assets/8317250/13658561/a401e5cc-e6bb-11e5-9037-2de2ef17cf07.png">

Does that make sense?

**Comment by decors** [comment]
@bucaran Thanks!

I tried it.  Then, an error has occurred .
```fish
~> fisher help tutorial
man: warning: /home/vagrant/.local/share/fisherman/man/man1/fisher-tutorial.1 is a dangling symlink
```

It refers to a file under your home directory
```fish
> readlink /home/vagrant/.local/share/fisherman/man/man1/fisher-tutorial.1
/Users/bucaran/c/fisherman/fisherman/man/man1/fisher.1
```

**Comment by bucaran** [comment]
@decors Thanks! I see the problem now :sweat_smile: 

Will submit a patch shortly.

**Comment by bucaran** [comment]
d24a4f0

The dangling link has been exterminated! :smile:

**Comment by decors** [comment]
Thank you for your fix :smiley:
