### ISSUE TITLE
Add "Did you mean?" like feature

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#155]
* Improve suggestions for unknown Fisherman commands / plugins.

> For system-wide commands you should look into [thefuck](https://github.com/nvbn/thefuck).

**See Also**
#144

/cc @domoritz

**Comment by lordlycastle** [comment]
While we at this, may be also a feature that searches for plugins, which aren't installed. Something similar to [Homebrew/homebrew-command-not-found](https://github.com/Homebrew/homebrew-command-not-found)?

**Comment by bucaran** [comment]
Hey @lordlycastle, are you using Fisherman?

Because you can search plugins index the index using `search` since day 1

**Comment by lordlycastle** [comment]
@bucaran I see we're talking about different things. 

Say for example there is a plugin called `potter`, and user enters `potter` and runs it. It'll return an error similar to `fish: Unknown command 'potter'`; since it's __not installed__. So before printing that error message it would check if there is a plugin called `potter` that can be installed with `fisher`, if so output something along the lines of: `The plugin 'potter' is currently not installed. You can install it by typing: fisher install potter`. 

It would search a cached list of plugins for `potter` to determine if it's one of fisher's plugins; cached because it must be quicker. This list can be from last time fisher was updated, or perhaps a plugin that does this.

As for what you're talking about, that's important as well; other package managers already have that.

**Comment by jethrokuan** [comment]
Yes, looking through the cache is an option, meaning this search is looking only at __disabled__ plugins. 

As with the other issues, this can be done through a plugin, but this note that this would make shell startup time longer, for this needs to be sourced at startup.

Fish provides colours to tell you whether a function is available or not, so it's unlikely altogether to run a command when the command is not available.

**Comment by lordlycastle** [comment]
> Yes, looking through the cache is an option, meaning this search is looking only at disabled plugins.

Not looking through cache, but looking through __cached list__ of all plugins available at the time of last update. A text file good enough for basic list, but a `.plist` or `.json` could be used to cached more information about the packages.

The _command-not-found_ is does affect the startup time a lot, however I use my fork of that repo which requires you to edit your `__fish_command_not_found_handler` so no setup was required, as that was run on `fish_command_not_found` event. I imagine we can have multiple functions run on same event so there might not even be need to edit it, just install a new function file as a plugin.

**Comment by pickfire** [comment]
Oh, this seems like a nice feature to be implemented but I haven't seen any of the other project implement similar feature in shell.

**Comment by bucaran** [comment]
@Shadowigor @hilmibakhari

**Comment by bucaran** [comment]
@pickfire Have a look at https://github.com/b4b4r07/zplug, they have a similar idea.

**Comment by pickfire** [comment]
@bucaran, it impressed me that it only consists of one file just like vim-plug. They can also have the idea to install zplug automatically when it isn't there.

I had look through it but didn't saw where the autocorrection begins.

zsh is powerful, but it's slowness upsets me, I tried prezto and antigen in the past, both is very, very slow and it takes seconds to start up.

I think vim-plug still excels in one place, in which where they can display the progress *gracefully* (nice UI) during a parallel update.

**Comment by bucaran** [comment]
@pickfire I think you might be interested in my new fisherman's spinoff project: https://github.com/fishery/fin

**Comment by pickfire** [comment]
@bucaran, I think I am going to look at it, the `fin self-destruct` got me interesting. :boom:

**Comment by bucaran** [comment]
@pickfire Thanks, the self-destroy feature is pretty cool, you don't even have to reset the shell after you are done.

**Comment by pickfire** [comment]
@bucaran, the self destruct feature is something I had implemented in the past to do some surprise to my father when he login. The `fish_greeting` automatically self-destruct after running.

**Comment by bucaran** [comment]
@pickfire Yup, no `curl | fish`, but `curl > fin.fish`.

```
curl -sL git.io/fin > ~/.config/fish/functions/fin.fish
```

**Comment by pickfire** [comment]
@bucaran, looks cool, I have a lot of idea for `fin` currently.

**Comment by bucaran** [comment]
@pickfire Feel free to share your heart at will!

**Comment by lordlycastle** [comment]
@bucaran Oh! This is kinda cool. I would like to help too, though kinda intimidating; such a large file! I'm better at following so it would be best if you can me tell what you might need help with.

**Comment by bucaran** [comment]
@lordlycastle I can walk you through the whole thing, just pick something and let's discuss it.

Help, yes, I need help! I am about to push 1.0 later tonight and start recording history properly.

Maybe you can try breaking it?

**Comment by lordlycastle** [comment]
@bucaran Cool. I'll installed it, I'll keep an eye out for bugs. Do you have a slack chatroom for fin? Since it's better to discuss it there than here.

**Comment by bucaran** [comment]
@lordlycastle I think the #dev room in the fisherman slack is acceptable.

**Comment by bucaran** [comment]
TBH I don't have any plans to implement this feature. While I think it would be nice to have, fisherman has a very capable search engine builtin that can answer anything wrt to plugins as described in the index.

If someone wants to take a stab at this, feel free to reopen.
