### ISSUE TITLE
Are completions supposed to be plugins?

### ISSUE THREAD

**Issue by taylon** [fisherman/fisherman#156]
I was about to submit a completion, but I didn't find any completion in the fisherman index and the README does not mention completions as plugins

> Plugins can be utilities, prompts, commands or snippets.

**Comment by bucaran** [comment]
Totally. Completions can be plugins. Having said that, fish usually ships with completions for everything, so if you created completions for a known command, adding it to fish directly would benefit even more people.

What command did you create completions for?

**Comment by taylon** [comment]
Nice, I created one for [Ember-CLI](http://ember-cli.com/) https://github.com/taylon/fish-ember-completion  =D

**Comment by bucaran** [comment]
Nice. Ember-CLI is a large project used by possibly thousands of people and I think submitting these completions directly to fish upstream would help the community more, but it's up to you! :smile:

**Comment by taylon** [comment]
Yeah, you are right, I'll improve it and submit to Fish =D

Thanks,
