### ISSUE TITLE
theme bobthefish cant autoload in new session

### ISSUE THREAD

**Issue by pantasio** [fisherman/fisherman#159]
open new terminal, fisher still run but bobthefish dont

**Comment by bucaran** [comment]
@pantasio That's odd and I can't repro.

![bob](https://cloud.githubusercontent.com/assets/8317250/13806680/589aa300-eba0-11e5-9fc9-91bddeaf7439.gif)

What is your OS, fisherman version, and the contents of your config.fish?

**Comment by bucaran** [comment]
@pantasio Ping.

**Comment by bucaran** [comment]
@pantasio You are welcome to reopen if you still have this problem.

Closing.

**Comment by pantasio** [comment]
Sorry guys, lated reply

Linux devops 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
fisher version 1.3.1

[config.txt](https://github.com/fisherman/fisherman/files/197030/config.txt)

Or see config.fish below
# Useful functions {{{

function ed; vim ~/.vim/custom-dictionary.utf-8.add; end
function ef; vim ~/.config/fish/config.fish; end
function eff; vim ~/.config/fish/functions; end
function eg; vim ~/.gitconfig; end
function eh; vim ~/.hgrc; end
function ei; vim ~/Dropbox/inventory.markdown; end
function ek; vim ~/lib/dotfiles/keymando/keymandorc.rb; end
function em; vim ~/.mutt/muttrc; end
function ep; vim ~/.pentadactylrc; end
function es; vim ~/.slate; end
function et; vim ~/.tmux.conf; end
function ev; vim ~/.vimrc; end
function ez; vim ~/lib/dotfiles/zsh; end

function ..;    cd ..; end
function ...;   cd ../..; end
function ....;  cd ../../..; end
function .....; cd ../../../..; end

# I give up
alias :q exit
alias :qa exit

# }}}
# Completions {{{

function make_completion --argument alias command
    complete -c $alias -xa "(
        set -l cmd (commandline -pc | sed -e 's/^ *\S\+ *//' );
        complete -C\"$command \$cmd\";
    )"
end

make_completion g "git"

# }}}
# Bind Keys {{{

# Backwards compatibility?  Screw that, it's more important that our function
# names have underscores so they look pretty.
function jesus_fucking_christ_bind_the_fucking_keys_fish
    bind \cn accept-autosuggestion
    bind \cw backward-kill-word
end
function fish_user_keybindings
    jesus_fucking_christ_bind_the_fucking_keys_fish
end
function fish_user_key_bindings
    jesus_fucking_christ_bind_the_fucking_keys_fish
end

# }}}
# Environment variables {{{

set -g -x NIX_LINK "$HOME/.nix-profile"

function prepend_to_path -d "Prepend the given dir to PATH if it exists and is not already in it"
    if test -d $argv[1]
        if not contains $argv[1] $PATH
            set -gx PATH "$argv[1]" $PATH
        end
    end
end
set -gx PATH "/usr/X11R6/bin"
prepend_to_path "/usr/texbin"
prepend_to_path "/sbin"
prepend_to_path "/usr/sbin"
prepend_to_path "/bin"
prepend_to_path "/usr/bin"
prepend_to_path "/usr/local/bin"
# prepend_to_path "/usr/local/share/python"
prepend_to_path "/usr/local/sbin"
prepend_to_path "/usr/local/share/npm/bin"
prepend_to_path "$HOME/lib/dotfiles/bin"
prepend_to_path "/opt/local/bin"
prepend_to_path "/opt/subversion/bin"
prepend_to_path "$HOME/lib/hg/hg"
prepend_to_path "$HOME/Library/Haskell/bin"
prepend_to_path "/usr/local/Cellar/ruby/1.9.3-p194/bin"
prepend_to_path "/Applications/Postgres.app/Contents/MacOS/bin"
prepend_to_path "$HOME/.rbenv/shims"
prepend_to_path "$HOME/bin"
prepend_to_path "/.composer/vendor/bin"
#prepend_to_path "/.local/bin/"

#Drush PATH for fish shell
set --export PATH ~/.config/composer/vendor/drush/drush/ $PATH
#set --export PATH ~/.local/bin/bashmark.sh $PATH
set --export PATH ~/.local/bin/bashmark.sh $PATH


set BROWSER open

set -g -x fish_greeting ''
set -g -x EDITOR vim
set -g -x COMMAND_MODE unix2003
set -g -x RUBYOPT rubygems
set -g -x CLASSPATH "$CLASSPATH:/usr/local/Cellar/clojure-contrib/1.2.0/clojure-contrib.jar"

set -g -x NODE_PATH "/usr/local/lib/node_modules"

set -g -x VIM_BINARY "/usr/local/bin/vim"
set -g -x MVIM_BINARY "/usr/local/bin/mvim"

set -g -x DRIP_SHUTDOWN 30

set -g -x MAVEN_OPTS "-Xmx512M -XX:MaxPermSize=512M"
set -g -x _JAVA_OPTIONS "-Djava.awt.headless=true"

set -g -x GPG_TTY (tty)

function headed_java -d "Put Java into headed mode"
    echo "Changing _JAVA_OPTIONS"
    echo "from: $_JAVA_OPTIONS"
    set -g -e _JAVA_OPTIONS
    echo "  to: $_JAVA_OPTIONS"
end
function headless_java -d "Put Java into headless mode"
    echo "Changing _JAVA_OPTIONS"
    echo "from: $_JAVA_OPTIONS"
    set -g -x _JAVA_OPTIONS "-Djava.awt.headless=true"
    echo "  to: $_JAVA_OPTIONS"
end



# }}}
# Python variables {{{

set -g -x PIP_DOWNLOAD_CACHE "$HOME/.pip/cache"
set -g -x WORKON_HOME "$HOME/lib/virtualenvs"

prepend_to_path "/usr/local/share/python"
prepend_to_path "/usr/local/Cellar/PyPi/3.6/bin"
prepend_to_path "/usr/local/Cellar/python/2.7.1/bin"
prepend_to_path "/usr/local/Cellar/python/2.7/bin"
prepend_to_path "/usr/local/Cellar/python/2.6.5/bin"

set -g -x PYTHONPATH ""
set PYTHONPATH "$PYTHONPATH:/usr/local/lib/python2.7.1/site-packages"
set PYTHONPATH "$PYTHONPATH:/usr/local/lib/python2.7/site-packages"
set PYTHONPATH "$PYTHONPATH:/usr/local/lib/python2.6/site-packages"
set PYTHONPATH "$HOME/lib/python/see:$PYTHONPATH"
set PYTHONPATH "$HOME/lib/hg/hg:$PYTHONPATH"

set -gx WORKON_HOME "$HOME/lib/virtualenvs"
#eval (python -m virtualfish)

set -g -x NLTK_DATA "/Users/sjl/src/ru/malv/nltk_data"

# }}}
# Z {{{

. ~/src/z-fish/z.fish

# }}}
# Prompt {{{

set normal (set_color normal)
set magenta (set_color magenta)
set yellow (set_color yellow)
set green (set_color green)
set gray (set_color -o black)
set hg_promptstring "< on $magenta<branch>$normal>< at $yellow<tags|$normal, $yellow>$normal>$green<status|modified|unknown><update>$normal<
patches: <patches|join( → )|pre_applied($yellow)|post_applied($normal)|pre_unapplied($gray)|post_unapplied($normal)>>" 2>/dev/null

function virtualenv_prompt
    if [ -n "$VIRTUAL_ENV" ]
        printf '(%s) ' (basename "$VIRTUAL_ENV")
    end
end

function hg_prompt
    #hg prompt --angle-brackets $hg_promptstring 2>/dev/null
    set -q -g __fish_has_hg_prompt ; or return

  	set -q -g __fish_hg_prompt_color; and set_color $__fish_hg_prompt_color
  	hg prompt " {branch}{ ({bookmark})}" 2> /dev/null

  	set -q -g __fish_hg_prompt_color_status; and set_color $__fish_hg_prompt_color_status
  	hg prompt "{status}{outgoing}" 2> /dev/null
end

function git_prompt
    if git root >/dev/null 2>&1
        set_color normal
        printf ' on '
        set_color magenta
        printf '%s' (git currentbranch ^/dev/null)
        set_color green
        git_prompt_status
        set_color normal
    end
end

function prompt_pwd --description 'Print the current working directory, shortend to fit the prompt'
    echo $PWD | sed -e "s|^$HOME|~|"
end

function fish_prompt
    set last_status $status

    #z --add "$PWD"

    echo

    set_color magenta
    printf '%s' (whoami)
    set_color normal
    printf ' at '

    set_color yellow
    printf '%s' (hostname|cut -d . -f 1)
    set_color normal
    printf ' in '

    set_color $fish_color_cwd
    printf '%s' (prompt_pwd)
    set_color normal

    hg_prompt
    git_prompt

    echo

    virtualenv_prompt

    if test $last_status -eq 0
        set_color white -o
        printf '><((°> '
    else
        set_color red -o
        printf '[%d] ><((ˣ> ' $last_status
    end

    set_color normal
end

# }}}

if test -f $HOME/.local.fish
    . $HOME/.local.fish
end

true

# Load fishmarks (http://github.com/techwizrd/fishmarks)
. $HOME/.fishmarks/marks.fish
set fisher_home ~/.local/share/fisherman
set fisher_config ~/.config/fisherman
source $fisher_home/config.fish



## Load fish theme with bobthefish

set -g theme_display_git no
set -g theme_display_git_untracked no
set -g theme_display_git_ahead_verbose yes
set -g theme_display_vagrant yes
set -g theme_display_hg yes
set -g theme_display_virtualenv no
set -g theme_display_ruby no
set -g theme_display_user yes
set -g theme_display_vi yes
set -g theme_display_vi_hide_mode default
set -g theme_title_display_process yes
set -g theme_title_display_path no
set -g theme_title_use_abbreviated_path no
set -g theme_date_format "+%a %H:%M"
set -g theme_avoid_ambiguous_glyphs yes
set -g theme_nerd_fonts yes
set -g theme_show_exit_status yes
#set -g default_user your_normal_user
set -g default_user pantasio


I think config.fish of fisherman have been conflict

**Comment by jethrokuan** [comment]
Potential conflicts here:
1. fish key bindings
2. fish_prompt

Improvements to be made on the side:
Don't use `prepend_to_path`, and instead use `$fish_user_paths`:
https://github.com/fish-shell/fish-shell/issues/527

It's expected that `config.fish` files, most configuration is done outside of it.

**Comment by pantasio** [comment]
thanks @jethrokuan 

Comfirm conflicts here:
1. fish key bindings
2. fish_prompt

Solution for my situation:
- Delete fish_prompt

change prepend_to_path to
set --universal fish_user_paths $fish_user_paths type_your_path
Ex:
set --universal fish_user_paths $fish_user_paths /usr/bin
set --universal fish_user_paths $fish_user_paths $HOME/bin

BTW, git style cant show like @bucaran 
![screenshot_2016-04-01_00-44-08](https://cloud.githubusercontent.com/assets/3162016/14185179/e0f8ba80-f7a2-11e5-87f9-9ab084ea29f7.png)

this blank for git command with original config.fish
############## begin config.fish ##################
# Load fishmarks (http://github.com/techwizrd/fishmarks)
. $HOME/.fishmarks/marks.fish
set fisher_home ~/.local/share/fisherman
set fisher_config ~/.config/fisherman
source $fisher_home/config.fish

## Load fish theme with bobthefish

set -g theme_display_git no
set -g theme_display_git_untracked no
set -g theme_display_git_ahead_verbose yes
set -g theme_display_vagrant yes
set -g theme_display_hg yes
set -g theme_display_virtualenv no
set -g theme_display_ruby no
set -g theme_display_user yes
set -g theme_display_vi yes
set -g theme_display_vi_hide_mode default
set -g theme_title_display_process yes
set -g theme_title_display_path no
set -g theme_title_use_abbreviated_path no
set -g theme_date_format "+%a %H:%M"
set -g theme_avoid_ambiguous_glyphs yes
set -g theme_nerd_fonts yes
set -g theme_show_exit_status yes
#set -g default_user your_normal_user
set -g default_user pantasio
############## end config.fish ##################
