### ISSUE TITLE
Why plugin install skipped?

### ISSUE THREAD

**Issue by anatoo** [fisherman/fisherman#161]
Hi guys,

I have a problem about installing plugin.
Fisherman display "1 plugins/s skipped(plugin name)" when I try to install plugin like the below.

```
$ fisher list
* debug
* spin
> vibrant

$ fisher install pure
1 plugin/s skipped (pure)
No plugins were installed.
```

Why plugin install skipped?

Fish shell and Fisherman's version:
```
$ fisher -v 
fisher version 1.3.1
$ fish -v
fish, version 2.2.0
```

Thanks.

**Comment by bucaran** [comment]
@anatoo That means that your fishfile got corrupted somehow. Fisherman thinks `pure` is already installed, hence it skipped _it_. 

```
$EDITOR $fisher_file
# remove `pure` and try again
```

If you still have problems you are welcome aboard [join.fisherman.sh](http://join.fisherman.sh).

**Comment by anatoo** [comment]
@bucaran Thanks for quick response.
I removed "pure" from $fisher_file and my problems are resolved!

**Comment by bucaran** [comment]
@anatoo Do you have any recollection of the steps you made that led to the file getting corrupted?

I'll confess I have experienced this a couple of times too, but I have never been able to repro the problem.

**Comment by anatoo** [comment]
@bucaran I uninstalled fisherman several times because fisherman seems to be broken when I installed some bad plugins. 
Probably I forgotten to remove "~/.config/fisherman" on uninstalling fisherman.

**Comment by bucaran** [comment]
Ok, I'll see if I can find something, thanks for reporting this.

By the way, which "bad" plugins?

**Comment by anatoo** [comment]
Sorry I forgotten which plugin. Some prompt plugin output many errors after the installation and just seems to be broken.

**Comment by bucaran** [comment]
Alright, perhaps it was one o the git_util plugins that were renamed recently.
