### ISSUE TITLE
Can't switch to theme vibrant anymore

### ISSUE THREAD

**Issue by Globegitter** [fisherman/fisherman#163]
I am not sure what happened, but first I switched around between a few themes, then I actually started using https://github.com/derhuerst/vibrant for a few days. Due to https://github.com/derhuerst/vibrant/issues/1 I switched theme and now I can not switch back to vibrant anymore or even uninstall it, it seems. I can switch to some other themes though.

`fisher i vibrant` and nothing happens.

```sh
fisher uninstall vibrant
▸ Uninstalling vibrant
1 plugin/s uninstalled in 0s

fisher search --tag=prompt
...
* vibrant                Pretty, minimal, git-centric prompt
...
```

Where-as the star seems to imply that it is still installed.

This is all using fish-shell 2.2.0, on elementary os 0.3.2 (which is based on ubuntu 14.04).

**Comment by Globegitter** [comment]
Removing vibrant from the cache and then installing it again seemed to do the trick though.

**Comment by bucaran** [comment]
@Globegitter I wish I had received a notification when you started having the problem. Perhaps the $fisher_prompt variable was set to `vibrant` incorrectly for some reason.

If you could repro this, I'd love to know.

**Comment by Globegitter** [comment]
Ahhh, good to know there is a `$fisher_prompt` env variable. I'll try to play around with that at some point again and see if I can reproduce it. Thanks for the quick response though.

**Comment by bucaran** [comment]
Yes, that is a universal variable we set to know the name of the prompt that is currently installed, so that when you install/switch to another prompt we know which one to disable.

**Comment by bucaran** [comment]
@Globegitter Please reopen if you get the same misbehavior again. :smile:
