### ISSUE TITLE
Which fish version is fisherman compatible?

### ISSUE THREAD

**Issue by fsquillace** [fisherman/fisherman#164]
Hi,

I have used the fish version 2.1.1 and during the manual installation I've got the following error:

    mkdir -p $HOME/.config/fish/ && touch $HOME/.config/fish/config.fish
    echo "set fisher_home /home/travis/build/fsquillace/pearl/mods/misc/fisherman/" | sed "s|/$||;s|$HOME|~|" > $HOME/.config/fish/config.fish.fisher
    echo "set fisher_config $HOME/.config/fisherman" | sed "s|$HOME|~|" >> $HOME/.config/fish/config.fish.fisher
    echo "source \$fisher_home/config.fish" >> $HOME/.config/fish/config.fish.fisher
    awk 'FNR==NR{ print; a[$0]; next } !($0 in a) || /^$/' $HOME/.config/fish/config.fish $HOME/.config/fish/config.fish.fisher > $HOME/.config/fish/config.fish.tmp
    mv $HOME/.config/fish/config.fish.tmp $HOME/.config/fish/config.fish && rm $HOME/.config/fish/config.fish.fisher
    mkdir -p $HOME/.config/fisherman/cache
    touch $HOME/.config/fisherman/fishfile
    ** Reload your shell and type 'fisher' to get started **
    set_color: Expected an argument
    ▸ Updating Fisherman
    Aye! Fisherman 1.3.1 updated (0s)
    0 plugin/s updated in 0s
    set_color: Expected an argument
    set_color: Expected an argument
    set_color: Expected an argument

Using the fish version 2.2.0 everything worked fine. You might want to specify the fish version in which fisherman appears compatible.

Thank you,
Filippo

PS: You did a really awesome work with Fisherman!

**Comment by bucaran** [comment]
@fsquillace That's not an error, that's make's output.

Fisherman is mostly compatible with 2.1.1, I haven't fully tested it in 2.1.1, but it should run basically.

```
set_color: Expected an argument
```

Seems like an error introduced in the latest update that introduced parallel updates and we are using `set_color` to colorize the spinner.

**Comment by jethrokuan** [comment]
iirc there is a check for fish version `2.1.2` and prompts you to upgrade to `2.2.0`.

https://github.com/fisherman/install/blob/master/install.fish#L106

@bucaran is probably right in that the recent changes made it less backward compatible

**Comment by bucaran** [comment]
> Which fish version is fisherman compatible?

Mostly compatible with 2.1.2 and perfectly compatible with 2.2.0

Closing as answered/resolved.
