### ISSUE TITLE
Is it possible to have an option to link plugins with symlinks instead of hardlinks?

### ISSUE THREAD

**Issue by rodonn** [fisherman/fisherman#165]
When I run `fisher install pure` (or any other plugin)

I get errors of the form
`ln: failed to create hard link 'MYHOME/.config/fisherman/functions/__format_time.fish' => 'MYHOME/.config/fisherman/cache/pure/__format_time.fish': Invalid cross-device link`

(one for each file that needs to get copied from the cache folder)

I think the problem may be due to the fact I'm running on a server with all the directories in an AFS system spread across multiple filesystems. This makes hardlinks break on my system.

Would it be possible to add an option to copy the files instead of hardlinking them?
(I checked that on my system copying the files to the location they would have been hardlinked makes things work).

**Comment by jethrokuan** [comment]
Soft-linking the cache directory to the working should work in theory, @bucaran any thoughts?

[This](https://github.com/fisherman/fisherman/blob/1493292cd28b7dc33aa3b22eaf4fe9aa4ee03910/functions/__fisher_plugin_enable.fish#L13-L17) seems to be the only area where `ln`'s options are involved.

**Comment by bucaran** [comment]
@rodonn We only create symbolic links when the path is already a symbolic link, which is the case of plugins which are installed from local files.

We could add an option `--link` or `--soft` to install to force creating a symlink from a plugin downloaded to $fisher_cache, but I wonder if this could potentially break anything.

**Comment by bucaran** [comment]
@rodonn Does adding a --link option to the install method fix the problem?

**Comment by rodonn** [comment]
Sorry for the delay in getting back to you.

I tested editing __fisher_plugin_link so that it creates softlinks.
``` function __fisher_plugin_link --argument options source target
                          debug "Link %s" $target
                          command ln -s $source $target
                      end
```

For the handful of plugins that I tried this worked without any errors on my system. I'm not sure if there are any other situations where this would break things.

I'd love a --link option. (Though as I've shown above it's a pretty simple manual fix using funced)

**Comment by jethrokuan** [comment]
In theory, I think soft links would work just as well as hard links, but you may run into surprises when users change their plugins drastically. Cases like these are rare, because the file name usually also corresponds to the function name.

That said, hard links should remain the default option. Perhaps instead of a --link option, we could use a variable like `$fisher_soft_links`, so you don't have to keep installing with `--link`.

**Comment by bucaran** [comment]
@rodonn If all your plugins are installed as symlinks, I wonder what the output for `fisher list` looks like. Would you mind posting a screenshot or copy paste the output?

Thanks.

**Comment by rodonn** [comment]
![image](https://cloud.githubusercontent.com/assets/2594443/14096013/5990f6dc-f51a-11e5-89bb-6b7bd61752f8.png)

**Comment by rodonn** [comment]
![image](https://cloud.githubusercontent.com/assets/2594443/14096048/968efcb4-f51a-11e5-946d-a129bf557486.png)

**Comment by rodonn** [comment]
Currently my editted __fisher_plugin_link looks like
```
function __fisher_plugin_link --argument options source target
        debug "Link %s" $target
    command ln -sf $source $target
end
```

**Comment by bucaran** [comment]
@rodonn Thanks, that looks alright to me.

So let me get this double clear again. The option would simply install plugins that are in cache into $fisher_config/{functions,completions,etc} as symlinks instead of copying the files. Correct?

**Comment by rodonn** [comment]
Yes. I think having the option to install plugins using symlinks would fix the problem I was having.

But if I am interpreting the code correctly, currently fisher does not "copy" the files, it makes hard links from the cache into the config folder.

**Comment by bucaran** [comment]
In 1.4.0 we will simply create symlinks always, as the internal cache will be used more like a stage to move plugins in and out the function path. tl;dr; you need neither `__fisher_plugin_link` or any `--link` option anymore as this will be the default behavior.

Closing and tracking this in #178.
