### ISSUE TITLE
Show changes when updating

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#168]
After reading https://medium.com/@robbyrussell/d-oh-my-zsh-af99ca54212c I think two simple additions could increase engagement. One is that when you update fisherman or a plugin, a short description of the changes  (commit messages/ what files have changed) could be shown (this issue). Second, fisherman could automatically update every other week to make sure that people stay up to date with the latest and greatest (#169).

**Comment by bucaran** [comment]
This could be a simple addition, but it depends on what and how we do it exactly. Like, just write the contents of `git log <options>` after the update. Or do you have something more elaborate in mind?

**Comment by domoritz** [comment]
Oh my zsh seems to show the file change stats from git (https://raw.githubusercontent.com/babun/babun.github.io/master/images/screenshots/screen_zsh_update.png). I think the commit messages are more useful. Or even better: when fisherman updates to a new version, show the release log from https://github.com/fisherman/fisherman/releases. 

Right now I don't even know whether updating actually installed a new version or not.

**Comment by bucaran** [comment]
@domoritz So we could print a message saying `Visit ...` with a link to the releases page. Or do you want to read the file in your terminal?

**Comment by domoritz** [comment]
> It shows you the new version number, that's all it does. Maybe it should not show anything if Fisherman is already the latest version?

But not even that for plugins. And yes, if the latest version is already installed it's odd to get a message. 

Just as a reference, this is the current output. 

```
$ fisher update
▸ Updating Fisherman
Aye! Fisherman 1.3.1 updated (3s)
Updating plugins...
▸ thefuck
▸ spin
▸ fasd
▸ python
▸ grc
▸ bobthefish
▸ shark
▸ vscode
▸ osx
▸ grc
▸ thefuck
▸ fasd
12 plugin/s updated in 6s
```

What I'm suggesting is this issue is a) only show the items that actually changed, b) show from what version to what version we updated, or c) show a little summary of the commit messages or the release log since the last update (can be long so I can see why this is not always great).

**Comment by bucaran** [comment]
Gotcha.

BTW plugins have **no versions**, but we could check whether there are any updates available and then update only if so.

So, hat kind of summary exactly? Since this is just text, can you write the desired output and post it here? That way we would be discussing something more concrete.

**Comment by domoritz** [comment]
> BTW plugins have no versions

But they have git hashes and dates when they were been updated.

**Comment by bucaran** [comment]
Yes, they certainly do. There is a lot of data and I am wondering, what would be the best way to display this data to the user. Can you take a stab at the ideal text output while / after you update plugins.

**Comment by domoritz** [comment]
```
$ fisher update
▸ Updating Fisherman
Aye! Fisherman updated from 1.3.1 to 1.4.0
▸ Updating plugins...
Updated thefuck spin fasd python
4 plugin/s updated (8 up to date)
```

```
$ fisher update
▸ Updating Fisherman
Aye! Fisherman updated from 1.3.1 to 1.4.0
Updating plugins...
▸ thefuck
4 new commits
▸ spin
1 new commit
▸ fasd
32 new commits
▸ python
2 new commits
4 plugin/s updated (8 up to date)
```

(it's odd that there is an arrow in front on different things (the message or the thing that has been updated)

```
$ fisher update
▸ Updating Fisherman
Aye! Fisherman updated from 1.3.1 to 1.4.0
▸ Updating plugins...
thefuck                                      5fb0dae -> 65b3f16        4 new commits
spin                                           5fb0dae -> 65b3f16        1 new commit
fasd                                           5fb0dae -> 65b3f16        32 new commits
python                                       5fb0dae -> 65b3f16        2 new commits

4 plugin/s updated (8 up to date)
```

And if fisherman is up to date

```
...
▸ Updating Fisherman
Aye! Fisherman is up to date.
...
```

If you also want to show the changes, it could look like this:

```
...
▸ Updating Fisherman
Aye! Fisherman updated from 1.3.1 to 1.4.0

Changes:
 * Better, faster [#123]
 * More usable [#312]
...
```

or just a link

```
...
▸ Updating Fisherman
Aye! Fisherman updated from 1.3.1 to 1.4.0 (see changes at https://github.com/fisherman/fisherman/releases/tag/1.3.1)
...
```

**Comment by bucaran** [comment]
I totally dig this :smile:

**Comment by bucaran** [comment]
@domoritz I think we have a wrapper c11ac1f.

**Comment by domoritz** [comment]
Cool!

```
▸ Aye! Fisherman is up to date
▸ Updating 4 plugin/s
  grc                       Up to date
  thefuck                   Up to date
  fasd                      Up to date
  grc                       Up to date
No plugins were updated.
```
