### ISSUE TITLE
Fix load order during installation

### ISSUE THREAD

**Issue by orangecms** [fisherman/fisherman#170]
When installing `ssh-agent`, one would get the following error:
```
fisher i ssh-agent
▸ Installing ssh-agent
fish: Unknown command '__test_ssh_identities'
~/.config/fisherman/conf.d/ssh-agent.init_ssh_agent.fish (line 2):     __test_ssh_identities
                                                                       ^
```

@bucaran figured out that the snippet is sourced before linking the actual function to the config.

**Comment by bucaran** [comment]
Thanks @orangecms.

This is affecting @herrbischoff ssh-agent too. I'll submit a patch shortly.
