### ISSUE TITLE
Do not show disabled plugins when using fisher list.

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#177]
Instead of modifying how uninstalling plugin works, we can simply ignore disabled plugins when using `fisher list`.

This way, `fisher uninstall` keeps a copy in the cache, but this is an implementation detail that does not concern most users.

The reason we need to keep the cache is so that we don't have to re-download a plugin if we already have it as well as making ~~theme~~ prompt switching possible.

**Comment by lordlycastle** [comment]
If you were re-installing by re-downloading, you'd might get an updated version... Maybe have an option to install from cache, in cases when not connected to internet. Also, I don't know about average size of packages, but they can't be that large so downloading them wouldn't be much of an effort.

**Comment by bucaran** [comment]
@lordlycastle 

> Maybe have an option to install from cache,

If you try to install a plugin that happens to be in the cache, it will be copied from there, that's by default. If you want to get the latest version, either update (the most logical thing to do) or remove it and reinstall.

>  I don't know about average size of packages

Usually small, but we always git clone --depth=1.

> it would be nice if the list was shown in multiple columns instead of just one.

This would be nice. I guess we could pipe `fisher_list`'s output to `column` for you, but I am not sure how one would go to get the output back into rows. Sounds like an intermediate level job for sed/awk.

**Comment by bucaran** [comment]
Closing as implemented.
