### ISSUE TITLE
Number appears when updating fisherman

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#179]
```
$ fisher u
4 ⠴
▸ Aye! Fisherman updated from 1.3.1 to 1.4.0 (2s)
▸ Updating 11 plugin/s
  python                    Up to date
  fasd                      Up to date
  spin                      Up to date
  thefuck                   Up to date
  vscode                    Up to date
  grc                       Up to date
  fasd                      Up to date
  grc                       Up to date
  osx                       Up to date
  shark                     Up to date
  bobthefish                2 new commit/s
1 plugin/s updated in 5s
```

Not sure why there is a `4`. I saw something similar earlier today but I don't know how to reproduce. I'll keep looking.

**Comment by bucaran** [comment]
@domoritz I couldn't repro here, but let's keep this open for a while.

**Comment by jethrokuan** [comment]
also, noticed grc printed twice, but can't repro either.

**Comment by bucaran** [comment]
@jethrokuan Are you using `grg`?

**Comment by domoritz** [comment]
> also, noticed grc printed twice, but can't repro either.

yeah, that's my fishfile. It's got `https://github.com/oh-my-fish/plugin-grc` and `grc`. I fixed it.

**Comment by bucaran** [comment]
@domoritz Is this behavior still happening?

**Comment by domoritz** [comment]
Not recently. But fisherman hasn't been updated since then. I'm closing for now and will post if I see something again.

**Comment by bucaran** [comment]
Thanks.

**Comment by domoritz** [comment]
It happened again

```
$ fisher u
1 ⠦
Aye! Fisherman is up to date
Updating 10 plugin/s
    grc                       Up to date
    thefuck                   Up to date
    fasd                      Up to date
    osx                       Up to date
    python                    Up to date
    spin                      Up to date
    brew                      Up to date
    vscode                    Up to date
    shark                     Up to date
    bobthefish                Up to date
No plugins were updated
```

I'm sure there is some race condition.

**Comment by bucaran** [comment]
The problem must be in how we check for the last job id. The current implementation is rather naive and does not account for jobs that contain new lines. When a job contains new lines they make parsing the id from `jobs` output harder than I thought when I first wrote the parallel update procedure.

I haven't seen this even once, but I'll fix this as soon as I can show everyone the results of a little experiment I am currently working on.

**Comment by domoritz** [comment]
It's still happening and other people seem to see it as well (e.g. #200).

**Comment by bucaran** [comment]
Essentially the update mechanism in fisherman should be modified entirely and taken from `fin`, where the race conditions  were fixed already. This will likely break the test suite, so it's not a trivial change.

If you want to make all the problems go away right now, I suggest you simply move on to fin, else, I'll need a few days before I can look at this or if someone wants to take a stab at it, I'd be happy to merge their PR.

**Comment by bucaran** [comment]
c390b0b
