### ISSUE TITLE
arch linux unable to install fisherman

### ISSUE THREAD

**Issue by edclement** [fisherman/fisherman#180]
Below is what I get. It looks like the `$fisher_home` isn't getting populated maybe based on the `Make sure you can write to` message? Any ideas?

![image](https://cloud.githubusercontent.com/assets/5667395/14163076/bb699bec-f6bf-11e5-9118-bd6e7de527d8.png)

**Comment by edclement** [comment]
managed to resolve this by:
```
rm -rf ~/.local/share/fisherman
curl -sL get.fisherman.sh | fish
curl -sL get.fisherman.sh | fish
```

It seems as though once the `~/.local/share/fisherman` directory was present it was able to install properly.

**Comment by jethrokuan** [comment]
I'm not sure what has changed since, but the one-liner installer still worked for my arch linux installation just a few days ago.

**Comment by bucaran** [comment]
Thanks for reporting this @edclement. Please try again, I am sure this is fixed by now.

**Comment by bucaran** [comment]
@edclement Problem was a bug in the installer with the CLI deps which by the way just went away now that we are supporting the progress spin directly.

Closing as resolved.
