### ISSUE TITLE
Fisherman will not install on CentOS 7

### ISSUE THREAD

**Issue by Silvery-Corgan** [fisherman/fisherman#181]
Hello. I am having trouble installing fisherman under CentOS 7 X64.

My OS details are as follows:

```
user@host ~> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

I am getting the below when trying to install fisherman:

```
user@host ~> curl -sL get.fisherman.sh | fish
 ✓ Downloading Fisherman to ~/.local/share/fisherman
 ✓ Creating the configuration in ~/.config/fisherman
 ✓ Updating the registry index
 × Installing CLI utilities

Sorry, but I couldn't install Fisherman. Some things you can try:

 → Upgrade your Git version (^2.0)
 → Upgrade your Fish version (^2.2.0)
 → Make sure you can write to /home/user/.local/share/fisherman
 → Make sure you are connected to the Internet

For more help visit http://issues.fisherman.sh
user@host ~> fish --version
fish, version 2.2.0
user@host ~> git --version
git version 1.8.3.1
```

I am certain this is because of the git version. This is the available version in CentOS 7.
I have also tried to compile git from source. By default it puts git into /usr/local/bin and when I run

```
user@host ~> git --version
git version 2.8.0
```

It shows up as git 2.8.0

but then I get the below:

```
user@host ~/git-2.8.0> curl -sL get.fisherman.sh | fish

 × Downloading Fisherman to ~/.local/share/fisherman

Sorry, but I couldn't install Fisherman. Some things you can try:

 → Upgrade your Git version (^2.0)
 → Upgrade your Fish version (^2.2.0)
 → Make sure you can write to /home/user/.local/share/fisherman
 → Make sure you are connected to the Internet

For more help visit http://issues.fisherman.sh
user@host ~/git-2.8.0>
```

I remain puzzled as to why it won't execute after I upgrade git. I've also rebooted the machine and the same thing happens. Git shows version 2.8.0

I am able to write to the mentioned directories. By the way I have SELinux enabled and I need it enabled. There is no special config for SELinux on my machine. Just the default one.

**Comment by bucaran** [comment]
@Silvery-Corgan How difficult would it be for you to provide something like a Vagrant file that I could use to run your CentOS in a test box?

Also, could you post your `make` version too?

Now, you can always try the manual installation method.

https://github.com/fisherman/fisherman/wiki/Installing-Fisherman#manual-install

@jethrokuan You have more experience with Linux, any thoughts?

**Comment by jethrokuan** [comment]
If you're running the curl installer a second time, it fails if the files are already there in `/home/user/.local/share/fisherman`. Just `cd` into the folder and run `make`.

**Comment by Silvery-Corgan** [comment]
@bucaran I am not familiar with Vagrant.

My make version is GNU Make 3.82

The manual install did the trick.

@jethrokuan Thanks man. That did the trick. The files were already there.

**Comment by bucaran** [comment]
Yay! :smile:

**Comment by jethrokuan** [comment]
@bucaran perhaps the lesson learnt is that we should remove the folder if installation fails at any point.

**Comment by bucaran** [comment]
Yes, that makes sense. I think we should put that on hold until we have figure out the new installer pioneered by @orangecms.

After that, I'll write a new curl installer, because some folks will just prefer to use that.

**Comment by Silvery-Corgan** [comment]
@jethrokuan @bucaran If you guys still need more info from me to fix this I am happy to provide it. Just let me know.

As a side-note you might want to make the curl installer check for git versions and use the latest one. I had both git 1.8.3.1 and 2.8.0 installed but the installer didn't see my git install located at `/usr/local/bin` for some reason even after I removed the official git package with `rpm -e --nodeps git`. Again I've rebooted the machine to make sure everything goes smooth. Location is in $PATH so after running `git --version` I got 2.8.0 but the installer still failed. And yes, I did remove the folders created by the previous failed install.

Anyway, like I said, @jethrokuan's post made the trick.

Cheers.

**Comment by bucaran** [comment]
Thanks @Silvery-Corgan, I'll ping you again when dev of the new installer starts. The important issues to be looking at are #173 and #174.

**Comment by bucaran** [comment]
@Sorin-Oprea With fisherman >2.0, a lot has changed, so I presume this is no longer a problem. Can you check again :)

**Comment by Silvery-Corgan** [comment]
@brj Sorry for the long delay. I can confirm that the installation works fine now. Things have changed quite a lot in the newer version and plugins have been renamed. Overall I like the fact that the framework looks a lot slimmer now.

**Comment by brj** [comment]
That's great news. Thanks @Silvery-Corgan!
