### ISSUE TITLE
Installing OMF plugins does not work

### ISSUE THREAD

**Issue by ypnos** [fisherman/fisherman#185]
Whenever I try to install a OMF plugin I get the same error message.

Example:

```
# fisher install omf/plugin_peco
Installing plugin/s
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/oh-my-fish/plugin_peco/'
No plugins were installed
```

**Comment by jethrokuan** [comment]
`https://github.com/oh-my-fish/plugin_peco/` the plugin does not exist at this repo.

The correct command would be: `fisher install omf/plugin-peco`.

Although granted, the error is confusing. we'll keep this issue open for further discussion.

**Comment by ypnos** [comment]
OK I see. Are OMF dependencies handled? I installed `plugin-weather` which got many errors because `plugin-config` was missing. Alas https://github.com/oh-my-fish/plugin-weather/blob/master/bundle

**Comment by jethrokuan** [comment]
At the moment, they are not.

@bucaran is this on the roadmap?

**Comment by bucaran** [comment]
@jethrokuan @ypnos OMF bundles **are** handled, problem here is `plugin-config` is a package designed to work exclusively with OMF variables, essentially a clever way to guarantee incompatibility with other systems.

@ypnos TBH, the weather package is not that impressive considering you can:

```
curl wttr.in/tokyo
```

<img width="1280" alt="screen shot 2016-04-04 at 10 25 04 pm" src="https://cloud.githubusercontent.com/assets/8317250/14249263/ef6b745e-fab3-11e5-9a25-719ef81592ae.png">

**Comment by bucaran** [comment]
Closing as the `config` package can't be supported.
