### ISSUE TITLE
fish: An error occurred while redirecting file '/Users/koofrank/.rbenv/version'

### ISSUE THREAD

**Issue by phpmaple** [fisherman/fisherman#186]
when I use fisher install plugins, then show:
fish: An error occurred while redirecting file '/Users/koofrank/.rbenv/version'
open: No such file or directory

and I use fisher any command line doesn't work, so I how to uninstall fisher and fix this problem, I use fisher uninstall not work

**Comment by bucaran** [comment]
@phpmaple Thanks, I don't use rbenv so I have never had this problem before, but @daenney, can you share some of your rbenv wisdom with us here?

**Comment by daenney** [comment]
@phpmaple How do you do the rbenv stuff? With the normal `rbenv` integration or using the fisherman rbenv plugin?

**Comment by phpmaple** [comment]
@daenney When I use fisher install some plugins, Then show this error, and then fisher doesn't work

**Comment by jethrokuan** [comment]
@phpmaple I think the folder is created when `rbenv` the utility, not the fisherman plugin, is installed, so if you don't have it installed, then an error will be thrown. In any case, the issue is not fisherman-specific.

**Comment by phpmaple** [comment]
@jethrokuan I uninstall  `rbenv`, then everything is ok

**Comment by jethrokuan** [comment]
@phpmaple do you confirm that you have https://github.com/rbenv/rbenv installed?

**Comment by phpmaple** [comment]
@jethrokuan  I sure

**Comment by bucaran** [comment]
@phpmaple Thanks! Close if your problem is resolved.

**Comment by rnorth** [comment]
It looks like the bobthefish theme is expecting to find the global ruby version in `~/.rbenv/version` but it's not there. I had this same problem too (coming from having regular rbenv+fish to fish+fisherman with the rbenv plugin). The relevant lines of `fish_prompt.fish` are:

       # Don't show global ruby version...
      set -q RBENV_ROOT
        or set -l RBENV_ROOT $HOME/.rbenv

      read -l global_ruby_version <$RBENV_ROOT/version

However, I did not have the `version` file in my `~/.rbenv` folder

For me, the following resolved the issue, though I'm not sure if it's a proper solution:

    rbenv version-name > ~/.rbenv/version

**Comment by bucaran** [comment]
@rnorth I have forked, bobthefish [here](https://github.com/fisherman/bobthefish), I don't use it myself, but since it's quite popular I've put it there hoping to fix some of its bugs in the future. If you want to PR me there with that go ahead.

**Comment by corysimmons** [comment]
Everyone still having problems:

Replace

```fish
# Don't show global ruby version...
set -q RBENV_ROOT
  or set -l RBENV_ROOT $HOME/.rbenv

read -l global_ruby_version <$RBENV_ROOT/version
```

with

```fish
set global_ruby_version (rbenv global)
```

Per https://github.com/rnorth/bobthefish/commit/ba3b165371ff90ef916ac008a25f60f62f56c84a

**Comment by michaeltarleton** [comment]
The above bgbthefish fix is a package specific fix but to fix your whole RBENV system see the following:

So it looks like after you install RBENV there is no ~/.rbenv/version file. To create it just run `rbenv global system` . Then that file will be created and everything will work.

To change the version from system just run something like `rbenv global 2.4.1` (of course after you've installed version 2.4.1 using `rbenv install 2.4.1`).
