### ISSUE TITLE
Broken index URL in index update function

### ISSUE THREAD

**Issue by jmo-learnosity** [fisherman/fisherman#187]
At https://github.com/fisherman/fisherman/blob/master/functions/__fisher_index_update.fish#L20, the URL given seems to be incorrect. It should actually be `https://github.com/fisherman/index/blob/master/index`. With its current value, it breaks searching for and installing plugins.

**Comment by artemruts** [comment]
Confirmed with `v.1.4.0`.

**Comment by bucaran** [comment]
@jmo-learnosity @artemruts Corrected and fixed cf19aed. Thanks for reporting it.
