### ISSUE TITLE
Install fails on FreeBSD

### ISSUE THREAD

**Issue by ekollof** [fisherman/fisherman#194]
```
   Downloading Fisherman to /usr~/.local/share/fisherman
   Creating the configuration in /usr~/.config/fisherman
 ? Updating the registry index

Sorry, but I couldn't install Fisherman. Some things you can try:

  Upgrade your Git version (^2.0)
  Upgrade your Fish version (^2.2.0)
  Make sure you can write to
  Make sure you are connected to the Internet

For more help visit http://issues.fisherman.sh
ekollof@nergal ~> git --version
git version 2.7.4
ekollof@nergal ~> fish --version
fish, version 2.2.0
ekollof@nergal ~> uname -r
10.3-RELEASE
```

**Comment by bucaran** [comment]
@ekollof Problem is you may not have `make` installed. Can you install `make` easily?

**Comment by ekollof** [comment]
```
ekollof@nergal ~> gmake --version
GNU Make 4.1
Built for amd64-portbld-freebsd10.1
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
ekollof@nergal ~> make
make: no target to make.

make: stopped in /usr/home/ekollof
```

**Comment by bucaran** [comment]
It seems you do have make, in that case can you try:

```
set -l fisher_home ~/.local/share/fisherman
mkdir -p "$fisher_home"
git clone https://github.com/fisherman/fisherman "$fisher_home"
cd "$fisher_home"
make
```

If that works fine, update things and get the `spin` plugin for cli progress interaction.

```
fisher update
fisher i spin
```

**Comment by ekollof** [comment]
I suspect some variable expansion is not working so well. After above procedure:
```

ekollof@nergal ~/.l/s/fisherman> cat ~/.config/fish/config.fish
set fisher_home /usr~/.local/share/fisherman
set fisher_config ~/.config/fisherman
source $fisher_home/config.fish
```

**Comment by bucaran** [comment]
We need to improve the installer for sure, so were you able to install fisherman okay?

**Comment by ekollof** [comment]
It sorta works now. I manually edited the fish config. I'll mess around a bit to see if I can get stuff to work

**Comment by bucaran** [comment]
@ekollof You are also welcome to try out [fin](https://github.com/fishery/fin), a more lightweight version of fisherman with a different approach. I think it may suit you better. Feature wise is essentially the same.

**Comment by mekanix** [comment]
GNU Make on FreeBSD is gmake, while BSD make is make. Maybe that's the problem? I have access to a FreeBSD box so I'll let you know I debug this a bit more

**Comment by bucaran** [comment]
I think this is not the problem. We had the exact same issue before and already fixed it by checking for the version and using either gmake or make.

What we really want to do is replace using make completely and rewrite that into a `bin/install` script in this repo.

@jethrokuan Do you have any comments?

**Comment by jethrokuan** [comment]
Can't really infer here, but I think @mekanix is right about the variable expansion part.

Instead of using `~` in the installer, maybe using `$HOME` helps?

**Comment by bucaran** [comment]
@jethrokuan AFIK ~ expands to the real home path, whereas HOME is just a regular variable you can even set and the shell does not protect you from it:

```
set HOME / # boom
```

**Comment by bucaran** [comment]
Closing as partially or completely resolved.

@ekollof [You are also welcome to try out fin](https://github.com/fishery/fin), a lightweight version of fisherman with a simpler design. I think it could suit your use case better.
