### ISSUE TITLE
Roadmap for 1.5.0

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#196]
+ [ ] Ditch make for a `scripts/make.fish` or `bin/install` file in pure fish that does what our `make` is presently doing and possibly also what `github/fisherman/install` does and remove that repository **or** keep that repo and make it work with `bin/install`, but either way make must go because we've had our share of users that don't have make.

**Comment by jethrokuan** [comment]
Will fin's fix for parallel updates/installs ported over here in 1.5.0? Or is the code base for installation and updating too big here?

**Comment by jethrokuan** [comment]
note that this will break the current attempt by @orangecms to make a AUR package.

**Comment by bucaran** [comment]
> Will fin's fix for parallel updates/installs ported over here in 1.5.0? Or is the code base for installation and updating too big here?

Yeah, let's discuss that. Updating the parallel update/install code seems like a thing worth doing. I don't think a lot of test rewiring would be needed, if at all, since fisherman's test are rather forgiving on that area.

> note that this will break the current attempt by @orangecms to make an AUR package.

Why?. The plan is to provide both a manual and curl|fish install, but not rely on make anymore.

**Comment by jethrokuan** [comment]
The current AUR package uses `make` under the hood.

**Comment by bucaran** [comment]
Yeah, I just want to have a more robust install procedure for fisherman in the future that's all.

**Comment by bucaran** [comment]
@jethrokuan Do you have any other ideas for 1.5.0, I am trying to keep the list realistic, hence only one item on the list, but I think we could squeeze one or two things in there. I can work on this next week.

**Comment by jethrokuan** [comment]
Given that all the complaints here are wrt to installations failing on certain distros, I think 1.5.0 should be the milestone that cleans all that up.

Also, perhaps it's time to relook at what's core in Fisherman, or what could be better implemented, and start to modularize.

**Comment by bucaran** [comment]
1275b68e52cfe06937bb7b0c458b6c3e0b916c62
