### ISSUE TITLE
Update fisherman itself

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#200]
How do I update fisherman to the latest version. I have 1.4.0 and I see that there is a new release. But if I do `fisher update`, it updates only plugins ("update everything" in the docs is a bit confusing). If I try to run `curl -sL get.fisherman.sh | fish`, it tells me, 

> ✘ fisherman is already installed. To reinstall: ....

So do I have to _reinstall_ fisherman every time when there's a new release?

**Comment by bucaran** [comment]
@laughedelic `fisher update` does update everything, that is plugins _and_ fisherman itself. If that's not working for you, can you post the log of the error?

**Comment by laughedelic** [comment]
Thanks for the fix! Now it worked as expected:

```
> fisher update
1 ⠸
Aye! Fisherman updated from 1.4.0 to 1.5.0 (4s)
```

Btw, spin leaves these dots after it finishes sometimes..

**Comment by bucaran** [comment]
@laughedelic And there's also that number. This must be a bug in spin. I need to dig into this.

BTW are you familiar with fin already?

**Comment by laughedelic** [comment]
> there's also that number

It's because one plugin also got updated (getopts). Or is that number supposed to disappear too?

> are you familiar with fin already?

Not really. I'm new to fish and fisherman and I'm a bit confused about relationships between things here. I thought that fin and fisherman are competitors, but then I saw fin in the fishery...

> 200th issue 🎈

🎉 😆

**Comment by bucaran** [comment]
They are competitors in a friendly way, they learn from each other, fin learn mostly from fisherman. They are all part of the "fisherman ecosystem". So, what was previously known as the fishery is know fisherman too. In other words, fisherman is now both the name of the plugin manager in this repo and an umbrella term to refer to the ecosystem.

Since the beginning people were already saying "fisherman plugins" anyway.

**Comment by domoritz** [comment]
> And there's also that number. This must be a bug in spin. I need to dig into this.
Looks like https://github.com/fisherman/fisherman/issues/179

**Comment by bucaran** [comment]
@domoritz Have you seen fin already? https://github.com/fisherman/fin

**Comment by domoritz** [comment]
Yeah, just saw it today. I'm trying to understand what the `fisherman - fin` is (assuming that fisherman offers something fin doesn't).

**Comment by domoritz** [comment]
I guess https://github.com/fisherman/fin#15-why-did-you-create-a-new-project-instead-of-improving-fisherman explains part of my question.

**Comment by bucaran** [comment]
Well, fisherman has search and can install things by name by looking at the index. fin is supposed to be more "agnostic" and try not to depend on an index. Also, since fisherman has an index, it can create completions with plugin descriptions. If that's not essential to you, try out fin.

**Comment by domoritz** [comment]
I usually just search on github or browse some web page that lists plugins.

**Comment by bucaran** [comment]
Yeah, me too, or use [fisherman.sh#search](http://fisherman.sh#search).

**Comment by tasmo** [comment]
Is that just a guess? I miss the search command much. R.I.P. fin. :/

**Comment by bucaran** [comment]
@tasmo There is no builtin search command, but the index is still available. It's just a matter of creating a plugin to search it. I might just do that after I am done with some other stuff first in the TODO.

I am working on a bunch of small plugins and a little surprise for everything.

The old search code is still available if you look in the git history. Perhaps extract that into a plugin and add it to the organization?

I can send you an invite if you're interested.

> Is that just a guess? 

Kind of. Also feedback from several users. No hard data though.
