### ISSUE TITLE
fisher u unexpected behavior

### ISSUE THREAD

**Issue by orangecms** [fisherman/fisherman#201]
In the menu, fisherman says that `fisher u` would update the plugins. However, it also attempts to run git commands in the fisher home directory, which fail in case of a global installation in the system, which causes nothing to be updated. The command `fisher u` should not try to tamper with system integrity. It should also make sure to have access to where it tries to write files.

**Comment by bucaran** [comment]
Yes, that's the current behavior. I am completely open to modifying this behavior entirely as well as dropping the current install procedure, but before we can do that we need packages for OSX, via brew, and Linux.

**Comment by orangecms** [comment]
That is the responsibility of the distros and repos. If people want it, they will create a package. All we need to do is to provide a usual build procedure (Makefile, like in my PR; I should eventually also work on the CI tests). This bug was just reported in AUR, so I put it here for trackability. See https://aur.archlinux.org/packages/fisherman-git/#news

**Comment by bucaran** [comment]
> All we need to do is to provide a usual build procedure (Makefile, like in my PR; I should eventually also work on the CI tests).

Go for it.

**Comment by bucaran** [comment]
@orangecms With 2.0 a lot has changed, for once, fisherman will not self-update anymore if it detects a non-standard setup. Is this issue still relevant?

**Comment by orangecms** [comment]
Nope, I've closed it.
