### ISSUE TITLE
Where should plugins put data?

### ISSUE THREAD

**Issue by igalic** [fisherman/fisherman#202]
I'm trying to create a plugin that uses Unicode data. It provides offline access to all your unicode (and emoji) copy-pasting needs, but i'm struggling where to put the actual data.

Any guidelines for this?

**Comment by bucaran** [comment]
@igalic This is not specific to fisherman or [fin](https://github.com/fisherman/fin) plugins, but any application.

The correct place to put your program's configuration is in XDG_CONFIG_HOME, by default ~/.config/your_program.

If your program uses a cache, then that should go into XDG_CACHE_HOME, by default ~/.cache/your_program.


Related: [XDG Base Directory support](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support)

**Comment by bucaran** [comment]
@igalic Feel ready to close?
