### ISSUE TITLE
Quiet update is not quiet. 

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#203]
At least it prints things (and also shows a spinner), which I believe it shouldn't. 

```
$ fisher u -q
    grc                       Up to date
    thefuck                   Up to date
    python                    Up to date
    bobthefish                Up to date
    spin                      Up to date
    vscode                    Up to date
    shark                     Up to date
    bobthefish                Up to date
    brew                      Up to date
    osx                       Up to date
    fasd                      Up to date
    spin                      Up to date
```

**Comment by bucaran** [comment]
We should be redirecting the output to `__fisher_stderr`, but it seems we are not. Fortunately, this bug is not a race condition and it shouldn't be too hard to fix.

**Comment by bucaran** [comment]
Relevant: c390b0b

I think this is still not working exactly as you'd like to. Can you check again?

Please see the README for instructions on how to upgrade to 2.0.

**Comment by dalln1** [comment]
Still not quiet with:
```
fisherman version 2.0.0-beta ~/.config/fish/functions/fisher.fish
```

**Comment by bucaran** [comment]
That will be the first thing I'll fix then 😄

**Comment by pickfire** [comment]
@bucaran, maybe we should implement a silent update which is totally quiet so no sound is produced.

**Comment by bucaran** [comment]
@pickfire No output. Absolutely and no worries, I'll push this very soon. --quiet should make fisherman be completely silent as you would expect.

**Comment by bucaran** [comment]
fa1ef92
