### ISSUE TITLE
Return to self-destruct

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#211]
I really like the idea of `fin self-destruct`, it server more meaning compared to `fisher self-uninstall`, @bucaran is there any chance to change it to `fisher self-destruct`?

**Comment by bucaran** [comment]
It was `self-destroy` in fin. In fisherman I changed it to `self-uninstall`. It's exactly the same code and I don't see any point of changing that now.

@jethrokuan ?

**Comment by jethrokuan** [comment]
@bucaran not exactly something I do often, but self-uninstall seems to relate to how the code is written: `self-update` for example.

I'm unopinionated as to what it's called.

**Comment by bucaran** [comment]
self-destroy was a "cool" term, but I feel "self-uninstall" is a bit more serious, without losing the general vibe.

Closing as wontfix. Sorry @pickfire :)

**Comment by pickfire** [comment]
No problem!
