### ISSUE TITLE
website improvements

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#212]
@fisherman/all 

Now that fin has ended and we are back to fisherman, it would be nice to have another look at the website and remove some of the cruft / redesign some of it. Perhaps even make it only a plugin search UI :)

Because so much have changed, I have drastically reduced the current [website](http://fisherman.sh/) to just the original search functionality and removed the feature / footer sections and titles / sub titles. It looks weird now, but the search is untouched.

**Comment by sijad** [comment]
* how about show install instruction before plugins search?
* maybe smaller search results?

**Comment by bucaran** [comment]
Yeah, why not.

**Comment by sijad** [comment]
maybe showing two result in a row? that can be possible I guess

**Comment by bucaran** [comment]
I am not against of anything really. The website is just a means for users to search content, so it should make it simpler or more obvious. Maybe we can even remove the fisherman logo from the center and make it just a little footprint on the top / bottom and something more like: gulpjs.com/plugins/

**Comment by sijad** [comment]
nice idea, how about a separated page and link for plugins just like *gulpjs* and a simple front page with logo and install instruction?

**Comment by sijad** [comment]
IMO install instruction is a little more important that plugins, it's confusing when they don't know how can they install fisherman
also it can be a good idea to add a little button for each search result to show install instruction for each plugin, it can show a modal with a little text input to tell user copy and paste that code in terminal for install the plugin

**Comment by bucaran** [comment]
> nice idea, how about a separated page and link for plugins just like gulpjs and a simple front page with logo and install instruction?

Could work. Yes!

> IMO install instruction is a little more important that plugins, it's confusing when they don't know how can they install fisherman
also it can be a good idea to add a little button for each search result to show install instruction for each plugin, it can show a modal with a little text input to tell user copy and paste that code in terminal for install the plugin

> edit: modal some times can be annoying, it can be also a button to copy that text to user clipboard

This is okay too, but then isn't that too much work? The idea is to ship something useful and fast.

**Comment by sijad** [comment]
yes but user should know how to install that plugins, maybe a little note before search text box or something?

**Comment by jethrokuan** [comment]
re: copy to clipboard, should be easy: https://clipboardjs.com/

**Comment by jethrokuan** [comment]
Plugin search can be revamped:

I'm thinking if it's a separate page we could do really interesting stuff:

It could work like google fonts, where they can choose plugins to install by clicking `use` or something and it forms up the command in the end, which could be easily copied to the clipboard.

**Comment by bucaran** [comment]
> yes but user should know how to install that plugins, maybe a little note before search text box or something?

Yeah, that too, instructions are simple to infer though:

If plugin is in fisherman org:

```
fisher PLUGIN_NAME
```

else

```
fisher USER_NAME/PLUGIN_NAME
```

**Comment by sijad** [comment]
I still thing it can help user to see install instruction for each plugin, I like @jethrokuan idea a lot, user can select multiple plugin and install them by one command, that's very interesting

**Comment by bucaran** [comment]
> I still thing it can help user to see install instruction for each plugin,

Yeah, sure, why not.

**Comment by herrbischoff** [comment]
You are sick for a couple of days and suddenly everything is different! :D Just wanted to say that I'm still on board with taking point on building the (now Fisherman instead of fin) site.

First meta input for the site: as it is all too often forgotten, we need to keep the focus on what a *visitor* would expect, not what *we* would like to implement. A site is for visitors after all. Therefore, I suggest skipping all kinds of "fancy" functionality like

> It could work like google fonts, where they can choose plugins to install by clicking use or something and it forms up the command in the end, which could be easily copied to the clipboard.

Reasoning: first-time users need plugin descriptions, which would be hard to do while keeping the list compact on without fuss. First-time users shouldn't install dozens of them at once anyway and current users already have their bundle file.

**Comment by bucaran** [comment]
@herrbischoff Should I create a new design or can you work with the existing theme? Maybe we should just start from scratch, my original html/css was pretty crappy.

**Comment by herrbischoff** [comment]
I like the clean look of the current website. If you have something that's just itching you to be changed, let me know. Otherwise I'll be taking the current source and clean it up. It needs to be converted to `pug` (formerly Jade) anyway. ;)

**Comment by bucaran** [comment]
@herrbischoff Have you seen the latest modifications I made? I removed almost everything, leaving only the search. If we are going to go the only search route, then we should redesign it.

**Comment by herrbischoff** [comment]
@bucaran: Alright, then give me something to go on folks. ;) Redesign means what exactly? Examples of websites you like, even just parts of it, would be helpful.

**Comment by bucaran** [comment]
Okay, do you think we need a fisherman landing page with the search builtin, or have both separate?

**Comment by herrbischoff** [comment]
I like search but it would be cool to have something like the gulp-page where all plugins are listed in an endless scroll but you can filter down by entering something in the search window. I believe someone wrote that earlier but I'm too lazy to look. ;)

So, I'm thinking extremely simple landing page with the one-line install instructions and a list of plugins on a separate page.

**Comment by bucaran** [comment]
@herrbischoff 
> So, I'm thinking extremely simple landing page with the one-line install instructions and a list of plugins on a separate page.

Yes, we don't need an entire new theme for that, we already have the logo and the colors and overall look of the current page should not change that dramatically.

And yes, an infinite scroll sounds better than the current search bar (which was my bad idea btw not @jethrokuan's ;))

**Comment by herrbischoff** [comment]
@bucaran: For reference, like that: http://gulpjs.com

**Comment by herrbischoff** [comment]
> Yes, we don't need an entire new theme for that, we already have the logo and the colors and overall look of the current page should not change that dramatically.

Good to hear. I can concoct some cross between gulp and the current Fisherman page without completely ripping off the look of the first.

**Comment by jethrokuan** [comment]
Given that the website is going to be a lot simpler, I hardly see the need for a templating library now, let alone a site generator like jekyll. It'd be a lot easier to work on plain static html and css.

**Comment by herrbischoff** [comment]
@jethrokuan: Plain HTML may do (but why, when pug is so much nicer and will be compiled to HTML anyway) but writing plain CSS in a responsive world with tons of browser-specific prefixes comes dangerously close to punishing yourself for no reason... ;)

**Comment by jethrokuan** [comment]
@herrbischoff because everyone would have to download a pug to html compiler in order to effectively contribute. I redid the css in sass for the same reason, and I realized the same.

**Comment by herrbischoff** [comment]
@jethrokuan: Well, I feel that providing a complete package (via gulp) should alleviate that. All you'd have to do is to do `npm install` and `gulp` and you'd be off to the races.

**Comment by jethrokuan** [comment]
I'm not particularly against that, but @bucaran had something to say back then.

**Comment by herrbischoff** [comment]
Alright, @bucaran, let's hear it! :D

**Comment by bucaran** [comment]
Yup, I did. My reasoning was, if you add a lot of cool stuff, then, who's going to be responsible for maintaining that? So, I was just looking after myself.

If @herrbischoff feels he is more productive in pug and the rest of the stack he is proposing, then go ahead.

@jethrokuan Sorry 😓

**Comment by herrbischoff** [comment]
For the record, I would be fine with plain HTML but I will not give up on my Stylus. :)

**Comment by bucaran** [comment]
@herrbischoff Pug is no problem.

You can write the front end in Elm if you like.

**Comment by jethrokuan** [comment]
@herrbischoff go ahead then (:

**Comment by herrbischoff** [comment]
@bucaran: Ahh, I remember the chat. Elm — gotta dive into that some time. Still, not search friendly at all, that stuff.

**Comment by herrbischoff** [comment]
@jethrokuan: I promise to keep the stack minimal. No need to tack on loads of junk. ;)

**Comment by jethrokuan** [comment]
feel free to rewrite the seach script with mithril/vue/whatever, it was quite poorly done.

**Comment by herrbischoff** [comment]
We will see. I was thinking vanilla JS and see how far we can get without adding framework overhead.

**Comment by herrbischoff** [comment]
@bucaran: Where should I put the development site?

**Comment by bucaran** [comment]
Yes, that's here:

https://github.com/fisherman/fisherman.github.io

**Comment by bucaran** [comment]
I just pushed the sticky footer, cleaned up a little bit the html and remove some of the css that we don't use anymore. It's still quite messy.

You could start on tidiying up everything, I am pretty sure my html still sucks and removing all the cruft as your rewrite the CSS with Stylus.

So, for starters let's just use Stylus and consider adding pug later. Why? Because HTML is quite simple and there is nothing fancy here.

The CSS on the other hand... :)

**Comment by herrbischoff** [comment]
Yeah, I've already started on the site. Using pug however. You'll see: it's a lot less clutter with it. Besides, I've really come to despise any kind of XML.

I'm in the middle of rewriting the main HTML code (which is *indeed* quite... creative) and cleaning up the CSS to be used in Stylus. I'm throwing away about 90% of the current work to build a far more simple and clean setup. Bootstrap may have been okay for a quick hack but the constant overwriting of default styles is tiresome — and extra overhead. I'm defining a micro responsive behavior, courtesy of Jeet and Rupture. I have found Bootstrap really only shines for quick and simple web applications, everything else inevitably leads to headaches. Plus, I'm going ahead with the separate plugin page, so the landing page can be very clean. That's also the reason I feel those GitHub buttons don't quite fit in.

If this seems to be to radical an approach, feel free to stop me. ;)

What I cannot seem to find is the "sticky footer" you mentioned. Is this the anchor image on the right?

**Comment by bucaran** [comment]
> I've really come to despise any kind of XML.

I hear you.

> What I cannot seem to find is the "sticky footer" you mentioned. Is this the anchor image on the right?

The sticky footer is just blue like the background of the page so you can't see it, but if you were to change the color it would stick to the bottom. A true 21st centruy accomplishment.

> If this seems to be to radical an approach, feel free to stop me. ;)

Go ahead. Do look at the website as it is right now as it does not really look bad.

**Comment by gretel** [comment]
no `xml` fine but how about `json`?

**Comment by bucaran** [comment]
@gretel How about entirely dropping the index and just querying the GitHub API?

@jethrokuan So long and thanks for all index? :)

**Comment by gretel** [comment]
@bucaran ah sure that does return `json` indeed doh 😝

**Comment by jethrokuan** [comment]
@bucaran sure, whatever works!

**Comment by bucaran** [comment]
@herrbischoff Do you have anything to show?

**Comment by bucaran** [comment]
@fisherman/all 
@jethrokuan 

I think the index has served us well, but it's time to move on and start to query the organization for plugins instead of depending on the index.

**Comment by jethrokuan** [comment]
this means that anything not in the fisherman org won't be displayed by default, right?

I thought the original idea was to have some indexable file in each plugin repo, and query github for that.

**Comment by bucaran** [comment]
Yeah.

> I thought the original idea was to have some indexable file in each plugin repo, and query github for that.
               
I thought about that one too, but if we make the org pure, then we don't have to worry about it.

**Comment by bucaran** [comment]
Ping @herrbischoff.

**Comment by bucaran** [comment]
Website is up and working, looks alright, search is useful, design is pretty. Sure, it could be improved, maybe we _will_ rewrite it in Elm someday or who knows what :)

I am going to close this for now, since I'd rather focus on improving the software and the person originally interested in revamping the site (@herrbischoff) vanished mysteriously anyway.
