### ISSUE TITLE
fisher broke my shell...

### ISSUE THREAD

**Issue by zacheryph** [fisherman/fisherman#213]
Broke install... again.  Shouldn't it be a goal to... keep something as someones shell/terminal/console in a working state.  I had this problem with oh-my-fish and thought fisherman was greener pastures.  I should just expect this with fish frameworks?

I did a fisher update, got a bunch of errors, opened-a-new terminal to not have a fisher command at all, and not have a theme.  I manually source the `~/.local/share/fisher/fisher.fish` file (yes which IS in the config.fish) in order to see the fisher command again. 

Ran `fisher update` again and seemed to have worked. I see `fisher` and theme opening a new terminal. Only now it cries about a non-standard setup detected when trying to update.  Exactly _what_ is non-standard now that has been perfectly fine for the last 6+ months, and was perfectly fine when i did `fisher update` 3 days ago. The update doesn't warn of these changes, doesn't explain the changes, doesn't aide in what the user needs to change, likes to say ARGH a lot.

I see nothing in the repo, or past issues that would raise awareness of "you are going to break everything".

```
> pwd
/Users/context/.local/share/fisherman
 > git show HEAD
commit ca735556eec3a816a851725110bbae6fa1a163ec
Merge: 57fdbd6 bd6b63f
Author: detailyang <detailyang@gmail.com>
Date:   Tue Apr 19 11:53:37 2016 +0800

    Merge pull request #199 from detailyang/thanks

    add new contributor to the THANKS.md

> fisher --version
fisher version 1.4.0
> fisher update
9 ⠧
cat: /Users/context/.local/share/fisherman/VERSION: No such file or directory
Aye! Fisherman updated from 1.4.0 to  (5s)
fish: Unknown command '__fisher_plugin_validate'
~/.local/share/fisherman/functions/fisher_update.fish (line 1): __fisher_plugin_validate $item
                                                                ^
in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/fisher_update.fish

in function 'fisher_update'
	called on line 1 of file -

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 51 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'update'

fisher: '' is not a valid plugin
fish: Unknown command '__fisher_plugin_validate'
~/.local/share/fisherman/functions/fisher_update.fish (line 1): __fisher_plugin_validate $item
                                                                ^
in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/fisher_update.fish

in function 'fisher_update'
	called on line 1 of file -

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 51 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'update'

fisher: '' is not a valid plugin
fish: Unknown command '__fisher_plugin_validate'
~/.local/share/fisherman/functions/fisher_update.fish (line 1): __fisher_plugin_validate $item
                                                                ^
in command substitution
	called on line 0 of file ~/.local/share/fisherman/functions/fisher_update.fish

in function 'fisher_update'
	called on line 1 of file -

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 51 of file ~/.local/share/fisherman/functions/fisher.fish

in function 'fisher'
	called on standard input
	with parameter list 'update'

fisher: '' is not a valid plugin
```

Opening a new terminal

```
context@zephyr ~> fisher update
fish: Unknown command 'fisher'
context@zephyr ~> source .local/share/fisherman/fisher.fish
context@zephyr ~> fisher update
WARN Non-standard setup detected.
INFO Updating 6 plugins
ARGH Fetching conf.d
ARGH Fetching cache
ARGH Fetching completions
ARGH Fetching man
ARGH Fetching functions
ARGH Fetching scripts
OKAY Done in 707ms
```

**Comment by bucaran** [comment]
@zacheryph 

Here is the relevant issue and history of how we went from 1.5 to 2.0: https://github.com/fisherman/fisherman/issues/204

The change from 1.5 to 2.0 was massive, so that should explain all the problems you were / are having.

To upgrade to 2.0 correctly you need to remove the old fisherman, and then follow the instructions on the README to install the new one.

If you don't want to do that and don't mind running a script I wrote for this, there's also:

```
curl -L git.io/fisher-up-me | fish
```

**Comment by bucaran** [comment]
@zacheryph Let me know if the above instructions don't work or you still other help troubleshooting the upgrade.

**Comment by zacheryph** [comment]
Yes this got this working.  Just a little frustrating to constantly have this happen. ;)  It might be helpful to others to make a note of the breaking change in the README. there is an install section but no upgrade/upgrading one.

**Comment by bucaran** [comment]
@zacheryph The 1.5 -> 2.0 upgrade was too reckless, but after working so much on this thing, I am quite confident it was for the best. Please keep me posted if you encounter any further problems.

> It might be helpful to others to make a note of the breaking change in the README. there is an install section but no upgrade/upgrading one.

A (temporary) note on how to upgrade from 1.5 deserves some mention indeed. I'll get around that in a bit.
