### ISSUE TITLE
fish: Unknown command '__fisher_complete'

### ISSUE THREAD

**Issue by oskarrough** [fisherman/fisherman#216]
Hi, somehow I messed up my previously well-working fish/fisherman setup on OS X. When I run `fisher update` I get

```
fish: Unknown command '__fisher_complete'
~/.config/fish/functions/debug.fish (line 3): debug -h | __fisher_complete debug
```

My `debug.fish` looks like this:

```
set -l IFS \t

debug -h | __fisher_complete debug
```

Any ideas? If there's a nuclear option to reinstall fisher I'd like that 👍

**Comment by bucaran** [comment]
@oskarrough 

If there's a nuclear option to reinstall fisher ?

Yes

```
curl -L git.io/fisher-up-me | fish
```

Notes: That is an older version of debug that still depends on that old code.

**Comment by oskarrough** [comment]
Thank you, but doesn't seem like it. Running the command gives me

`You seem to be running fisherman >=2.0.0 :)`

**Comment by bucaran** [comment]
@oskarrough So you are already using 2.0.0 I guess :)

Just delete the debug plugin then. That `debug` directory must be somewhere, I presume your config, simply erase it.

**Comment by oskarrough** [comment]
That was it! Thank you.

`rm ~/.config/fish/functions/debug.fish`
