### ISSUE TITLE
Fisher overwrites my fishfile

### ISSUE THREAD

**Issue by andrewrynhard** [fisherman/fisherman#218]
If I have a fishfile that exists in `~/.config/fish` then install `fisher` then run `fisher install` my `fishfile` get wiped out. How can you store your `fishfile` and on a fresh install use it to get the same setup?

**Comment by bucaran** [comment]
@andrewrynhard I can't repro this, it works just as expected. Here is what I did.

1. Remove fisherman from my setup to see if I could repro from a clean install.
2. `curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman`
3. `echo stark > ~/.config/fish/fishfile`
4. `fisher`

<img width="751" alt="screen shot 2016-04-24 at 11 17 59 am" src="https://cloud.githubusercontent.com/assets/8317250/14765128/38c87aa2-0a0e-11e6-9dd0-1b8c42404bd8.png">

**Comment by andrewrynhard** [comment]
I did run `fisher install`. Thanks.
