### ISSUE TITLE
Should fisher update also re-install prompts/themes?

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#22]
The current behavior of `fisher update` is to install the plugin again.

This is simply by calling `fisher install` after the update. This makes sense for a plugin, but perhaps not for a prompt/theme. If you are using prompt X and then `fisher update promptZ`, Fisherman will update `promptZ` and also set your current prompt to `promptZ`.

I have no problem with this, but perhaps we could add an option to `fisher update --no-install` or similar.

@tuvistavie @colstrom @tobywf

**Comment by tuvistavie** [comment]
It depends, what is the current behaviour if several themes are installed?
Could running `fisher update` change the theme, or is this only if the theme name is explicitly mentioned?

**Comment by bucaran** [comment]
@tuvistavie 

```
fisher update theme1 theme2 theme3
```

will update themes 1 2 and 3 in the cache and try to install each one after they are updated. If the last one is `theme3`, which would be, that one will be set.

**Comment by bucaran** [comment]
0.5.0 introduces `$fisher_theme` to keep track of the current theme and we are now checking currently installed plugins and not allowing users to re install them unless they use the --force flag.

As for 
```
fisher update theme1 theme2 theme3
```
The behavior of theme3 taking precendence will remain.
