### ISSUE TITLE
I feel fooled by the plugin fisherman, it makes my life worser, many times. 

### ISSUE THREAD

**Issue by melotusme** [fisherman/fisherman#225]
I'm frustrated. I'm fresh, but the plugin crashed many times. Just now,  it crashed again, because i just key `fisher update` in my terminal.

**Comment by bucaran** [comment]
@melotusme There was a dangerous upgrade recently, to 2.0, you can upgrade with:

```
curl -L git.io/fisher-up-me | fish
```

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately changes are not backward compatible, but you can upgrade with:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately changes are not backward compatible, but you can upgrade with:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately changes are not backward compatible, but you can upgrade with:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh).

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above didn't work out for some reason, feel free to reopen this issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```fish
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above doesn't work, please reopen the issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by bucaran** [comment]
@melotusme There was a huge update recently, to 2.0, unfortunately, changes are not backward compatible, but you can upgrade with the following if you are stuck in 1.5:

```fish
curl -L git.io/fisher-up-me | fish
```

Let me know if the above fixed your issue and if you need more help, you can [join.fisherman.sh](http://join.fisherman.sh). If the above doesn't work, please reopen the issue :)

Related: https://github.com/fisherman/fisherman/issues/223

**Comment by herrbischoff** [comment]
@melotusme: Also, it would be very helpful to get actual information and screen output instead of a whining post about how you feel. This is the behavior of so called "lusers". We really **want** to help you. We need information for that. Please help us help you. Thanks.

**Comment by bucaran** [comment]
@melotusme Also, please take no offence, but just in case there was a language miscommunication issue here, we have docs in Chinese too.

https://github.com/fisherman/fisherman/tree/master/docs/zh-CN

**Comment by laughedelic** [comment]
@bucaran that translation doesn't have the new upgrade instructions

**Comment by bucaran** [comment]
Good point. 

Ping @detailyang, if you have a second, can you fix it up? 🙏

**Comment by melotusme** [comment]
I did not want to take offence at beginning. But I'm really frustrated. I can get rid of it by myself, but it takes my time !!! And it's not the first. I just type `fisher update`, and everything goes wront, I feel amazing!!!. BTW, I found it may conflict with `mackup`. Thanks for all your answers.

**Comment by bucaran** [comment]
Run 

```fish
curl -L git.io/fisher-up-me | fish
```

If that does not work:

```
function rm_fisherman
    if test -d ~/.config/fisherman
        rm -rf ~/.config/fisherman 
    end

    if test -d ~/.cache/fisherman
        rm -rf ~/.cache/fisherman 
    end
end

## Call rm_fisherman

rm_fisherman
```

Then, just use:

```
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
```

to install fisherman 2.0 and you'll be in heaven.

**Comment by melotusme** [comment]
I found this in the readme file, but current, the  latest version is 2.2 in fishshell.com.
> fisherman was built for fish >= 2.3.0. If you are using 2.2.0, append the following code to your ~/.config/fish/config.fish for snippet support.

**Comment by pickfire** [comment]
@melotusme Don't worry, be happy! :smile: 

@bucaran IIRC, there is some bug with that `curl ...|fish` which doesn't remove the line that has been added in `~/.config/fish/config.fish`. Not sure if I can reproduce it now but I had to manually removed that in the past.

**Comment by melotusme** [comment]
@bucaran
Did you forget this???
```fish 
if test -d ~/.local/share/fisherman
  rm -rf ~/.local/share/fisherman
end
```

**Comment by pickfire** [comment]
@melotusme Nope, it is deleted.

**Comment by bucaran** [comment]
@detailyang Maybe you can help with Chinese translation?

> **@melotusme** All of you got fish 2.3???

I have 2.2.0.

The nuance is, fisherman was designed for 2.3.0, but it works just perfect in 2.2.0.

> Did you forget this???
>
if test -d ~/.local/share/fisherman
  rm -rf ~/.local/share/fisherman
end

Yes. Remove that too please.

**Comment by detailyang** [comment]
`fish shell` has released 2.3b1 and now i'm ready to upgrade the readme.md for Chinese:)

**Comment by bucaran** [comment]
@melotusme Please try fisherman again! I know the upgrade to 2.0 broke your shell, but 2.0 is so much better than 1.5 and after this there will never be more cross-versions breaking. My word.

**Comment by melotusme** [comment]
already get fixed by removing fisherman totally， and reinstall everything.  :)@brj

**Comment by brj** [comment]
@melotusme Awesome! Thanks.
