### ISSUE TITLE
remove dependencies

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#226]
> **@ndalliard** When I installed for example `simple`, ~~fin~~ fisherman installed some dependencies. When I `fisher rm simple`, the dependencies stay and I've to remove them from hand.

> **@bucaran** Removing simple should remove its dependencies, but only if they are not currently being used by other plugin, correct?

> **@ndalliard** What if the user installed them himself and maybe uses them for something else? Is that a possible scenario? Would make it a little bit harder to realise I think.

<h1></h1>

Say someone installs `segment`, to help them prototype a new prompt/theme they are working on.

While they are at that, they also install `stark` or `superman`, because they like it, or because they want to see `segment` in action.

Later they decide they don't want either of those and `fin rm stark superman`. By definition, this should remove `segment`, since these two prompts depend on segment, but then that's not what the user was expecting.

So, we need a way to know whether `segment` was installed as a dependency from another plugin, or by the user directly.

##### How can we determine this?

What about introducing a special character like `!` to lock plugins written in the bundle. 

```
fishery/segment!
```

That says, do not remove this plugin even if there is no other plugin depending in it. We could then add this character to plugins users install themselves.

> This should not be recursive.

<h2>

**Comment by avioli** [comment]
I would suggest a new fisher command to cleanup unused plugins - walk through all installed plugins and check their dependencies, then diff with currently installed ones and remove the ones that are unused.

**Comment by bucaran** [comment]
Yes, that's an option I like too. It doesn't even have to be a new command and we could just do it every time. I couldn't say if that would be slow, but based in my experience building this, I'd say is worth optimizing.

Thanks for sharing your opinion @avioli :)

**Comment by laughedelic** [comment]
> What about introducing a special character like ! to lock plugins written in the bundle

here's my opinion [from the slack chat](https://fisherman.slack.com/archives/general/p1461682336003904):

> I would put the special symbol (`!` or whatever it be), ​_before_​ the plugin name/url, not after. 
I think it's more noticeable, easier to parse (because a url can have some weird suffix) and coincides with the other annotations in `fisher ls

**Comment by laughedelic** [comment]
Also I think that fisherman should notify user that 

- when you remove some plugin, some of its dependencies are not removed because they are locked
- when you do global update, some plugins are not updated because they are locked with a certain version

**Comment by bucaran** [comment]
@laughedelic Ah, yes, I think putting the symbol _before_ the plugin name makes more sense than _after_. 👍

**Comment by bucaran** [comment]
> Also I think that fisherman should notify user that

> when you remove some plugin, some of its dependencies are not removed because they are locked

Clever idea. With this, we could avoid doing anything at all, and simply displaying a message.


> when you do global update, some plugins are not updated because they are locked with a certain version

How do you know the version of the plugin? We currently have mechanism in place for this.

**Comment by bucaran** [comment]
I would love to get some feedback from @fisherman/all. Implementing this feature is quite complicated, and I am not even sure if it's worth the trouble :)

**Comment by pickfire** [comment]
@bucaran, +1 for this feature. I think we need not to prompt user to ask for confirmation, maybe for which the user did `fisher in simple`, `simple!` will be added to the fishfile.

But the downside of is that it might be slow to determine if the dependency is required by a others plugin.

**Comment by bucaran** [comment]
To be honest I am not sure if this would be worth all the trouble. I do want to do something in this area, right now we are doing nothing, so at least some hint or anything.

**Comment by MadcapJake** [comment]
Another option would be to include a number per plugin (delimited by a `\0` or something) that represents how many other plugins depend on said plugin.  For instance, when you install `segment` it's given a value of 1 representing that it is depended upon by the user as the user directly installed it.  Then if you install `stark`  that depends on `segment` the value is incremented by one.  Whenever you remove a package like `stark` it decrements any depended upon plugin and if it falls to zero it is removed. So in the case of `segment` it would __not__ uninstall as the user personally installed it.

**Comment by bucaran** [comment]
@MadcapJake Reference counting! This is simple and clever. The problem is embedding the count in the fishfile which is not desirable, let me see what I think of.

**Comment by bucaran** [comment]
@fisherman/all Okay, I have come up with an implementation based in @MadcapJake's idea. I'll be pushing this to master and releasing it as 2.5.

This is a big change and bugs may have sneaked in during the production, but I think it's all for the best and future of the project.
