### ISSUE TITLE
fisherman adds .git suffix to some plugins unexpectedly

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#228]
I found this in my fishfile. I am unable to repro at the moment, but if anyone sees this, please let me know.

I'll try to reproduce later and close if fixed or can't reproduce again after testing for a period of time.

![screen shot 2016-04-26 at 9 35 45 pm](https://cloud.githubusercontent.com/assets/8317250/14818221/e322d454-0bf6-11e6-9980-7b3ded37d9e5.png)

**Comment by bucaran** [comment]
I have never seen this bug again. @laughedelic You were saying something about the fishfile on Slack.

Is it related or have you seen this bug before?

**Comment by laughedelic** [comment]
Nope, I haven't seen it before. In my situation it was a local plugin (git repo):

```fish
> fisher i ~/dev/laughedelic/fish
INFO Installing fish
OKAY Done in 148ms

> cat ~/.config/fish/fishfile
fisherman/anicode
oh-my-fish/plugin-brew
oh-my-fish/plugin-errno
laughedelic/.fish.git          # <-- this appears
fisherman/get
fisherman/getopts
fisherman/git_util
oh-my-fish/plugin-grc
fisherman/host_info
fisherman/humanize_duration
fisherman/last_job_id
fisherman/menu
fisherman/pwd_info
fisherman/pwd_is_home
fisherman/simple
fisherman/spin
fisherman/z
```

**Comment by bucaran** [comment]
I haven't been able to repro this again after the more recent changes and it seems related to #242, so I am going to track this as a whole thing there.
