### ISSUE TITLE
Sanitize the fishfile

### ISSUE THREAD

**Issue by rif** [fisherman/fisherman#23]
After several failed attempts to install some plugins my fishfile looks like this:

❯ cat ~/.config/fisherman/fishfile 
pure
https://github.com/oh-my-fish/fzf
https://github.com/oh-my-fish/fasd
https://github.com/oh-my-fish/tmux
https://github.com/oh-my-fish/plugin-fzf
fasd
tmux
fzf

We need a way to clean bad plugins from the file.

**Comment by bucaran** [comment]
There are two bugs here.

1. https://github.com/oh-my-fish/fasd is incorrect, it should be https://github.com/oh-my-fish/plugin-fasd
2. https://github.com/oh-my-fish/plugin-fzf was a mistake when you tried to install fzf, yet it was added to the fishfile incorrectly.
3. I see some empty blank lines there. Fisherman will not touch your blank lines, but it should not add any blank lines either.
