### ISSUE TITLE
Re-install plugin problem?

### ISSUE THREAD

**Issue by decors** [fisherman/fisherman#230]
My env: OS X Elcapitan, fish **2.3b1**, fisherman **2.1.10**

Install plugin with fisherman.
```
> fisher install foo 
INFO Installing 1 plugin/s
OKAY Done in 204ms
> tree -d ~/.config/fisherman/foo/
/Users/username/.config/fisherman/foo/
└── foo
    └── functions
```

And, uninstall and re-install it.
```
> fisher uninstall foo
OKAY Done in 105ms
> tree -d ~/.config/fisherman/foo/
/Users/username/.config/fisherman/foo/
```
```
> fisher install foo
INFO Installing 1 plugin/s
OKAY Done in 204ms
> tree -d ~/.config/fisherman/foo/
/Users/username/.config/fisherman/foo/
└── foo
  　 ├── functions
  　 └── foo
　       └── functions
```
That plugin's directory structure will be double depth.

**Comment by bucaran** [comment]
@decors Is "foo" a local plugin or a real plugin?

**Comment by decors** [comment]
@bucaran Real plugin.

**Comment by bucaran** [comment]
@decors I am sorry, I can't repro this. Can you take a screenshot?

**Comment by decors** [comment]
@bucaran Thanks.

It occurred in the update after re-install.
seems there is a problem with the `.cache`.

![reinstall](https://cloud.githubusercontent.com/assets/34811/14823813/cfbea65a-0c0e-11e6-9cd8-14b4b450a4cb.png)

**Comment by bucaran** [comment]
@decors Acknowledged. I am going to fix this right away.

**Comment by bucaran** [comment]
@decors 

I think the problem is here.

```fish
function __fisher_update_path_async -a name path
...
...
...
```
```fish
        if test -z \"\$commits\" -o \"\$commits\" -eq 0
            printf '$okay""OKAY""$nc Latest $okay%s$nc\n' '$name' > $__fisher_stderr
            command cp -rf '$path' '$fisher_cache/$name'
        else
            printf '$okay""OKAY""$nc $okay%s$nc new commits $okay%s$nc\n' \$commits '$name' > $__fisher_stderr
        end
```

**Comment by bucaran** [comment]
@decors https://github.com/fisherman/fisherman/commit/b20a6f8ee8c4d9a77c50384e6254927a95f78209

I think it's solved now, please reopen if you find the problem again.

解決したと思います。また同じことが起きたら、ぜひ再オープンお願いします。

**Comment by decors** [comment]
@bucaran ありがとうございます！アップデートして試してみます。
