### ISSUE TITLE
add a way to query, search, list, crawl or browse remote content, plugins in <org>/*

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#234]
Before, we had Search, and it was great. But it also makes us depend on the index file which is hard to maintain.

This proposal and what I am going to be working over the next hours is for a new builtin extension, via a command or subcommand to let us search or browse what plugins are available in the organization (should crawl oh-my-fish too).

**Comment by fishequality** [comment]
Hi folks! @bimawa @yxnino @melvinno @caocao485 @netroby @izuo I would like to introduce fisherman to you. Would you mind having a look over at the project? Cheers!

**Comment by bimawa** [comment]
+1 for search
