### ISSUE TITLE
how to install fundle into fisherman

### ISSUE THREAD

**Issue by rainchen** [fisherman/fisherman#235]
cause I want some fundle plugins, for example: 
* 'edc/bass'
* 'tuvistavie/fish-nvm'

**Comment by bucaran** [comment]
```
fisher edc/bass tuvistavie/fish-nvm
```

**Comment by rainchen** [comment]
@bucaran  thx the quick response.

I saw the `fisher help` and it said it can install omf plugin such as:
`fisher i omf/plugin-{percol,jump,fasd}`

I found a nvm omf plugin here: 
https://github.com/derekstavis/plugin-nvm

I used following command to install it: 
`fisher i derekstavis/plugin-nvm`

no errors and  `fisher list` can show it:
```
  nvm
  foreign-env
```

but I can't call the `nvm` command

```
$ nvm
bash: nvm: No such file or directory
```

did you have any idea for this?

**Comment by bucaran** [comment]
@rainchen Yes, fisherman works with most omf plugins and 99% of the themes, but `plugin-nvm` is a little special as it uses a deprecated event pattern support does not support anymore.

That's another reason why I created fin: https://github.com/fisherman/fin

Although, fin is still very new, it's working very nicely and I highly encourage you to try it out.

**Comment by rainchen** [comment]
@bucaran `fin` is nice but all of my teams are using nvm, I have to keep the same tech stack with them.

**Comment by bucaran** [comment]
@rainchen 

```
fisher edc/bass https://gist.github.com/bucaran/e21b07e6ee5bd5943a973cab22187a2a
```


<h1></h1>

On a related note, @FabioAntunes may be working on an nvm wrapper.

* See: https://github.com/fisherman/fin/issues/13

**Comment by FabioAntunes** [comment]
@rainchen (https://github.com/fisherman/nvm)[nvm] plugin was updated give it a go and report any issues you might find?

**Comment by rainchen** [comment]
@FabioAntunes impressed! 👍
