### ISSUE TITLE
Better help for failed installs

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#24]
If Fisherman fails to install a package it could offer better help adding something like:

```
Did you miss the `prefix-` or `theme-`?
```

In the case of oh-my-fish plugins, or even better, if it fails, then test with `plugin-` and if that fails too, test `theme-`. 

Another thing, it should validate `ohm-y-fish`, `o-hm-y-fsh` or similar looking URLs to the correct address.

**Comment by namandistro** [comment]
I agree with this i wanted to recommend the same..

**Comment by bucaran** [comment]
Thanks! Noted.

**Comment by bucaran** [comment]
@namandistro Please upgrade to 0.3.0! :anchor:
