### ISSUE TITLE
test: Missing argument at index 2 when running `fisher ls-remote`

### ISSUE THREAD

**Issue by amir20** [fisherman/fisherman#244]
```
$ fisher ls-remote
test: Missing argument at index 2
anicode			enhancd			git_porcelain		new			settitle		teapot
aquaman			fin			git_untracked_files	nvm			shark			termcolours
autoenvstack		fish-vte		gitignore		plugin-template		simple			terran
bobthefish		fishtape		hulk			prompt-template		snippet-template	tio
choices			flash			jellyfish		roach			spin			vault
cyber			fzf			joker			rvm			stark			vibrant
debug			get			koi			segment			submit
eco			git_branch_name		mock			sektor			superman
```

I am not sure what `test: Missing argument at index 2` means. I think it is a simple bug.

**Comment by bucaran** [comment]
That looks like a bug, but I am unable to reproduce it, both with no plugins installed or in my regular setup.

Please upgrade to the latest fisherman, then try again and tell me if this happens again.

Also, can you post what's inside your cache? 

```
ls -a ~/.cache/fisherman
```

**Comment by amir20** [comment]
I was running `2.4.1` which I think is the latest. I do `fisher up` often. 

Here is my cache. 

```
$ ls -a ~/.cache/fisherman
.
..
.index
.index.json
await
bang-bang
bass
dartfish
docker-completion
es
get_file_age
getopts
git_util
grc
host_info
humanize_duration
last_job_id
menu
nvm
pure
pwd_info
pwd_is_home
pyenv
rbenv
z

$ fisher -v
fisherman version 2.4.1 ~/.config/fish/functions/fisher.fish

$ fisher ls-remote
test: Missing argument at index 2
...
```

**Comment by bucaran** [comment]
@amir20 

Problem was __fisher_file_age was expanding to nothing, causing the test builtin to miss-behave.

If __fisher_file_age was expanding to nothing, that could mean you don't have Python installed on your system, which we use to determine the age of a file since it was last modified and decide whether to pull the index from scratch or not.

I a not sure how to do the same without Python, so that means you'll get download the index every time you query ls-remote.

Also, please remove the .index.json file, which is not used anymore.

```
rm  ~/.cache/fisherman/.index.json
```

**Comment by bucaran** [comment]
f3f284c5de0c2c3570a384c3a84d389effe1718b

**Comment by amir20** [comment]
Hi @bucaran, you intrigued my interest so I did a little debugging. It seems like you depend on Python 2.7 to be installed. I use `pyenv` and globally I was using python `3.5.1`. 

I noticed that this command `python -c "import os, time; print int(time.time() - os.path.getmtime('.'))" ` assumes version `2.7`. After switching to version 2.7 via `pyenv local system` I no longer see the error message. 

I believe this a bug and you should not assume a particular version is installed.

**Comment by amir20** [comment]
It might be worth adding `from __future__ import print_function` so that `print` works on 2.7 and 3. See [here](http://python-future.org/compatible_idioms.html) for more info.

**Comment by bucaran** [comment]
@amir20 How do you write

```
python -c "import os, time; print int(time.time() - os.path.getmtime('.'))"
```

in a way that works in both Python 2 and 3?

**Comment by amir20** [comment]
I have it working locally so this is what you want

```python
python -c "import os, time; from __future__ import print_function; print int(time.time() - os.path.getmtime('$file'))" ^ /dev/null
```

**Comment by amir20** [comment]
Does that line get executed every time? If I don't see the error, did it work or do I have to do something else?

**Comment by bucaran** [comment]
@amir20 Thanks, but that syntax is not working for me on Python 2.7 :(

**Comment by bucaran** [comment]
Maybe I can figure this out with perl...

**Comment by amir20** [comment]
Ok, I was able to make sure it works. You want 

```python
python -c "from __future__ import print_function; import os, time; print(int(time.time() - os.path.getmtime('.')))"  
```
<img width="1052" alt="screen shot 2016-05-01 at 1 20 55 pm" src="https://cloud.githubusercontent.com/assets/260667/14943149/9237ecda-0f9f-11e6-8e00-260a765b3909.png">

**Comment by bucaran** [comment]
Awesome, that's working. Thanks @amir20. I will ship

**Comment by bucaran** [comment]
9de333d687e892a08ac0ed80e7c38a9caf87b236
