### ISSUE TITLE
should we add some new project scaffolding functionality to fisherman?

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#245]
I know I have shown reluctance before to add new commands, but I was _just_ wondering, what would you think of adding some of following functionality to fisherman? I am probably okay with any of the following options, but I am sure @fisherman/all can help me choose the best one.

1) Nothing. Don't do this.

2)

```ApacheConf
$ fisher plugin # get the plugin template fisherman/plugin-template and scaffold new project
❯ What's your plugin name? peach
❯ What's your plugin about? About Princess Peach
❯ What's your GitHub username? kingbowser
    ✓ Creating peach from plugin template
    .editorconfig
    .gitignore
    .travis.yml
    completions/peach.fish
    functions/peach.fish
    functions/uninstall.fish
    LICENSE
    man/man1/peach.md
    README.md
```

The other templates are "prompt" and "snippet".

3) Same as above, but via a command named `init`.

**Comment by sotayamashita** [comment]
I prefer (3). `init` is very familiar with npm or bundle user and command behaviour like below:

```fish
$ fisher init
name:  '<string>' | directory name
description:  '<string>'
keywords: ['<string>', ...]
type: plugin | prompt | snippet
```

**Comment by FabioAntunes** [comment]
Couldn't that be a plugin instead? Not everyone is a plugin developer and adding more commands and tools that most of the people won't use will just increase fisherman size and complexity.

**Comment by bucaran** [comment]
@FabioAntunes @sotayamashita Thank you guys for your feedback.

Closing as won't fix.
