### ISSUE TITLE
fisherman fails to restore colors correctly if the user is missing definitions for some of fish_color_* uvars

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#246]
Affected user:
* @s0r00t 

Related
* https://github.com/oh-my-fish/theme-bobthefish/issues/35

**Comment by s0r00t** [comment]
This also happens with the default colorscheme (which I was using).
(wow. didnt even have time to finish my comment before it got closed)

**Comment by bucaran** [comment]
@s0r00t Fixed :)

**Comment by bucaran** [comment]
> @s0r00t This also happens with the default colorscheme (which I was using).

Yes, I can imagine. So, undefined uvars were being saved as blanks in the fish_colors restore file, which is okay, but when fisherman tried to restore the colors, blanks were skipped and the next available color would be set to the previously undefined variables causing everything to go crazy.
