### ISSUE TITLE
`fisher ls-remote` does not play nice with pipes

### ISSUE THREAD

**Issue by colstrom** [fisherman/fisherman#249]
Output of ls-remote is in columns. At least when piped, it should be one record per line.

`isatty stdout` can be used to check for this.

Actual:
```
$ fisher ls-remote | cat
foo	bar	baz
abc	def	ghi
```

Expected:
```
$ fisher ls-remote | cat
foo
bar
baz
abc
def
ghi
```

**Comment by bucaran** [comment]
Coming to theaters near you in 2.6.0.

**Comment by bucaran** [comment]
#257
