### ISSUE TITLE
`fisher update --me` spews errors then loops at a spinner forever.

### ISSUE THREAD

**Issue by colstrom** [fisherman/fisherman#25]
```
$ fisher update --me
Updating >> Fisherman
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
test: unexpected argument at index 2: '10 81184 stopped cat | grep -o .'
```

It's hard to paste a spinner here, so just imagine it's on the last line.

**Comment by Polyg0n** [comment]
What's your system setup and fish config? Because I just ran ```fisher update --me``` and it finished without errors.

**Comment by bucaran** [comment]
@colstrom New in 0.3.0 is `$fisher_timeout`. `curl(1)` could be spinning on itself if the network is bad. But, if it's not that either then I am not sure. I will investigate ASAP.

**Comment by Polyg0n** [comment]
@bucaran Can't be if the network pipe is offline (or turned off) I just checked that. My full terminal output is thus:

```
corbin@linux-box ~/Desktop> fisher update --me
Updating >> Fisherman
corbin@linux-box ~/Desktop> 
```
Disabled network simply won't output spinner.

**Comment by bucaran** [comment]
@Polyg0n Thanks, noted.

**Comment by bucaran** [comment]
`fisher update --me` will be deprecated in 0.3.0. Now the default behavior will be updating fisherman.
