### ISSUE TITLE
issue with grc install

### ISSUE THREAD

**Issue by elwan** [fisherman/fisherman#251]
hello i have already installed grc  but when i do fisher up it said "You need to install grc!" .do you have faced to this issue?

**Comment by detailyang** [comment]
can you show this output in terminal as follow:
````bash
grc --version
````
:beers:

**Comment by bucaran** [comment]
@elwan I don't use grc, but @domoritz could help you with it.

In short, the omf/grc plugin is just a fish-wrapper for grc, so you need to download the actual grc:
* https://github.com/garabik/grc

**Comment by domoritz** [comment]
Everything worked just out of the box for me. I installed grc, made sure it's in the path (run `grc --version`) and then installed the omf/grc plugin.

**Comment by bucaran** [comment]
@elwan I see what the problem is.
> https://github.com/fisherman/fisherman#1-what-is-the-required-fish-version

So, if you can't upgrade to the latest fish right now, just add:

```fish
for file in ~/.config/fish/conf.d/*.fish
    source $file
end
```

to your config.fish until you can.

**Comment by bucaran** [comment]
@elwan Is the problem solved now?

**Comment by bucaran** [comment]
@elwan So, were you able to fix the problem?

> https://github.com/fisherman/fisherman/issues/251#issuecomment-216887810

**Comment by bucaran** [comment]
@elwan @domoritz I rewrote the plugin removing the startup time penalty and adding a proper uninstall script. Please upgrade to fisherman/grc.

```
fisher rm grc
rm -rf $fisher_cache/grc # remove old oh-my-fish copy of the grc
fisher grc
```
