### ISSUE TITLE
Error thrown when git is not installed

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman#253]
Now that the installer has moved to a single curl command, there is no check whether `git` is installed on the system. I found out after trying to install some plugins, but the error message was less than friendly.

I'd suggest a `fisher doctor` command that checks for multiple things like fisherman being out of date, or command line utilities not being installed (awk, git etc).

What does @fisherman/all think?

**Comment by bucaran** [comment]
fisherman already does some basic health checks on startup / exit, so rather than introducing a new command, we could lazily catch the error before it happens and inform the user.

```
if not type -q git
    echo "really dude? ..."
end
```

**Comment by jethrokuan** [comment]
Great if that's already in place, but it didn't for me

**Comment by orangecms** [comment]
All checks must be performed. However, it is sensible to assume LSB or basic *NIX/GNU tools to be installed.

**Comment by bucaran** [comment]
Some checks are in place, but nothing for git or curl, which I'll add and ship with 2.6.0.

**Comment by bucaran** [comment]
#257
