### ISSUE TITLE
use a single source of truth for the blacklisted plugins

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#255]
Do not repeat code, use a fisher.fish scoped variable to keep track of what plugins are blacklisted, and share the list with embedded awk scripts.

**Comment by bucaran** [comment]
https://github.com/fisherman/fisherman/issues/257

**Comment by laughedelic** [comment]
What's "blacklisted plugins"?

**Comment by bucaran** [comment]
Stuff like the index, docker-builds, etc.
