### ISSUE TITLE
Autocomplete is cluttered with uninstalled plugins

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#256]
I [raised](https://fisherman.slack.com/archives/feedback/p1461961539000126) this question in the chat before:

> When I type `fisher <tab>` here's what I see:
> ```
> aquaman  (Prompt)  help           (Show help)  ls              (List what's installed)  rm  (Remove plugins)  update  (Upgrade and update plugins)
Choices  (Plugin)  install  (Install plugins)  ls-remote  (List what can be installed)  theme-eden  (Prompt)
> ```
> are these plugins/themes supposed to be there? I've tried them at some point, but then removed (so they don't appear in `fisher ls`)

@bucaran:

> fisher<Tab> should show you what plugins you can install, the same as fisher install<Tab>.
> Notice those plugins are plugins ​*not currently*​ installed.    

First, `fisher install <Tab>` shows only the plugins that were installed and then removed, not just "plugins you can install" (which would be, for example `fisher ls-remote`'s cached list).

Secondly, if I uninstalled some plugins, I don't want to use them and therefore I don't want to see them in autocomplete. Besides, I think autocomplete after typing just `fisher ` is useful only if it shows the available commands and doesn't mix it with some plugin names. I think it's against autocomplete-discoverability, especially for new users that may install and delete a lot of plugins to try them and then never find some of the cool fisherman commands through autocomplete.

And the last, what is the right way to cleanup the cache to remove these plugins completely?

**Comment by bucaran** [comment]
@laughedelic Autocomplete shows you the plugins you _can_ install (it learns these from stuff you have installed previously). If you install `aquaman`, and later uninstall it, `fisher install <TAB>` will `aquaman` will be in the autocomplete.

**Comment by bucaran** [comment]
#257

**Comment by laughedelic** [comment]
> Uninstalling a plugin does not necessarily mean I will never install it again

Sure, but these uninstalled plugins shouldn't have priority over other plugins that haven't been installed yet. In the old fisherman, I think there was a concept of _disabled_ plugins — it was also confusing for me, but at least there was a clear distinction..

> we could generate fisher [install] <TAB> completions from ls-remote's output instead of the current behavior

👍 

> fisherman follows the XDG spec

OK. ( To be honest, I haven't heard about XDG before I encountered fisherman "_ )


> fisher [install] <TAB>
> fisher -h shows you all the cool commands you can use

I, _personally_, think that this implicit default `install` command is rather confusing and makes interface non-uniform.
