### ISSUE TITLE
Autocomplete for rm and ls commands

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#258]
I think that autocomplete for both of these commands should suggest all installed plugins (what is showed by `fisher ls`).

**Comment by bucaran** [comment]
That's exactly what they do. The same is true for `fisher update`.

**Comment by bucaran** [comment]
@laughedelic 

Yeah, and that's exactly what they do. Same for `fisher update` :)

**Comment by laughedelic** [comment]
Then something doesn't work. They give me autocomplete for the files in current directory "/

**Comment by bucaran** [comment]
@laughedelic If you create a new terminal window, you need to run fisher at least once. This is obvious from the fact `fisher` is self-contained. It does actually put some basic completions in your *completions* directory, but that's about it.

**Comment by laughedelic** [comment]
Well, I got some new problems after running just `fisher` (see https://github.com/fisherman/fisherman/issues/242#issuecomment-217467825), but besides that, I've got autocomplete for _some_ installed plugins, except of the plugins installed from the oh-my-fish org. Even though they are all listed in `fisher ls`.

Also, autocomplete for the local plugins shows strange description:
```
ec2ls                                                       (~/.config/fisherman/ec2ls)
fish                                                         (~/.config/fisherman/fish)
```

(They are actually both in `~/dev/laughedelic/`)

**Comment by bucaran** [comment]
This one is easy to fix, we should simply follow symlinks. Thanks for reporting that. Feel free to create an issue for this too if you want, I'll fix it right away.

Closing this as invalid.

**Comment by laughedelic** [comment]
What I see in 2.6.4 is

<img width="493" alt="screen shot 2016-05-06 at 22 24 59" src="https://cloud.githubusercontent.com/assets/766656/15085248/66e182d8-13d9-11e6-8985-45d4081fb20c.png">

I guess, it's not supposed to be like this

**Comment by bucaran** [comment]
That only occurs when the index is not available, so I guess you deleted it. 

```
cat ~/.cache/fisherman/.index
```

**Comment by laughedelic** [comment]
Oh! I see.. After calling `fisher ls-remote`, I have good autocomplete. 
It's so confusing and inconvenient that every time I start a new fish-shell session I have to call `fisher` just to get any autocompletion and then to call `fisher ls-remote` (at least once) to get good autocompletion... I mean, I understand why it work like this, but it's confusing and inconvenient from the user's perspective.

**Comment by laughedelic** [comment]
By the way, you can say that this good autocomplete doesn't work _"out of the box"_. Can't we have it as a plugin then? Minimal functionality out of the box and good extra autocomplete that _always_ works once installed.

**Comment by bucaran** [comment]
@laughedelic Yeah, it bothers me too. I'll try an experiment and get back to you.

**Comment by bucaran** [comment]
@laughedelic Done ;)
f1b676e08a5c7d2c11c4ec4e823accf32cb57408

**Comment by bucaran** [comment]
f1b676e08a5c7d2c11c4ec4e823accf32cb57408
@laughedelic Done ;)
