### ISSUE TITLE
Add dotfiles tutorial to README

### ISSUE THREAD

**Issue by jadengore** [fisherman/fisherman#259]
One of the things that really stood out to me was [oh-my-fish's dotfiles section](https://github.com/oh-my-fish/oh-my-fish#dotfiles). It really helped me as a newbie get all set up with it, and it would be cool if Fisherman had this as well.

**Comment by bucaran** [comment]
@jadengore 

What did you try and what didn't work?

When I built wahoo and oh-my-fish (I am no longer maintaining either of those projects, and they are pretty much inactive by now), the idea of doing dotfiles with fish was essentially the same as oh-my-zsh, which seemed pretty acceptable at the time.

With fisherman, you can do dotfiles in any way you like. In my case, I commit the entire fish directory, which includes the *fishfile*, config.fish and uvar file. You may choose to ignore the *functions* and *completions* directory.

**Comment by jadengore** [comment]
My original post:
> I've been unable to get Fisherman set up in my dotfiles, and after dealing with symbolic linking and a bunch of other issues for a couple days I switched to oh-my-fish (only because I couldn't sink any more time into this).

I was unable to reproduce the issues that turned me away from Fisherman in the first place. However, I think some simple documentation on dotfiles like @bucaran provided above in the README would be helpful.

**Comment by bucaran** [comment]
> I would be willing to PR.

👍 👍 👍 👍

**Comment by bucaran** [comment]
I had a little change of heart. Let's keep the FAQ as it is and refer to future users to this issue. Here is the missing tenth question.

# 10. How do I use dotfiles with fisherman?

Commit *~/.config/fish* to your dotfiles.

**Comment by jadengore** [comment]
@bucaran 👍

**Comment by tuukkamustonen** [comment]
New to fish and all but `~/.config/fish` contains at least `fishd.personal` and `fish_history` which you're _not_ supposed to commit to dotfiles, right?

**Comment by JorgeBucaran** [comment]
@tuukkamustonen You could commit them if you wanted to keep your history, but I guess it dependso on a case by case basis. I don't commit it.

**Comment by tuukkamustonen** [comment]
Also what I found is that `z`, for example, creates symlinks in `.config/fish/functions` and if your username is different on different machines, the symlinks break (because of absolute path).

So, maybe this answer should actually be put to FAQ (and refined a bit)?

**Comment by JorgeBucaran** [comment]
@tuukkamustonen Sure! 👍
