### ISSUE TITLE
smart tab completions are not preserved across sessions unless you run `fisher [<command>]`

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#262]
This is not a problem within the same session / subshells as fisherman updates completions every time it runs, but if you create a new window / tab, you'll notice completions are not persisted accordingly.

**Comment by laughedelic** [comment]
So how it's supposed to work? I run `fisher ls-remote` once, I have cached index now, then I open a new fish session and I should have good autocomplete for, say, `fisher rm`, right?
