### ISSUE TITLE
Keybindings from {fish_,}key_bindings files are handled wrong

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#263]
Follow up of the [talk in the chat](https://fisherman.slack.com/archives/dev/p1462578443000618).

I have two plugins each of which defines some keybindings. 

- If they define a function called `fish_user_key_bindings` then everything is handled as it's supposed to:

  ```fish
  function fish_user_key_bindings
  	### A ###
    ...
    ### A ###
    ### B ###
    ...
    ### B ###
  end
  ```

- if they define a function called `fish_key_bindings` or just `key_bindings`, then this is what comes out after reinstalling them:

  ```fish
  function fish_user_key_bindings
  	### A ###
    function key_bindings
    ...
    end
    ### A ###
    ### B ###
    function key_bindings
    ...
    end
    ### B ###
  end  
  ```

  which obviously doesn't work.

- if only one of them defines `fish_user_key_bindings`, then the _other_ one won't appear in the result

**Comment by bucaran** [comment]
Observed. Will fix right away.
