### ISSUE TITLE
Local plugins are managed inconsistently

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#264]
See the beginning of #242. Questions that are left open:

1. There is an unclear notion of "hidden plugins", their name starts with a dot and they don't appear in the fishfile or `fisher ls`. So what are hidden plugins and why do we need them?
2. If a local plugin is a git repo with a remote, this remote will be added to the fishfile and the plugin will be listed in `fisher ls`.
3. If a local plugin doesn't have a git remote, it will be listed in `fisher ls`, but _not_ in the fishfile

The second bothers me because, when I run `fisher`, it gets the plugin from the remote, which is already installed locally.

I think that the behaviour of the third case is the most logical (of these three) and I don't see any point in having hidden plugins that are installed but you don't know about it. 
My suggestion
- add local plugin's _full path_ to the fishfile (nothing about git)
- list it in `fisher ls` (as it is now)

This way adding a local plugin to the fishfile or installing it through `fisher install` will be the same. See https://github.com/fisherman/fisherman/issues/242#issuecomment-215859834. At the moment, if I add a local plugin to the fishfile and then run `fisher`, the one with git remote is substituted with it, and the one without git remote is just removed from the fishfile.

**Comment by bucaran** [comment]
1. Good question. Hidden plugins are probably useless and most likely a side effect. Just don't start your plugins with a dot.

2. Observed.

3. Observed.

---

I will start by making 2 consistent with 3, which is to not add the plugin to the fishfile.

**Comment by bucaran** [comment]
Pushed 2.6.10.

1. Still pending. 
2. Local plugins are not added to fishfile at all, I find this rather convenient. They do show if using `fisher ls`
3. See 2.

**Comment by laughedelic** [comment]
Nice! Making 2 & 3 consistent is already a lot. Having a local plugin with a git remote in the fishfile was also messing up in #263 (it had duplicated keybindings, because of the 2 different names)

**Comment by bucaran** [comment]
I'll experiment a bit with adding local plugins to the fishfile, and see how fisherman behaves.
