### ISSUE TITLE
z plugin doesn't work

### ISSUE THREAD

**Issue by seagle0128** [fisherman/fisherman#267]
I update to the latest version. z plugin doesn't work after I restart the fish terminal.

I got this error:
`fish: Unknown command 'z'`

if I run `fisher u`, then it works again.

**Comment by bucaran** [comment]
@seagle0128 

You are probably just missing snippet support.

> https://github.com/fisherman/fisherman#what-is-the-required-fish-version
> #### What is the required fish version?

>=2.2.0.

> For snippet support, upgrade to >=2.3.0 ***or*** append the following code to your ~/.config/fish/config.fish.
>```fish
for file in ~/.config/fish/conf.d/*.fish
    source $file
end

**Comment by seagle0128** [comment]
Thanks for the solution!

**Comment by bucaran** [comment]
@seagle0128 One more thing:

> https://github.com/fisherman/fisherman/issues/241

If you've updated from 1.5 to 2.0, please refer to the linked issue.
