### ISSUE TITLE
fisher silently clobbers pre-existing functions

### ISSUE THREAD

**Issue by colstrom** [fisherman/fisherman#268]
Steps to reproduce:
- Create a function (let's use `mock` as an example).
- `fisher install mock` or any plugin with a conflicting name.
- Check your `$fish_functions_path` and see that `mock.fish` has been overwritten with a symlink to the plugin installed.
- `fisher uninstall mock`, and now both are deleted.

This is surprising behaviour, and may be (in the case of non-version-controlled functions) a negative experience. Some discussion on what the "correct" behaviour is would be practical. Offhand, a few things come to mind:

- Check if they are the same file, or are linked to the same location. It may be reasonable to silently overwrite in this case.
- Advise the user of the conflict, and either:
  - Fail
  - Present a diff, and prompt the user to choose one.

Other ideas?

**Comment by bucaran** [comment]
We can fail or fail that item if we are installing a list of items / plugins. What would be a good way to report this to the user?
