### ISSUE TITLE
Install from branch or tag

### ISSUE THREAD

**Issue by colstrom** [fisherman/fisherman#269]
Would be nice to install from a branch or tag (both options, ideally).

`fisher install plugin@develop` or `fisher install plugin@1.0.0`. As a proposed syntax, which is consistent with similar use cases in the wild.

These represent two different use cases (branch-based deployment, and version pinning), but the implementation would likely be the same for both, give how git handles these things.

Thoughts?

**Comment by bucaran** [comment]
Would be nice to have. fishfile parser would need to change as well to support tags / versions this way.

Incidentally, for testing / developing, what I usually do, is _git clone_ the plugin, install it as link, test and publish when I am done.

**Comment by colstrom** [comment]
@bucaran That's only as good as "works on my box". It's nice to ship pre-release builds for interested parties.

Totally agree about the fallback, I'd assume the sane fallback would be to do as it does now, and assume `master` if undefined.

**Comment by bucaran** [comment]
@colstrom Can you describe how this feature would work as far as the CLI is concerned?

**Comment by aristidesfl** [comment]
Apologies for reviving this issue. Where was the `@` notation inspired from?
Github seems to use `:`

![screen shot 2017-02-10 at 15 04 37](https://cloud.githubusercontent.com/assets/208149/22829351/746e6560-efa2-11e6-83fa-7be344a548b8.png)

**Comment by FabioAntunes** [comment]
Be guess would be npm https://docs.npmjs.com/cli/install

**Comment by jbucaran** [comment]
@aristidesfl We could support `:` too. I don't really have a strong preference since I don't use this feature.

**Comment by aristidesfl** [comment]
@jbucaran useful to test plugins pull requests no?

**Comment by jbucaran** [comment]
@aristidesfl I guess the reason we went with `@` was from:

> @colstrom fisher install plugin@develop or fisher install plugin@1.0.0. As a proposed syntax, which is consistent with similar use cases in the wild.

**Comment by jbucaran** [comment]
* https://github.com/fisherman/fisherman/blob/master/fisher.fish#L480

This is the regex, can you send a PR?
