### ISSUE TITLE
Check Fish version, exit if too low

### ISSUE THREAD

**Issue by msikma** [fisherman/fisherman#271]
Just now I updated my Fisherman (finally!) but started getting some strange errors. I realized it was because I was still on an old version of Fish, the 2.1 branch. After updating to 2.2.0, everything was fine.

Since Fisherman pretty much crashed and burned on the old version, maybe it's worth having a brief check? Something like this:

```fish
function __fisher_check_fish_version
    set -l fish_version (fish --version 2>&1 | grep -oE "[0-9]+.[0-9]+.[0-9]+")
    # test: set -l fish_version 2.1.3
    set -l fish_major (echo $fish_version | cut -f1 -d.)
    set -l fish_minor (echo $fish_version | cut -f2 -d.)
    if [ $fish_major -lt 2 -o $fish_minor -lt 2 ]
        echo "Current Fish version is $fish_version."
        echo "A minimum version of 2.2.0 is required to run Fisherman."
        exit 1
    end
end

__fisher_check_fish_version
```

This is the first time I've actually written a Fish script, so it's probably a mess. So I didn't send it in as PR, but I'll do that if you think this is a valid addition 😄

**Comment by bucaran** [comment]
I think we could perform this check outside the `fisher` function itself in the file. This way the code would run only "once", when the `fisher.fish` file is sourced by fish, that is, the first time the function is called, but only the first time.

**Comment by bucaran** [comment]
https://github.com/fisherman/fisherman/commit/846758a8528c4c2d1dfdf26bfbd6568865281b26
