### ISSUE TITLE
Regex / fuzzy search in ls-remote

### ISSUE THREAD

**Issue by brj** [fisherman/fisherman#279]
fisher ls-remote and fisher ls-remote PLUGIN [PLUGIN...] allows you to list and search one or more plugins, but it would be nice if we could use a regex to search and match fields other than the default, plugin's name.

```fish
# match name by default

fisher ls-remote a                  # regex→ /^a/
fisher ls-remote "/a.*(er)$/"       # regex→ /a.*(er)$/
fisher ls-remote "/^a|^z/"          # regex→ /^a/
fisher ls-remote "/^a|^z/"          # regex→ /^a/

# match other fields

fisher ls-remote "%stars > 5"
fisher ls-remote "%url ~ /oh-my-fish/"
fisher ls-remote "%info ~ /theme|prompt/"
fisher ls-remote "%info !~ /[Pp]owerline/"
```

**Comment by Globegitter** [comment]
On that note, is there a way now with `ls-remote` to e.g. only search for themes? That feature used to exist in the past but can not find any documentation on it, nor playing around with the command has lead me to anything.

**Comment by brj** [comment]
@Globegitter Correct. There isn't a simple way since the search command was removed in favor of the simpler ls-remote (at first), now not so simple anymore.

You can which are omf themes since they show up like:
<img width="1280" alt="screen shot 2016-06-01 at 10 54 23 pm" src="https://cloud.githubusercontent.com/assets/8317250/15712073/cd2e8b90-284b-11e6-9b42-d18d198a049f.png">

But it's not totally impossible:

<img width="1280" alt="screen shot 2016-06-01 at 11 05 50 pm" src="https://cloud.githubusercontent.com/assets/8317250/15712493/75d31314-284d-11e6-861f-244ae84ecc34.png">

**Comment by brj** [comment]
Closing as I'd rather focus on the 3.0 roadmap. This whole thing may even go away in 3.0.
