### ISSUE TITLE
Plugins with custom key bindings clears functions outside of fish_user_key_bindings

### ISSUE THREAD

**Issue by terlar** [fisherman/fisherman#283]
It is quite common for people to define functions outside of the main `fish_user_key_bindings` function inside  `~/.config/fish/functions/fish_user_key_bindings.fish`.

The current implementation of fisherman will resave the function file without these functions and in that way they will disappear.

Example:

`~/.config/fish/functions/fish_user_key_bindings.fish`:
```fish
function fish_user_key_bindings
	bind \er __commandline_sudo_toggle
end

function __commandline_sudo_toggle
	set pos (commandline -C)
	set cmd (commandline)

	if string match -q 'sudo *' $cmd
		set pos (expr $pos - 5)
		commandline (string replace 'sudo ' '' $cmd)
	else
		commandline -C 0
		commandline -i 'sudo '
		set pos (expr $pos + 5)
	end

	commandline -C $pos
end
```

Installing plugin with key-bindings:
```fish
fisher install laughedelic/pisces
```

**Comment by bucaran** [comment]
Thanks @terlar, I'll make this happen very soon.

**Comment by laughedelic** [comment]
Huh.. 🤔 I didn't notice it, because I stored my custom key bindings in a plugin and it got all merged with other plugins.
