### ISSUE TITLE
Where is bobthefish theme?

### ISSUE THREAD

**Issue by seagle0128** [fisherman/fisherman#286]
I am unable to install bobthefish theme now. It seems it has been removed, but why? Moreover, I cannot install omf/theme-bobthefish either. 

```
~> fisher install omf/theme-bobthefish
Installing 1 plugin/s
! Fetch bobthefish github.com/oh-my-fish/theme-bobthefish
Installing 1 dependency
Fetch bobthefish
Remove bobthefish
Done in 726ms
```

**Comment by bucaran** [comment]
Works here:

<img width="1280" alt="screen shot 2016-05-17 at 4 48 10 pm" src="https://cloud.githubusercontent.com/assets/8317250/15314832/293962ba-1c4f-11e6-8053-0d2d6962a502.png">

**Comment by seagle0128** [comment]
I am using Ubuntu mate 16.04 LTS with fish 2.2.0 and fisher 2.7.1.
I cleaned the cache and reinstalled successfully. 
BTW, metro is cool!
Thanks and close it.

**Comment by bucaran** [comment]
Great!
