### ISSUE TITLE
Submitting plugins to the index?

### ISSUE THREAD

**Issue by nyarly** [fisherman/fisherman#287]
Is there a process for submitting plugins to be added to the index?

**Comment by bj** [comment]
Basically [this](https://github.com/fisherman/index#adding-plugins-to-this-list). Do note that the index only powers the online [search](http://fisherman.sh).

The CLI tool (fisher) queries the GitHub API instead, currently both github/orgs/{fisherman,oh-my-fish}.

**Comment by nyarly** [comment]
Is the CLI going to change? It seems confusing to have one search do one thing and another do the other

**Comment by bj** [comment]
It is like this at the moment for historical reasons. Before 2.0, we used to rely on that index for everything. 

The new (current) fisherman's design querying the GitHub API is superior to whatever we had before, but the website didn't keep up to date. I would love to revamp the website search, but I'd rather focus on improving fisherman itself.

Recently some people have shown interest to help with the website, but there is nothing concrete yet.

**Comment by brj** [comment]
Closing as resolved.
