### ISSUE TITLE
Key bindings?

### ISSUE THREAD

**Issue by nyarly** [fisherman/fisherman#289]
Does fisherman support plugins defining keybindings, or is the closest it comes allowing a function to be defined and letting the user include that in their fish_user_key_bindings.fish?

**Comment by laughedelic** [comment]
Here's an example plugin for you: [pisces](https://github.com/laughedelic/pisces) 😉 
And here's a relevant issue in the fish repo: https://github.com/fish-shell/fish-shell/issues/3032

**Comment by brj** [comment]
@nyarly It does! This bit is not documented as much as I'd like to, but basically your plugin can expose bindings via a function named `key_bindings.fish` or `user_key_bindings.fish`.

During install, fisherman will extract the binding code and merge it into any existing key bindings inside your ~/.config/fish/functions/.

**Comment by laughedelic** [comment]
Also when your plugin is uninstalled fisherman erases those bindings that you do [explicitly](https://github.com/laughedelic/pisces/blob/master/key_bindings.fish#L15-L21), but if you call `bind` from a function of [in a cycle](https://github.com/laughedelic/pisces/blob/master/key_bindings.fish#L11-L13), you need an [uninstall script](https://github.com/laughedelic/pisces/blob/master/uninstall.fish#L7-L11) to tell fisherman how to take care of those bindings.

**Comment by brj** [comment]
Closing as resolved!
