### ISSUE TITLE
Update plugins if given full original name or url

### ISSUE THREAD

**Issue by nyarly** [fisherman/fisherman#290]
fisher update <plugin> reports 'skipped <plugin>' even though the plugin has been updated remotely. `fisher rm <plugin>; fisher install <plugin>` succeeds, but restores the old version of the plugin

**Comment by brj** [comment]
What are the steps to reproduce the problem?

**Comment by nyarly** [comment]
The trick here is that I'd 

```
fisher install nyarly/fish-cache-file
```

so I'd tried to
```
fisher update nyarly/fish-cache-file
```
which led to
```
Updating 1 plugin
! Skipped nyarly/fish-cache-file
Done in 31ms
```

If I `fisher update cache-file`, it pulls the new commits.

So, I see now how to do that properly, but it was certainly surprising.

**Comment by laughedelic** [comment]
Yep, I was also confused about this at first.

**Comment by nyarly** [comment]
It seems to me that other commands make suggestions about namespaces etc. And somehow `fisher` changed `nyarly/fish-cache-file` into `cache-file` when it did the original install. Perhaps either it could do the same for update (maybe with a warning) or fail with "try <short name>"

**Comment by brj** [comment]
Did you try just:

```
fisher u cache-file
```

**Comment by nyarly** [comment]
I did that, after doing `fisher ls` and noticing that it was listed as `cache-file`

**Comment by brj** [comment]
Yeah, I just read you did. See my edits above as to why that makes sense.
