### ISSUE TITLE
Run uninstall script before removing the plugin functions

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#293]
I don't know if it's a good idea, but here is my reasoning:

- uninstall script is not a function and I cannot reuse it in the plugin itself
- I want to define a function which will do plugin "unload" (part of the uninstall script) to reuse it for plugin "reload" feature
- but I cannot call it from the uninstall script, because at the moment it's run the function is already deleted

**Comment by brj** [comment]
Sounds reasonable. This could be implemented as either a function or an event.

**Comment by brj** [comment]
What is this plugin "reload" thing and what kind of plugin are you talking about? Do you have any examples?

**Comment by brj** [comment]
Now the uninstall script is sourced *before* the functions are erased.
