### ISSUE TITLE
Help subcommand completion

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#294]
I don't get any completion on `fisher help <tab>`. At least the list of plugins installed would be useful, even better only those that actually provide help. 

By the way, what is the way for plugins to provide a help page?

**Comment by brj** [comment]
Good catch. I didn't add completions for help commands because I felt it would be too slow to walk the plugin tree and check if they include any man pages.

So, what we can do for now is, simply add all the installed plugins to help <TAB> completion.

**Comment by laughedelic** [comment]
Ok. I'll take a look on how to generate a man page. But will `man spin` work as well?
How about showing plugin's README in pager as a fallback when there is no man page?

**Comment by brj** [comment]
> But will man spin work as well?

Nope. That would involve modifying the MANPATH on shell startup. We used to do that in <=2.0, but not anymore, as fisherman is completely standalone now.

> How about showing plugin's README in pager as a fallback when there is no man page?

That would be nice.
