### ISSUE TITLE
Deleting an entry from the fishfile should uninstall the missing plugin

### ISSUE THREAD

**Issue by brj** [fisherman/fisherman#296]
* Similar to [fin](https://github.com/fisherman/fin).

**Comment by tentakel** [comment]
something to note is that this effects the readme and all of its translations

**Comment by brj** [comment]
Certainly, but the title is misleading. This is just a proposal, if no one has much to say about this feature, I may not add it at all.

**Comment by brj** [comment]
@fisherman/all Thoughts?

**Comment by laughedelic** [comment]
Would be nice to have this feature, but it's definitely not essential.. This would be even more useful with ability to comment out lines in the fishfile.

**Comment by brj** [comment]
@laughedelic You can't comment lines in the fishfile?

**Comment by laughedelic** [comment]
Until now I didn't know that I can 😆

**Comment by brj** [comment]
Yep, you can.

**Comment by brj** [comment]
Closing this as wontfix.

I looked at how we are using the fishfile in fisherman, and it turns out the fishfile tracks down everything the user has installed including deps. This format is different to what I ended up doing in fin, so I see now it's not really compatible with fisherman.

fisherman emphasizes the CLI, fin the config, pick one :)
