### ISSUE TITLE
Prompt 'eco' removed?

### ISSUE THREAD

**Issue by nesmyslny** [fisherman/fisherman#300]
Actually this is not an issue with fisherman, but maybe someone here knows what is going on :)

I use the prompt `eco`. It's listed in the fisherman plugin list and the repository used to be here:
https://github.com/fisherman/eco

This repo is gone now and redirects to https://github.com/fisherman/fin

So after the last `fisher up` my beloved prompt disappeared 😭 Please help 😃

**Comment by brj** [comment]
@nesmyslny Oops, sorry, I removed it, for a few random reasons that won't really bring it back right now, so let's try to find a copy instead. I've created an empty repo here https://github.com/fisherman/eco, would you happen to have a copy laying around?

**Comment by nesmyslny** [comment]
Yeah! Thank you very much @brj 😄

**Comment by brj** [comment]
👯
