### ISSUE TITLE
Fisherman is broken with fish version 2.3.0

### ISSUE THREAD

**Issue by bitwave** [fisherman/fisherman#302]
The new fish version breaks fisherman.

Regards,
bitwave

**Comment by brj** [comment]
Do you have any evidence?

**Comment by brj** [comment]
@bitwave

**Comment by brj** [comment]
@bitwave 

Do you have any evidence, logs, or anything to show?

I'm on fish 2.3 and everything is apparently running fine.

**Comment by brj** [comment]
@bitwave 

Do you have any evidence, logs, or anything to show?

I'm on fish 2.3 and everything is (seemingly) running fine.

**Comment by brj** [comment]
@bitwave 

Do you have any evidence, logs, or anything to show?
I'm running fish 2.3 and everything is running fine.

Also, make sure you've seen this: https://github.com/fisherman/fisherman/issues/241

**Comment by brj** [comment]
Ping @bitwave

**Comment by bitwave** [comment]
I reinstalled it completely. It works now.

**Comment by brj** [comment]
Thanks! Yeah, sorry about that.
