### ISSUE TITLE
Lost snippet when duplicate name of snippets

### ISSUE THREAD

**Issue by dynamotn** [fisherman/fisherman#303]
I installed first plugin with snippet a.fish, then install second with also snippet a.fish but different contents => Only keep snippet a.fish of second plugin

Can you merge 2 snippets to one in conf.d instead of create softlink to last snippet?

**Comment by brj** [comment]
If the first and second plugin have different names, say A and B, and both happen to include a `conf.d/x.fish` snippet, then we could prepend / append the name of the plugin to the soft link solving whatever issue you had. 

If the first and second plugin have the same name, then you are out of luck. 

> Can you merge 2 snippets to one in conf.d instead of create softlink to last snippet?

Not impossible. They could be prepended to the existing snippet inside a `begin; end` block to prevent local var leakage, but then how do we unmerge them later if A or B is uninstalled? Seems like asking for trouble :)

**Comment by laughedelic** [comment]
I think that prepending snippet names with plugin names is a better solution. Even if it not about two conflicting plugins: (from the [docs](file:///usr/local/Cellar/fish/2.3.0/share/doc/fish/index.html#initialization))

> ...
> If there are multiple files with the same name in these directories, only the first will be executed.

So if a user has some snippet, say in `/usr/share/fish/vendor_conf.d/foo.fish` and then installs a plugin with `conf.d/foo.fish`, the original one won't be loaded.

About plugins having the same name, won't fisherman report a conflict on installation (already installed or smth)?

**Comment by brj** [comment]
> I think that prepending snippet names with plugin names is a better solution. Even if it's not about two conflicting plugins: (from the docs)

Yeah. Actually, I thought this was already the way it worked. Perhaps it changed in the transition to 2.0.

> About plugins having the same name, won't fisherman report a conflict on installation (already installed or smth)?

I think it will create a backup of such files inside functions/*, but that's it.

**Comment by laughedelic** [comment]
How about storing plugins in `$fisher_config/org/name` instead of just `$fisher_config/name`? Same about cache.

**Comment by brj** [comment]
That could be done, that's what fin does btw, but you still can't install two plugins with the same name just like you can't have two functions with the same name.

**Comment by brj** [comment]
@dynamotn What about using $fish_path. This would separate your fish config from fisherman's and there would never be clashes. You'd be responsible for adding the {functions,completions} to the path, but that's it.

**Comment by brj** [comment]
The solution is to use $fish_path. 

```fish
set -U fish_path ~/my/path
```

If you do as above, fisherman will copy functions, completions and snippets under that prefix, so there will be no fear of name collisions.

Let me know how that goes.
