### ISSUE TITLE
git.io/fisherman link is down

### ISSUE THREAD

**Issue by sooheon** [fisherman/fisherman#304]
This breaks installation instructions. Change to point to file on github master?

**Comment by brj** [comment]
Use `https://raw.githubusercontent.com/fisherman/fisherman/master/fisher.fish` in the meantime, GitHub is going to fix this for me in a bit.

**Comment by brj** [comment]
Actually is back up again. This is odd.

**Comment by brj** [comment]
Confirmed. It's back :)
