### ISSUE TITLE
Dependencies out of nowhere

### ISSUE THREAD

**Issue by Shadowigor** [fisherman/fisherman#306]
Hi

I tried to install my own theme. It has no fishfile and no dependencies, but fisherman is still asuming some (see picture). Is this a problem with my theme or with fisherman? The theme works flawless, except for that message.

![fisher](https://cloud.githubusercontent.com/assets/6695660/15739791/f8268bde-28b1-11e6-9f6a-2e8b740ddf0f.png)

**Comment by brj** [comment]
@Shadowigor Observed! I'll send a fix shortly. Thanks for reporting :)

**Comment by brj** [comment]
Fixed! Thanks again.
