### ISSUE TITLE
Display help for plugin not installed with "fisher help PLUGIN"

### ISSUE THREAD

**Issue by sevkin** [fisherman/fisherman#309]
Ok, install fisherman then type `fisher ls-remote` and see "the list of some names"
How do I know about each of them?

I think `fisher help` must download, display and cache description for not installed plugins from registry.

**Comment by laughedelic** [comment]
You can get short information about each plugin in the output of `ls-remote`, it has `--format` option. I don't know if it's documented anywhere besides the [release notes](https://github.com/fisherman/fisherman/releases/tag/2.2.0). So you can do something like

```fish
fisher ls-remote --format="%name: %info\n"
```

**Comment by sevkin** [comment]
I see this short descriptions in suggestion list. But in order to make responsible decisions about how to install the plugin i need to know mooore :)

**Comment by brj** [comment]
@sevkin Hmm, in order to do what we need to download the plugin, then see if it has a man page or not. Problem is, few plugins include a man page. The vast majority have none, so fisherman would just say something:

```
There's no manual for this plugin.
Try online: <github.com/fisherman/git_util>
```

**Comment by laughedelic** [comment]
I just want to remind about idea that I suggested some time ago: https://github.com/fisherman/fisherman/issues/294#issuecomment-220498331 (showing readme when there's no manpage). 
I don't know how hard is to do it, but another idea is to request just the man/readme file content from github, if the plugin is not installed/stored in cache yet.

**Comment by brj** [comment]
That would be nice!

**Comment by brj** [comment]
@laughedelic Question. When we read the README, do we just pipe the markdown in the user's default pager?

**Comment by daenney** [comment]
I don't really want to be parsing Markdown. There's tools like `md2man` that can convert markdown in a sensible way but a generic README usually does not a great manpage make.

**Comment by laughedelic** [comment]
I agree that any converting markdown to man won't give better results and doesn't make much sense. So I would just show the readme as is. Yes, sometimes it won't give much usage information, etc. but either it's better than nothing, or the author just didn't take time to write any kind of usage documentation, then there's nothing user or fisherman can do (the user should write to the author requesting documentation, probably).

**Comment by sevkin** [comment]
Probably not worth thinking about the formatting of the README and an improvement in the registry?
Registry may issue a unified information about the plugin:
- name
- short description
- source url
- long description AKA help

**Comment by laughedelic** [comment]
@sevkin what's registry? Current `ls-remote` information is collected without any kind of centralized index, it just uses github API to get information about all repos in the @fisherman/@oh-my-fish orgs. So there's no simple way to get that "long description AKA help" from anywhere except of readme.

**Comment by sevkin** [comment]
@laughedelic i dont know. may be http://fisherman.sh ?
How work `fisher help` ?

**Comment by laughedelic** [comment]
@sevkin the search on that website is powered by the [index](https://github.com/fisherman/index), which is manually curated (plugin authors add their plugins there), and **this is not related** to what you see when you do `fisher ls-remote` (see #308).

In the current version, `fisher help` is supposed to be used only for those plugins that are already installed (or were installed and remained in cache), you can see it from the completion when you type `fisher help <TAB>`. If the plugin has a man page, it is shown, otherwise you only get the link to the repo.

**Comment by sevkin** [comment]
imho perfectly!

[fisherman/index](https://github.com/fisherman/index) can be improved to download and install founded plugins (into docker image) then capture and save output of `fisher help`

The Registry :)

**Comment by laughedelic** [comment]
Save where? Again, fisherman CLI and the online search/index are not connected anyhow.

**Comment by sevkin** [comment]
pr welcome

**Comment by laughedelic** [comment]
@sevkin The proposed solution is just to retrieve plugin's man-page when you do `fisher help` if it's not installed/in cache yet. Plus to show the readme if the plugin doesn't have a man page. 
Aren't you happy with this solution? I'm not sure if @brj is already working on it or it will be left open for a third-party PR..

**Comment by sevkin** [comment]
@brj add label WIP ?

**Comment by brj** [comment]
What about just looking at the help / README online?

**Comment by daenney** [comment]
What @brj said. I'm not exactly convinced that showing unrendered markdown text in a terminal is any better than just going to look at the README on GitHub or wherever else it is hosted.

**Comment by brj** [comment]
Yes, `fisher help` displays the repository link if no man page is available.

**Comment by brj** [comment]
Related
![man_page](https://cloud.githubusercontent.com/assets/8317250/15966167/e9047a4c-2f5c-11e6-863c-00c62d2a446c.png)

* https://xkcd.com/1692/
