### ISSUE TITLE
Feature of exporting environment variables from plugins is broken

### ISSUE THREAD

**Issue by changyuheng** [fisherman/fisherman#310]
To reproduce:

1. Install plugin `pyenv` and `https://github.com/yyuu/pyenv`.
2. Create another fish session.
3. Compare the results of `echo $PATH` before and after executing `fisher update`.

**Comment by changyuheng** [comment]
Oh sorry, has documented here https://github.com/fisherman/fisherman#what-is-the-required-fish-version .

**Comment by daenney** [comment]
See also the second note in the fisherman/pyenv README: https://github.com/fisherman/pyenv

> On Fish 2.3.0 and later support was introduced that automatically loads snippets in conf.d. However, these snippets are evaluated before your config.fish. If you're setting PYENV_ROOT in your config.fish to relocate your pyenv installation this will be evaluated after our plugin gets loaded and hence have no effect. In order to fix this you should drop a 000-env.fish file in your ~/.config/fish/conf.d folder which sets up your environment accordingly.
