### ISSUE TITLE
On fisherman.sh, can you implement a browse instead of just a search?

### ISSUE THREAD

**Issue by brettgoulder** [fisherman/fisherman#311]
On fisherman.sh, would you be able to implement a browse instead of just a search?

I really have no idea the names of the plugins to start looking for and it would be nice to poke around.

Is there a list somewhere?

**Comment by laughedelic** [comment]
There's some fragmentation:
- you can do `fisher ls-remote --format="%name: %info\n"` to see the list of plugins from the @oh-my-fish and @fisherman orgs (or just browse these orgs on Github)
- you can check the [index](https://github.com/fisherman/index/blob/master/index) that powers fisherman.sh search. But it's just a text file and probably is not very convenient.

These two lists have a big intersection, but ~~unfortunately~~ are not the same.

**Comment by brj** [comment]
@BretJohnson You can get the list of plugins you can install using `fisher ls-remote`.

The website is still here for historical reasons; it used to be more useful. Ideally, it would query the GitHub API to retrieve repos from the orgs, just like the CLI client does currently, but no one has gotten around that.
