### ISSUE TITLE
github api rejects calls when `fisher ls-remote` is run too frequently

### ISSUE THREAD

**Issue by ianferguson** [fisherman/fisherman#312]
Currently if `ls-remote` is run too frequently, fisher will begin returning the following error, 

```
! I could not update the remote index.

This is most likely a problem with http://api.github.com/
or a connection timeout. If the problem persists, open an
issue in: <github.com/fisherman/fisherman/issues>
```

This might potentially be due to github throttling/rejecting anonymous api searches occurring above a similar rate, similar to the conditions that led to homebrew to support passing an API token to homebrew for searches: https://gist.github.com/christopheranderton/8644743

Would it be possible to enable similar facilities in fisher that would allow users to provide an API token to fisherman for the github call behind ls-remote?

**Comment by brj** [comment]
Hi @ianferguson.

* GITHUB_USER and 
* GITHUB_TOKEN 

are available.

```fish
set -x GITHUB_USER ianferguson
set -x GITHUB_TOKEN xxxxxx
```

**Comment by ianferguson** [comment]
Awesome, thanks! Would it be helpful if I opened a PR to updates the docs
somewhere with that info?

**Comment by brj** [comment]
@ianferguson Yes, it would be! Can you add a new question to the FAQ?

**Comment by ianferguson** [comment]
opened #314
