### ISSUE TITLE
fishfile does not contain enough information to reclone plugin repos

### ISSUE THREAD

**Issue by ianferguson** [fisherman/fisherman#315]
I currently have a set up where I have just my config.fish and fishfile checked into my dotfiles repo in git: https://github.com/ianferguson/dotfiles/blob/master/fish/.config/fish/fishfile and want to use it across multiple computers.

This currently works fine only if all the fisherman plugins installed are github.com repos, in which case when a new plugin is in the fishfile (after pulling from the dotfiles repo) running fisher results in that repo being cloned and the plugin installed.

In the case of git repos that are not hosted at github.com (github enterprise, atlassian stash, bitbucket, etc), there is not enough information to reconstruct the original url used.

i.e., if I run `fisher install https://github-enterprise.some-company.com/ianferguson/a_fisher_plugin` it will install successfully (I believe because the URL just ends up getting passed through in whole to the __fisher_plugin_url_clone_async function, but not 100% sure, just started reading the source this morning, sorry!), but that plugin will be saved to the fishfile as just 'ianferguson/a_fisher_plugin'.

Then in the case that `~/.config/fisherman/a_fisher_plugin` either didn't exist (because the fishfile is shared between multiple hosts via the dotfiles repo mentioned above) or is deleted locally for whatever reason, when `fisher` or `fisher up` is run next, fisher will pull in `ianferguson/a_fisher_plugin` and look for https://github.com/ianferguson/a_fisher_plugin, rather than the originally cloned location.

I'm not sure if it would be acceptable/sensible to have fully qualified URLs as an optional either format for a line in the fishfile or as an additional field that can be tagged on after the line, such as `ianferguson/a_fisher_plugin https://github-enterprise.some-company.com/ianferguson/a_fisher_plugin`, but some approach like that would allow a fishfile to be a fully encapsulated amount of information for installing a set of plugins from any arbitrary git repository.

**Comment by ianferguson** [comment]
It also just occurred to me that rather than trying to squeeze the repository information into the fishfile, it may make more sense to use an approach more similar to homebrew's tap system, and allow a user to add custom taps/endpoints which the $username/$pluginname combos from the fishfile could be tried against in succession until a match was found

**Comment by brj** [comment]
> **@ianferguson** ...plugin will be saved to the fishfile as just 'ianferguson/a_fisher_plugin'.

Really? I think this could be partially fixed if we make fisherman's fishfile behave like fin's fishfile.

Are you familiar with fin? https://github.com/fisherman/fin

Just like fisherman, fin too, ignores the git host, i.e. `github`, `bitbucket`, etc., when copying the repos into the cache, but _fin_ stores the repo inside a namespace like `fisherman/repo` or `oh-my-fish/repo`, etc., whereas fisherman only puts stuff under ~/.config/fisherman (it does do some "sophisticated" namespace resolution to allow you to install repos of the same name and from different orgs, but other than that is quite simple).

**Comment by ianferguson** [comment]
@brj I looked at fin a bit, is the main difference that fin _only_ does installs/removals/etc via working from its fishfile, vs fisher supporting that and interactive commands?

Do you anticipate fin being developed long term? I may just be able to switch to using that if it already supports full URLs in the fishfile, but was hesitant to do so if most/all development was going to stay behind fisherman

**Comment by brj** [comment]
Yes, that's the main difference, but fin supports less features than fisherman too, see:
* https://github.com/fisherman/fin/issues/5#issuecomment-222481377

> Do you anticipate fin being developed long term? I may just be able to switch to using that if it already supports full URLs in the fishfile, but was hesitant to do so if most/all development was going to stay behind fisherman

Absolutely. Both will be developed and maintained. 

I actually use fin, since I really don't need most of fisherman's advanced feature set, e.g. key bindings. The idea with fin is to stay small and simple, but still useful.

**Comment by ianferguson** [comment]
after reading through the fin source, I think I'm going to go ahead and switch over to that (configuration only+simple mechanics match what I actually want/need), though it does seem like it would be a nice improvement if the line `fisher install $plugin_name_or_url` added to the fishfile was added in a way that included the host/full url if needed, but maybe not worth the effort given that I think syncing up dotfiles across machines as outlined above is the main use case where that is extra helpful, and fin is a better fit for that workflow, so far as I can tell right now

**Comment by brj** [comment]
@ianferguson How's fin? Going to close this for now.
