### ISSUE TITLE
how to deal with it behind a firewall?

### ISSUE THREAD

**Issue by kupusc** [fisherman/fisherman#316]
I'm behind a corpo firewall, and I guess I need a proxy to be able to fetch anything (ls-remote works, though).

**Comment by detailyang** [comment]
hi, maybe you can check this [post](https://wiki.archlinux.org/index.php/proxy_settings), it use env http_proxy to proxy http connection in terminal.

wish it's useful to you :grin:

**Comment by brj** [comment]
I hope these articles are helpful:

* http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server
* http://stackoverflow.com/questions/5529218/how-to-use-git-behind-a-proxy
