### ISSUE TITLE
WIki: Bootstrap Instructions

### ISSUE THREAD

**Issue by zacheryph** [fisherman/fisherman#317]
Not an issue, but wanted to make the people that need to know know.  I didn't realize wiki pages on github were open to all.  Wanted to let people know in case this is not needed.

I added a wiki page: https://github.com/fisherman/fisherman/wiki/Bootstrap

This is an easy way to only put `config.fish` and `fishfile` in your dotfiles repository and ensure fish installs fisherman and plugins if needed (will only get executed once upon inital execution of fish)

**Comment by brj** [comment]
Thanks @zacheryph! It's great.

**Comment by sotayamashita** [comment]
I changed `fisher` to `fisher -v`.

**Comment by brj** [comment]
If there's nothing to add here, then I'll close this. Thanks again.
