### ISSUE TITLE
Why plugins in $XDG_CONFIG_HOME/fisherman instead $XDG_DATA_HOME/fisherman?

### ISSUE THREAD

**Issue by bbqtd** [fisherman/fisherman#319]
Just a question. For me `$XDG_DATA_HOME` more viable than `$XDG_CONFIG_HOME` for storing data that I want `share` between my or local devices (like vendoring) instead populate `$XDG_CONFIG_HOME` that I want share between my coworkers and hold this directory small as possible for symlinking whole directory.

**Comment by brj** [comment]
What about sharing the fishfile? That way you can simply clone your dotfiles repo, cd into the directory and run `fisher` to get everything like your other machine.

**Comment by bbqtd** [comment]
Yes, it's most simple way when you just clone it and make install all plugins by `fishfile`. But I think about plugins as _data_ for `fisherman`, not configuration, because it's not configuration files for `fisherman` it's _data_ that `fisherman` link it and update it.

It's not very important but I think it's unclear when you share your `configs` with some kind of `data` that users in most cases don't need it (welcome `.gitignore`). 

Anyway it's just my proposal :), I just want see `fisherman` more `xdg` compatible that provide you do some tricks with `$XDG_DATA_HOME`.

**Comment by brj** [comment]
@bbqtd Don't want to fix what's not broken, but if you are able to come up with a compelling PR, I would be happy to merge, prepare for the transition and cut a new release :)

**Comment by bbqtd** [comment]
@brj Cool, I'm ready to do it.

**Comment by bucaran** [comment]
Hi @bbqtd! Haven't heard from you in almost a month and since I am not particularly inclined to work on this myself I'm going to close the issue. Feel free to bring this back up to life when you are ready to give it a shot.
