### ISSUE TITLE
fisher update should remove broken links

### ISSUE THREAD

**Issue by robsonpeixoto** [fisherman/fisherman#321]
If some script change the name, fisherman keep the old symlink pointing to a file that not exists.

**Comment by bucaran** [comment]
There's no way to do this, unless fisherman runs a script in the background that's always checking the integrity of your links/files. 

Related?
* https://github.com/fisherman/fisherman/issues/182
* https://github.com/fisherman/fisherman/issues/305

**Comment by robsonpeixoto** [comment]
Run a script after the update is a good solution, IMHO, @bucaran

**Comment by bucaran** [comment]
Thanks @robsonpeixoto. Sure, I'd be happy to review and merge a PR for this.
