### ISSUE TITLE
fishfile empties after installing packages on WSL

### ISSUE THREAD

**Issue by Perlence** [fisherman/fisherman#322]
I'm running fisherman on Windows Subsystem for Linux. Installing and deleting packages works, but all contents of fishfile are replaced by a single byte `'0x0a'`.

**Comment by bucaran** [comment]
Hi @Perlence. What version of fisherman are you running?

**Comment by Perlence** [comment]
I'm using fisherman v2.10.0

**Comment by bucaran** [comment]
@Perlence Thanks for your patience. I will ask on the slack channel if there is anyone using fish on windows and see if they have experienced any issues.

**Comment by jbucaran** [comment]
@Perlence Sorry for the delay with this issue. What is your current status on this?

**Comment by Perlence** [comment]
@jbucaran Still an issue, even on 2.11.0.

**Comment by jbucaran** [comment]
@Perlence Thanks for the update. I don't have WSL, but I don't want to give up on this either.

[Here](https://github.com/fisherman/fisherman/blob/master/fisher.fish#L348) is the line where the fishfile is updated:

```fish
    switch "$cmd"
        case ls ls-remote
        case \*
            if test -z "$config"
                echo > "$fisher_file"
                set -e fisher_dependency_count
            else
                __fisher_plugin_get_url_info -- "$fisher_config"/$config > $fisher_file
            end
    end
```

If you navigate to that line and add some instrumentation code before or inside the function `__fisher_plugin_get_url_info`, you could help me debugging this guy.

**Comment by Perlence** [comment]
I guess, the problem comes from `echo > "fisher_file"`. Variable `$config` is empty because:

```
[~/.c/f/fisherman]-⟩ command find $config_glob -maxdepth 0 -type d | command sed "s|.*/||"
Could not send process 646, 'sed' in job 1, 'find | sed "s|.*/||"' from group 468 to group 645
setpgid: Operation not permitted
sed: read error on stdin: Input/output error
```

**Comment by jbucaran** [comment]
@Perlence Thanks!

**Comment by jbucaran** [comment]
@Perlence Hi. Did you open the issue on the WSL tracker? I haven't seen any cross-referenced issues, so I'll assume you are busy. 

Please reopen if you got any news :)

**Comment by Perlence** [comment]
@jbucaran Hey, I opened the issue https://github.com/Microsoft/BashOnWindows/issues/1210, so we can only wait while folks at Microsoft figure it out.
