### ISSUE TITLE
fisher update

### ISSUE THREAD

**Issue by killua99** [fisherman/fisherman#323]
I've had a few problems updating to the latest fisherman build.

When I run fisher update I get: Aye! Fisherman updated to version 0.7.0 (0s)

Why is not updating to the latest one, 2.x.x ? what if I install fisherman again? I'm gonna lose the setting I've ?

**Comment by laughedelic** [comment]
Check https://github.com/fisherman/fisherman/issues/241

**Comment by killua99** [comment]
I guess I was the last to read this, might be helpful to be on the main README.md

Thanks for the support!

**Comment by bucaran** [comment]
@laughedelic Thanks.

@killua99 Were you able to get everything back up okay?
