### ISSUE TITLE
`fisher` wipes out fishfile if stdin is /dev/null

### ISSUE THREAD

**Issue by garyp** [fisherman/fisherman#326]
Steps to reproduce:

1. Start with a clean install (i.e. no plugins)
2. Add some plugins to `~/.config/fish/fishfile`
3. Run `fisher < /dev/null`

Expected results:

* Fisherman installs the plugins added in step 2

Actual results:

* Fisherman does not install the plugins added in step 2
* Output of `fisher` command is "No plugins to install or dependencies missing."
* `fishfile` is truncated, resulting in an empty file with no plugins listed

---

I ran into this problem because I was trying to run `fisher` from an ansible playbook, and by default ansible runs commands with stdin set to `/dev/null`. I'm not too familiar with the internals of fisherman, but it looks like https://github.com/fisherman/fisherman/blob/master/fisher.fish#L362 needs to be changed from `__fisher_read_bundle_file | read -az argv` to `__fisher_read_bundle_file < "$fisher_file" | read -az argv`. Making that change in my local copy does fix the problem for me.

**Comment by bucaran** [comment]
Hi @garyp! 

<img width="624" alt="screen shot 2016-08-22 at 9 29 19 am" src="https://cloud.githubusercontent.com/assets/8317250/17840825/f7f07a84-684a-11e6-9bd9-c04377175beb.png">

**Comment by bucaran** [comment]
We can't set `__fisher_read_bundle_file < "$fisher_file" | read -az argv` as that would remove the ability to install plugins from stdin, which is a "feature".

See L182

```fish
    if test -z "$items" -a "$cmd" = "default"
        if isatty
            command touch "$fisher_file"

            set cmd "install"
            set items (__fisher_read_bundle_file < "$fisher_file")

            if test -z "$items"
                __fisher_log info "
                    No plugins to install or dependencies missing.
                " > /dev/stderr

                __fisher_log info "
                    See &$fisher_cmd_name help& for usage instructions.
                " > /dev/stderr
                return
            end
        else
            set cmd "install"
        end
    end
```

Try adding `echo` log statements in there and see what branch fisherman is running when you use it from your ansible playbook.

**Comment by jbucaran** [comment]
@garyp! 

<img width="624" alt="screen shot 2016-08-22 at 9 29 19 am" src="https://cloud.githubusercontent.com/assets/8317250/17840825/f7f07a84-684a-11e6-9bd9-c04377175beb.png">

My fishfile is not truncated.

---


We can't set `__fisher_read_bundle_file < "$fisher_file" | read -az argv` as that would remove the ability to install plugins from stdin, which is a "feature".

See L182

```fish
    if test -z "$items" -a "$cmd" = "default"
        if isatty
            command touch "$fisher_file"

            set cmd "install"
            set items (__fisher_read_bundle_file < "$fisher_file")

            if test -z "$items"
                __fisher_log info "
                    No plugins to install or dependencies missing.
                " > /dev/stderr

                __fisher_log info "
                    See &$fisher_cmd_name help& for usage instructions.
                " > /dev/stderr
                return
            end
        else
            set cmd "install"
        end
    end
```

Try adding `echo` log statements inside each branch and see which one fisherman is running when you use it from your ansible playbook. This is key to fixing the issue :)

**Comment by gimoh** [comment]
I just came across this when trying to run fisher during docker build. Given the following `Dockerfile`:

```
FROM ohmyfish/fish

RUN curl \
  -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

RUN \
  mkdir -p /home/nemo/.config/fish/ \
  && printf '%s\n' fisherman/g2 > /home/nemo/.config/fish/fishfile

RUN ls -l /home/nemo/.config/fish/fishfile
RUN fish -c fisher
RUN ls -l /home/nemo/.config/fish/fishfile
```

when I run `docker build` I get:

```
> docker build -f Dockerfile.fisher-326 -t fisher-326 .
Sending build context to Docker daemon 112.1 kB
Step 1/6 : FROM ohmyfish/fish
 ---> 3d7d98a101de
Step 2/6 : RUN curl   -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher
 ---> Using cache
 ---> e7c978b66129
Step 3/6 : RUN mkdir -p /home/nemo/.config/fish/   && printf '%s\n' fisherman/g2 > /home/nemo/.config/fish/fishfile
 ---> Running in 7668bb6ddccf
 ---> 9355bfc3c55b
Removing intermediate container 7668bb6ddccf
Step 4/6 : RUN ls -l /home/nemo/.config/fish/fishfile
 ---> Running in 5eff22b047fc
-rw-r--r--    1 nemo     nemo            13 Jul 10 12:35 /home/nemo/.config/fish/fishfile
 ---> 49f701969ac6
Removing intermediate container 5eff22b047fc
Step 5/6 : RUN fish -c fisher
 ---> Running in a56cc0276fd4
No plugins to install or dependencies missing.
 ---> 7c62045f744c
Removing intermediate container a56cc0276fd4
Step 6/6 : RUN ls -l /home/nemo/.config/fish/fishfile
 ---> Running in 0882fd5c4d9e
-rw-r--r--    1 nemo     nemo             1 Jul 10 12:35 /home/nemo/.config/fish/fishfile
 ---> 410bb2c9aa97
Removing intermediate container 0882fd5c4d9e
Successfully built 410bb2c9aa97
```

In this case, in the code you referenced `isatty` returns false, so it just goes into the `else` `set cmd "install"` branch.

**Comment by gimoh** [comment]
BTW, this works around it:

```
RUN fish -c 'fisher < /home/nemo/.config/fish/fishfile'
```
