### ISSUE TITLE
How do you uninstall fisherman?

### ISSUE THREAD

**Issue by padurean** [fisherman/fisherman#327]
I tried to use it to install nvm wrapper for fish, but no success.
I've installed latest version, but i can not seem to get rid of:

```
ogg-machine:~ ogg$ fish
source: Error encountered while sourcing file '/Users/ogg/.local/share/fisherman/config.fish':
source: No such file or directory
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

Permissions on `./local/share`:

```
ogg@ogg-machine ~ λ la /Users/ogg/.local/share/
total 0
drwxr-xr-x  3 ogg  staff   102B Aug 30 12:12 .
drwxr-xr-x  4 ogg  staff   136B Feb  2  2016 ..
drwxr-xr-x  4 ogg  staff   136B Aug 30 12:15 fish
ogg@ogg-machine ~ λ la /Users/ogg/.local | grep share
drwxr-xr-x   3 ogg  staff   102B Aug 30 12:12 share
```

Versions:

```
ogg@ogg-machine ~/w/g/P/client-web (master) λ fish --version
fish, version 2.3.1
ogg@ogg-machine ~/w/g/P/client-web (master) λ fisher --version
fisherman version 2.10.0 ~/.config/fish/functions/fisher.fish
```

Realising there's no `uninstall` command i've run the installer multiple times:
`curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher`, but the problem persisted.

I've also defined and run this (as described in a comment on issue #232):

```
## Copy and paste into your terminal

function rm_fisherman
    if test -d ~/.config/fisherman
        rm -rf ~/.config/fisherman 
    end

    if test -d ~/.cache/fisherman
        rm -rf ~/.cache/fisherman 
    end

    if test -d ~/.local/share/fisherman
        rm -rf ~/.local/share/fisherman
    end
end

## Call rm_fisherman, bye bye!

rm_fisherman
```

and then i re-run the installation script - same issue.

Now i'd like to uninstall it (Mac OS latest) - which are directories/files that i have to delete in order to completely erase fisherman from my machine?

Here is what i have (i've listed the directories mentioned in README.md):

```
ogg@ogg-machine ~/w/g/P/client-web (master) λ tree ~/.config/fisherman
/Users/ogg/.config/fisherman
0 directories, 0 files

ogg@ogg-machine ~/w/g/P/client-web (master) λ tree ~/.cache/fisherman
/Users/ogg/.cache/fisherman
├── bass
│   ├── Makefile
│   ├── README.md
│   ├── functions
│   │   ├── __bass.py
│   │   └── bass.fish
│   └── test
│       └── test_bass.fish
└── nvm
    ├── README.md
    ├── __nvm_can_run.fish
    ├── __nvm_run.fish
    ├── completions
    │   └── nvm.fish
    ├── fishfile
    ├── node.fish
    ├── npm.fish
    └── nvm.fish

5 directories, 13 files
ogg@ogg-machine ~/w/g/P/client-web (master) λ fisher ls
ogg@ogg-machine ~/w/g/P/client-web (master) λ tree ~/.config/fish
/Users/ogg/.config/fish
├── completions
│   └── fisher.fish
├── conf.d
├── config.fish
├── fish_history
├── fish_read_history
├── fishd.acbc32c5e489
├── fishfile
└── functions
    ├── debug.fish -> /Users/ogg/.config/fisherman/functions/debug.fish
    ├── fish_prompt.fish
    ├── fisher.fish
    ├── fisher.fish.1472547589
    ├── fisher.fish.1472548075
    ├── spin.fish -> /Users/ogg/.config/fisherman/functions/spin.fish
    └── treegg.fish

3 directories, 13 files
```

Thanks in advance.

P.S.
Isn't it common sense that if something has a "command" to install it, it should also have a command to UN-install it? :(

**Comment by bucaran** [comment]
It's just a file, you can just delete it `~/.config/fish/functions/fisher.fish`.

Or use the built in self-implosion command :)

```
fisher self-uninstall
```

What fisherman version you are running?

> I tried to use it to install nvm wrapper for fish, but no success.

Which one? https://github.com/fisherman/nvm ?

**Comment by padurean** [comment]
I've mentioned the version in the initial description:
> Versions:
> ```
ogg@ogg-machine ~/w/g/P/client-web (master) λ fish --version
fish, version 2.3.1
ogg@ogg-machine ~/w/g/P/client-web (master) λ fisher --version
fisherman version 2.10.0 ~/.config/fish/functions/fisher.fish
```

Yes, that nvm.

**Comment by padurean** [comment]
I've run the `self-uninstall` command (shouldn't this be listed in doc/help? as i didn't saw it mentioned until you said) - it didn't help with the error:

```
ogg@ogg-machine ~/w/g/P/client-web (master) λ fisher self-uninstall
This will permanently remove fisherman from your system.
The following directories and files will be erased:

/Users/ogg/.cache/fisherman
/Users/ogg/.config/fisherman
/Users/ogg/.config/fish/functions/fisher.fish
/Users/ogg/.config/fish/completions/fisher.fish

Continue? [Y/n] 
ogg@Ogg-MacBook-Pro-Bit ~/w/g/P/client-web-seller (master) λ exit

Ogg-MacBook-Pro-Bit:~ ogg$ fish
source: Error encountered while sourcing file '/Users/ogg/.local/share/fisherman/config.fish':
source: No such file or directory
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
ogg@Ogg-MacBook-Pro-Bit ~ λ 
```

**Comment by padurean** [comment]
@bucaran Event if i deleted the function, i still got the error.
I suppose i also need to delete the symlinks:

```
ogg@ogg-machine ~ λ la ~/.config/fish/functions
total 32
drwx------  6 ogg  staff   204B Aug 30 13:25 .
drwx------  9 ogg  staff   306B Aug 30 13:21 ..
lrwxr-xr-x  1 ogg  staff    49B Aug 30 12:09 debug.fish -> /Users/ogg/.config/fisherman/functions/debug.fish
-rw-------  1 ogg  staff   2.7K Apr 28 15:05 fish_prompt.fish
lrwxr-xr-x  1 ogg  staff    48B Aug 30 12:09 spin.fish -> /Users/ogg/.config/fisherman/functions/spin.fish
-rw-r--r--  1 ogg  staff    68B Jan 16  2016 treegg.fish
```

**Comment by padurean** [comment]
Even after deleting those links (`debug.fish` and `spin.fish`) i still get that error when starting fish :( 

```
ogg-machine:~ ogg$ fish
source: Error encountered while sourcing file '/Users/ogg/.local/share/fisherman/config.fish':
source: No such file or directory
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
ogg@ogg-machine ~ λ 
```

**Comment by bucaran** [comment]
@padurean Is there any chance you updated to the latest fisherman from a very old version recently? I'm willing to bet that's the problem.

Check https://github.com/fisherman/fisherman/issues/241

**Comment by bucaran** [comment]
@padurean Could help you on real time if you get on the slack channel.

**Comment by bucaran** [comment]
> source: Error encountered while sourcing file '/Users/ogg/.local/share/fisherman/config.fish':

Ah, yes, this is the problem.

You are/were using the _old_ fisherman, which used to source stuff on startup and other stuff.

Remove all mention of fisherman from your config.fish and install it again with the instructions in the README. Fisherman >=2.0 is a totally different thing.

**Comment by padurean** [comment]
@bucaran thanks - removing the lines from `config.fish` fixed the error.
However, i've reinstalled fisherman as described in _README_ and tried to install `nvm`:

`fisher nvm`

Installation went fine, however i can not really use the nvm wrapper:

```
#bash
ogg-machine:~ ogg$ nvm ls
->       v4.2.4  
         system  
default -> v4.2.4
node -> stable (-> v4.2.4) (default)
stable -> 4.2 (-> v4.2.4) (default)
iojs -> N/A (default)

#fish
ogg-machine:~ ogg$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
ogg@ogg-machine ~ λ fisher ls
bass	 nvm
ogg@Ogg-MacBook-Pro-Bit ~ λ nvm ls
bash: /Users/ogg/.nvm/nvm.sh: No such file or directory
bash: nvm: command not found
exit code: 127
Bass encountered an error!
```

In my `.bash_profile` file i have the following:
```
#nvm settings - OGG
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

`nvm` itself is installed using `brew` and as can be seen from above, works fine in `bash`:

```
#bash
ogg-machine:~ ogg$ brew --prefix nvm
/usr/local/opt/nvm
ogg-machine:~ ogg$ brew ls | grep nvm
nvm
ogg-machine:~ ogg$ nvm --version
0.31.6
```

If this should be solved on the nvm plugin repo/issues, i will close this (just lmk).

Thanks for your help - much obliged! 👍

**Comment by bucaran** [comment]
Glad we sorted this out.

@FabioAntunes can you help @padurean with nvm?

And if everything else fails and you are flexible to try another tool, check out [fnm](console.log(slack.dataStore.users)) or [verman](https://github.com/fisherman/verman/).

**Comment by padurean** [comment]
@bucaran nevermind - i will just use `fnm` - worked straight out of the box! 😄 
Thanks again.
