### ISSUE TITLE
Could we possible have a way to view all 87 plugins as opposed to having to search.

### ISSUE THREAD

**Issue by CrashyBang** [fisherman/fisherman#329]
It is a bit of a pain not being able to view the plugins as sometimes you want to browse to simply improve your workflow.

Cheers,
Otis.

**Comment by bucaran** [comment]
You can use 
```
fisher ls-remote
```
for that.

<img width="1280" alt="screen shot 2016-09-02 at 5 52 21 am" src="https://cloud.githubusercontent.com/assets/8317250/18183909/79dc6d6c-70d1-11e6-9598-19bfa3282d3e.png">

**Comment by CrashyBang** [comment]
Hey @bucaran,

Happy as with that :).

Cheers,
Otis.
