### ISSUE TITLE
Drop into editor command

### ISSUE THREAD

**Issue by CrashyBang** [fisherman/fisherman#330]
I have the following function:

```fish
function edit_cmd --description 'Input command in external editor'
    set -l f (mktemp /tmp/fish.cmd.XXXXXXXX)
    if test -n "$f"
        set -l p (commandline -C)
        commandline -b > $f
        nvim -c 'set ft=fish' $f
        commandline -r (more $f)
        commandline -C $p
        command rm $f
    end
end
```

Which basically drops the current command into neovim, would be cool to have a plugin for this and but maybe use `$EDITOR` instead of hardcoding `vim`/`nvim`?

**Comment by bucaran** [comment]
Sure! I just invited you to join the org. You can create repos and manage your plugins that way if you like.

**Comment by CrashyBang** [comment]
Hey @bucaran,

Okay I will look into setting this up as a plugin over the coming week :).

Cheers.

**Comment by bucaran** [comment]
Sounds good to me :)

**Comment by bucaran** [comment]
Closing in favor of a future PR! Up to you @CrashyBang :)
