### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by rodonn** [fisherman/fisherman#331]
When I try running the example command from the readme
` fisher z fzf edc/bass omf/thefuck`

I get the following error:
Installing 4 plugin/s
! Fetch z github.com/fisherman/z
! Fetch fzf github.com/fisherman/fzf
! Fetch bass github.com/edc/bass
! Fetch thefuck github.com/oh-my-fish/plugin-thefuck
! There was an error installing z or more plugin/s.
Try using a namespace before the plugin name: owner/z

I am using the following software versions:
fisherman version 2.10.0 ~/.config/fish/functions/fisher.fish
fish, version 2.3.0-225-g53e865b
git version 2.8.0.rc3.12.g047057b
Ubuntu 14.04

**Comment by CrashyBang** [comment]
Hey @rodonn,

Just out of curiosity what happens when you run: `fisher ls-remote`?

Cheers,
Otis.

**Comment by bucaran** [comment]
@rodonn Please make sure this is not tied to https://github.com/fisherman/fisherman/issues/327 somehow.

Did you update to 2.10 recently from 1.5 or a very old version. If so, that's the problem! So, you would need to completely remove fisherman and use the new version (which was updated many months and nights ago :P)

**Comment by rodonn** [comment]
Sorry for the false alarm. Doing a clean install of 2.10 fixed the problem.

**Comment by jbucaran** [comment]
Great!

**Comment by steinwelberg** [comment]
I actually have exactly the same issue. If I try to install any plugin it gives me the error below:
```
Installing 1 plugin/s
! Fetch z github.com/fisherman/z
! There was an error installing z or more plugin/s.
Try using a namespace before the plugin name: owner/z
```

I'm running the latest version of Fisherman.

Is there any way to debug the installation process of a plugin? I cannot find out what is going wrong.. Btw it's a fresh install of Fisherman..

Cheers,
Stein

**Comment by steinwelberg** [comment]
Nevermind, I have already fixed it. It apparently had something to do with a tackle script.. After updating those it works fine.

**Comment by jorgebucaran** [comment]
@steinwelberg Interesting. Thanks for reporting it. BTW the `z` package has moved back to its original author (@jethrokuan), therefore the correct name is now `jethrokuan/z`. 

One more thing, keep an eye open for #445. V3 is coming. 👋

**Comment by steinwelberg** [comment]
Thanks for giving me the heads up! I'm looking forward to v3, thanks for the awesome tool! 👍

**Comment by steinwelberg** [comment]
Thanks for the heads up @jorgebucaran. I'm looking forward to v3.

Oh btw, thanks for the awesome tool! 👍
