### ISSUE TITLE
fisherman installs conf.d staff to fish_path, but searches for it in fish_config

### ISSUE THREAD

**Issue by narqo** [fisherman/fisherman#332]
My fish / fisherman setup looks like this: 

I store common configs in the `$HOME/.local/share/fish` directory, so my `$fish_path` is set to it. The main fish config (`$HOME/.config/fish`) depends on a particular machine, and in general, it looks like:

```
# Source the common user config.fish
source $HOME/.local/share/fish/config.fish
```

When I run `fisher <package>`, the package is fetched and installed to `$HOME/.local/share/fish/conf.d`. But it looks like fisher doesn't load these things, as it searches them in `$HOME/.confg/fish/conf.d`.

**Comment by jbucaran** [comment]
@narqo Sorry for the delay with this issue. 

Plugins you install with fisherman are downloaded to `$fisher_config`.

You can use `$fish_path` to customize the location where the downloaded plugins are installed to.

Installing a plugin means traversing the downloaded git repo's directory and copying relevant files to a location that will be automatically picked up by fish.

fish will automatically load functions inside ~/.config/fish/functions and source any files inside ~/.config/fish/conf.d.

By default, `$fish_path` is ~/.config/fish so everything works out of the box. _If you want to use a custom location_, that is, modify `$fish_path`, then you are responsible for loading functions and sourcing stuff inside `$fish_path/conf.d`.

Cheers!
