### ISSUE TITLE
OMF themes that rely on OMF lib

### ISSUE THREAD

**Issue by CrashyBang** [fisherman/fisherman#333]
What do we do when an OMF plugin relies on the [OMF lib](https://github.com/oh-my-fish/oh-my-fish/tree/master/lib)?

I am using the [sushi theme](https://github.com/umayr/theme-sushi) which heavily relies on the `git` functions provided by OMF, have we run into this in the past?

Cheers,
Otis.

**Comment by jbucaran** [comment]
@CrashyBang There are very few plugins that rely on it. One thing that you could do is create a private plugin that exports the required functions and make it a dependency to your theme.

**Comment by CrashyBang** [comment]
Hey @jbucaran,

That's cool, would it be worth while creating a blacklist of OMF plugins (even if it is just in the Wiki/README) that includes a list of any OMF plugins with known issues? 

Cheers.

**Comment by jbucaran** [comment]
A new page in the wiki to list OMF plugins with known issues sounds good to me :)

**Comment by CrashyBang** [comment]
Sweet I will get onto that tonight, can you think of any plugins off the top of your head that I should be adding besides the `sushi` theme.

**Comment by jbucaran** [comment]
Thanks @CrashyBang.

See https://github.com/fisherman/fisherman/issues/46

**Comment by CrashyBang** [comment]
Hey @jbucaran,

Please review new wiki page [here](https://github.com/fisherman/fisherman/wiki/Oh-My-Fish-Plugins---Known-Issues).

Cheers.

**Comment by jbucaran** [comment]
Hey @CrashyBang! Thanks for taking the time :)
