### ISSUE TITLE
What is the correct way to build a plugin?

### ISSUE THREAD

**Issue by Alsan** [fisherman/fisherman#334]
I'm trying to build a simple plugin, and then push to github, and install back with fisher install command. My plugin works as expected immediately after install, but when I open another shell session, it's not loaded as other plugin.

So, what am I miss?

**Comment by jbucaran** [comment]
@Alsan Maybe you are running fish <=2.2.0.

What is your fish --version?

**Comment by Alsan** [comment]
2.2.0，installed from official linuxmint repo

**Comment by jbucaran** [comment]
@Alsan That's what I figured. In order for plugins to be loaded automatically at the start of each session, you need fish >=2.2.3

If you can't update at least to 2.2.3, simply add this piece to your config.fish

```fish
for file in ~/.config/fish/conf.d/*.fish
    source $file
end
```

**Comment by Alsan** [comment]
@bj Thanks for you kindly help, but neither update to the  fish nightly (from launchpad), or source the files under conf.d work for me. I have to move the file which generated by generated by the fishkit and placed in the functions directory of the plugin folder to the root of the plugin folder and symlink that file to ~/.config/fish/conf.d to match up your second solution.

The above steps work for me, but I still think a better documentation and some examples should be introduced to promote the whole ecosystem.

**Comment by Alsan** [comment]
Ok, my bad, I just checkup the version of the fish nightly from launchpad, it's still 2.2.0, and that's why the first solution not work (I think).
