### ISSUE TITLE
Some plugins are not set up correctly

### ISSUE THREAD

**Issue by Shadowigor** [fisherman/fisherman#336]
If I install a plugin I created (https://github.com/Shadowigor/fish-ssh-agent), it doesn't immediately recognize the new function. `fisher ls` lists it, but running it gives me a `fish: Unknown command`. After I run `fisher up`, everything works fine. I have to run `fisher up` for every terminal I open to make it work. For a different plugin I made (https://github.com/Shadowigor/plugin-errno-grep), everything works right away. I cannot see the difference why one would work and the other not. Rebooting and reinstalling don't help.

**Comment by jbucaran** [comment]
Make sure you are running fish 2.3 or superior.

**Comment by Shadowigor** [comment]
I'm running fish 2.3.1.

**Comment by jbucaran** [comment]
I had a look at your plugin.

The reason is that the function name is `ssha` and the file name `ssh-agent.fish`.

They must have the same name.

**Comment by Shadowigor** [comment]
Oh, ok, I didn't know that. Is this written somewhere in the documentation?

**Comment by jbucaran** [comment]
Try the fish docs https://fishshell.com/docs/current/tutorial.html#tut_autoload

It could be more explicit IMO.
