### ISSUE TITLE
local plugin - cannot be installed if there is "space" in path

### ISSUE THREAD

**Issue by chrisduong** [fisherman/fisherman#338]
I'm using **fisher** version 2.10.0.

Fisher failed with this error.

```
❯ fisher "~/Google Drive/my-repos/fisherman/cduong"                                                                226ms
Installing 1 plugin/s
! Fetch Google github.com/~/Google (Drive/my-repos/fisherman/cduong)
! There was an error installing Google or more plugin/s.
Try using a namespace before the plugin name: owner/Google
```

**Comment by chrisduong** [comment]
And one more thing, **local plugin**, does not get updated with command `fisher up`, AND when I add new function in my local plugin, it has not been "autoload". So I have to remove and reinstall the local plugin.

**Comment by jbucaran** [comment]
I am not sure I understand the second comment. `fisher up` updates local plugins. Is that related to the first comment?

**Comment by chrisduong** [comment]
@jbucaran, as in `fisher --help`, it says it update everything, so I thought so.  By the way, it can be discussed later. Thank you.

**Comment by jbucaran** [comment]
@chrisduong Sorry. I wrote that in haste. You are correct, `fisher up` updates everything, including local plugins. Feel free to open an issue for each problem you are having.

Also, notice that if you write

```
 "~/Google Drive/my-repos/fisherman/cduong"         
```

the tilde will not expand to your $HOME directory. I suggest you write instead

```
fisher up "$HOME/Google Drive/my-repos/fisherman/cduong"         
```

Let me know if that works okay.

**Comment by chrisduong** [comment]
@jbucaran, Thanks. You are brilliant.

btw, I don't see **local plugin cduong shown up** when running update. There is some "
usage complaints" but I don't know. There is also no config for "log verbose". :(

```
cduong at cduong13-MacBook-Pro in ~
❯ fisher up                                 11:51
OK fisherman is up to date
Updating 15 plugins
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
! Fetch completions
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
! Fetch cache
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
! Fetch files
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
! Fetch man
OK Latest fin
OK Latest docker-completion
OK Latest last_job_id
OK Latest host_info
OK Latest git_util
OK Latest humanize_duration
OK Latest pwd_is_home
OK Latest pwd_info
Synced 3 symlink/s
Done in 8s 671ms
```

**Comment by jbucaran** [comment]
@chrisduong By the way what is your OS?

```
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
```

**Comment by jbucaran** [comment]
I believe

```
fisher up "$HOME/Google Drive/my-repos/fisherman/cduong"   
```

fixes the issue

> cannot be installed if there is "space" in path

please create new issues for other problems you are having to track this stuff easily. Let's catch all those bugs :)
