### ISSUE TITLE
Post install issues

### ISSUE THREAD

**Issue by askl56** [fisherman/fisherman#339]
Hey all,

Just installed fisherman after resetting all of my fish config. Have a strange error I can't seem to find any documentation on.

After installing, when typing in fisher I get:

``` 
$ fisher
awk: syntax error at source line 2
 context is
	 >>>  <<<
awk: bailing out at source line 14
function: Expected function name
~/.config/fish/functions/fisher.fish (line 18): function $fisher_cmd_name -d "fish plugin manager"
    switch "$FISH_VERSION"
                                                ^
from sourcing file ~/.config/fish/functions/fisher.fish
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'fisher'
# Desktop
$
```

So obviously fisher is not recognised, but then I go to try to install something (as an example, Mono):

``` 
$ fisher mono
fish: Unknown command 'fisher'
```

Any advice would be welcome

**Comment by jbucaran** [comment]
Hi @askl56. What fish version are you using and what is your OS?

**Comment by askl56** [comment]
Hey @jbucaran 

Fish version:

```
fish, version 2.3.1-623-gd35cbb6
```

El Capitan most recent update.

Cheers

**Comment by askl56** [comment]
```
awk version 20121220
```

Ran that command, but with same result.

Config.fish:

```
# Path to Oh My Fish install.
set -q XDG_DATA_HOME
  and set -gx OMF_PATH "$XDG_DATA_HOME/omf"
  or set -gx OMF_PATH "$HOME/.local/share/omf"

# Customize Oh My Fish configuration path.
#set -gx OMF_CONFIG "/Users/andrew/.config/omf"

# Load oh-my-fish configuration.
source $OMF_PATH/init.fish

# RBenv

set -gx RBENV_ROOT /usr/local/var/rbenv
. (rbenv init -|psub)

. "$HOME/.config/fish/functions/aliases.fish"
. "$HOME/.config/fish/functions/utils.fish"
```

**Comment by jbucaran** [comment]
@askl56 What about commenting out everything in your config.fish and trying one more time?

Again, just in case.

If you want live assistance please [join us](https://fisherman-wharf.herokuapp.com/) on slack.

**Comment by jbucaran** [comment]
I wonder is `fisher_cmd_name` is not getting properly set. Can you try

```
echo $fisher_cmd_name
```

and post the result?

**Comment by askl56** [comment]
@jbucaran on Slack now, no response from that command

**Comment by jbucaran** [comment]
@askl56 Fixed by reinstalling awk via brew.
