### ISSUE TITLE
How to add plugins to remote list?

### ISSUE THREAD

**Issue by dideler** [fisherman/fisherman#341]
I'm really excited to see how far fisherman has come. It does a great job representing the ethos of fish and its design laws. So thank you and well done.

I noticed that `ls-remote` only shows plugins that are under the GitHub org for fisherman or oh-my-fish.

How can we, or what is the proposed way, to include community plugins?

If this is still undecided, some ideas to kickstart discussion:
- Repo naming convention (like homebrew's) such as fish-my-plugin or my-plugin.fish
- A public registry such as this one https://github.com/oh-my-fish/db ([context](https://github.com/oh-my-fish/oh-my-fish/pull/427#issuecomment-255602593))*

<sup>*I'm wary of submitting plugins/packages to either fisherman or oh-my-fish as it segregates them between communities.</sup>

**Comment by jbucaran** [comment]
@dideler We would need to host the plugin under the fisherman or omf organization or create a new organization and add its URL to the list of registries fisherman knows about.

In fisherman there is the concept of "registries", essentially GitHub org URLs, and we know two at the moment:

* https://github.com/oh-my-fish
* https://github.com/fisherman

**Comment by jbucaran** [comment]
> I'm wary of submitting plugins/packages to either fisherman or oh-my-fish as it segregates them between communities.

Sure, then your option is to create a new org with your packages and teach the URL to fisherman.
