### ISSUE TITLE
Including test dependencies in fishfile

### ISSUE THREAD

**Issue by dideler** [fisherman/fisherman#342]
When a plugin contains tests that depend on other plugins such as fishtape and mock, should those dependencies be specified in the fishfile?

For distribution, it doesn't seem necessary because fisherman doesn't run tests after installing a plugin. For development however, it would help to include such dependencies, but I wouldn't want them to bloat user installation of the plugin.

Should there be a way to specify test dependencies? For example, [Bundler has groups](http://bundler.io/groups.html). The test group could be ignored when fisherman installs dependencies.

**Comment by jbucaran** [comment]
@dideler 

> When a plugin contains tests that depend on other plugins such as fishtape and mock, should those dependencies be specified in the fishfile?

I'd say no.

> For distribution, it doesn't seem necessary because fisherman doesn't run tests after installing a plugin.

Exactly.

> For development however, it would help to include such dependencies, but I wouldn't want them to bloat user installation of the plugin.

Maybe. If you are testing, you already have fishtape anyway. The other plugin you could possibly want that end users don't care about is mock, so I'd find easier to have mock integrated with fishtape.

**Comment by jbucaran** [comment]
@dideler Just to be clear, just include both deps and dev deps in the fishfile and voila!
