### ISSUE TITLE
Add requirements in README.md

### ISSUE THREAD

**Issue by nagromc** [fisherman/fisherman#344]
Fisherman seems to require [`bc`](https://packages.debian.org/jessie/bc):

```shell
$ fisher ls
env: bc: Aucun fichier ou dossier de ce type
rvm             ssh-agent
$ # Basically, it says that `bc` was not found. On Debian Jessie, I use the following command to install it
$ sudo apt-get install bc
# … successful instalation logs …
$ fisher ls
rvm             ssh-agent
$ # ↑ yay, no error 👍 ↑
```

It may be a good idea to add the requirement installation to README.md for every system (`apt-get` for Debian, `brew` for macOS, etc.)

Related issue: https://github.com/fisherman/fisherman/issues/113#issuecomment-187968096

**Comment by jbucaran** [comment]
@nagromc

Another idea, let's get rid of bc in favor of awk. Awk is definitely required, so it makes sense.

**Comment by jbucaran** [comment]
@nagromc

Another idea, let's get rid of bc in favor of awk. Awk is definitely required, so it would make sense.

**Comment by nagromc** [comment]
Well, do you mean I just need `awk` to be installed on the system, or it's just a memo for you?

At the moment, I do have `awk` pre-installed on my system:

```shell
$ fisher --version 
fisherman version 2.10.0 ~/.config/fish/functions/fisher.fish
$ sudo apt-get remove bc
# … successful uninstalation logs …
$ which awk
/usr/bin/awk
$ fisher ls
env: bc: Aucun fichier ou dossier de ce type
rvm             ssh-agent
$ # oh noes ☹
```

Actually, I've no idea why `bc` is needed.

**Comment by jbucaran** [comment]
@nagromc Sorry for the confusion. What I am saying is I'll cut a new release removing any incidence of `bc` with a functional equivalent using awk. This way fisherman is only dependent in awk.

**Comment by nagromc** [comment]
Great! So I let you close this issue whenever you find it appropriate. To me, it is a now a known bug and I know you'll fix it soon.

Thanks.

**Comment by jbucaran** [comment]
Hi @nagromc. I'm sorry it has taken me forever to answer to this issue properly. `bc` is not really used anywhere in fisherman. But I know that fish's native `math` function uses `bc` under the hood. Do you still have this problem?

**Comment by nagromc** [comment]
That's okay @jbucaran Don't worry about that 😉 

You seem to be right. `bc` is needed by `fish`:

```shell
$ bc --version
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
$ sudo apt-get remove bc
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  rlwrap xsel
Veuillez utiliser « apt-get autoremove » pour les supprimer.
Les paquets suivants seront ENLEVÉS :
  bc fish fish-common
0 mis à jour, 0 nouvellement installés, 3 à enlever et 0 non mis à jour.
Après cette opération, 8 565 ko d'espace disque seront libérés.
Souhaitez-vous continuer ? [O/n] n
Annulation.
$ # basically, it says that `bc` `fish` and `fish-common` will be removed
$ math "3.14*2"
6.28
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

Those are the logs from a "real" Debian Jessie 8.7. I think my mistake comes from using [Raspbian](https://www.raspbian.org/) where I installed `fish` manually -- the version I needed not being available on the repo at the moment I stumbled upon the issue.

Thanks for your time.
