### ISSUE TITLE
git.io/fisher-up-me 404 not-found

### ISSUE THREAD

**Issue by aristidesfl** [fisherman/fisherman#347]
http://git.io/fisher-up-me

**Comment by jbucaran** [comment]
@aristidesfl Unfortunately the link is not available anymore. I think it may be somewhere buried in the fisherman's Slack history.

It's been more than half a year since it was relevant though. What problem are you having?

**Comment by aristidesfl** [comment]
```
$ fisher --version
fisher version 1.3.1
```

**Comment by jbucaran** [comment]
@aristidesfl Current version is 2.10.0! Before you try to update, remove fisherman $fisher_home and $fisher_config, and remove whatever mention to fisherman from your config.fish.

Then install using the procedure in the README and you should be okay.

**Comment by aristidesfl** [comment]
It works, thanks!
