### ISSUE TITLE
Can't change main/right prompt independently

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#348]
See https://github.com/fisherman/index/pull/86

**Comment by maxelewis** [comment]
ok.   contact me here : emma45314.@gmail.com

**Comment by jbucaran** [comment]
@laughedelic Thanks.

**Comment by jbucaran** [comment]
Why do you want to change the right prompt independently? Is there a plugin that only uses a right prompt?

**Comment by aristidesfl** [comment]
fisherman/done was using the right prompt, but now using the post and pre exec hooks

**Comment by jbucaran** [comment]
@aristidesfl You mean, only the right prompt, and no (left) fish_prompt.fish file. Correct?

**Comment by aristidesfl** [comment]
Correct
