### ISSUE TITLE
Make onboarding even easier

### ISSUE THREAD

**Issue by cmarqu** [fisherman/fisherman#349]
Hi,

fresh fish and fisherman user here. Both fish+fisherman work nicely out of the box (thanks very much!). However, there is one thing that could be improved IMO.

Here is my story:
* installed fish, played around with ``fish_config`` and customized color theme and prompt, also set my terminal's background color
* discovered fisherman, installed it without problem, liked the way it provided me with things to try initially
* installed another theme through ``fisher``
* liked my original prompt better than all the packaged ones
* didn't find an easy way to restore my prompt from before fisherman

So, my suggestion would be to (automatically) create a local fisherman theme from the non-fisherman config at the first start of fisherman that can be restored if needed. 
The theme could e.g. be named ``<username>_<timestamp>``.

**Comment by jbucaran** [comment]
@cmarqu Hi there. That's possible, but first let me clarify something. 

> didn't find an easy way to restore my prompt from before fisherman

Did you try uninstalling the plugin? 

```
fisher uninstall :plugin
```

That should restore your prompt to whatever it was before.

If that's not the actual behavior, we have a bug then.

**Comment by cmarqu** [comment]
When I do ``fisher uninstall mono``, the mono prompt is gone, but fish is now running with a different prompt (is this the default one?: ``maq3rt@rt-x1su11-4 ~/tools/bin>``). When I then exit fish and start it again, *then* I have my own custom prompt back.

**Comment by jbucaran** [comment]
@cmarqu Thanks! I will try to repro this and get back to you.

**Comment by jbucaran** [comment]
@cmarqu Hi after a long time. When you uninstall a prompt, fisherman will restore your previous prompt, and if there was not one will use fish default prompt. 

How does fisherman know what is your previous prompt? If your previous prompt was in ~/.config/fish/functions/fish_prompt.fish, it will make a copy of that file that it can restore later.
