### ISSUE TITLE
Allow using a GitHub API token to allow greater number of API requests

### ISSUE THREAD

**Issue by patresi** [fisherman/fisherman#350]
Using fisher in a corporate environment is almost impossible because GitHub blocks requests to the API originating from the same IP.

Brew gets around this by using [an environment variable](https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L181:L186). I'm proposing that something like this is implemented for fisher

**Comment by jbucaran** [comment]
@patresi Good news! You can export the GITHUB_USER and GITHUB_TOKEN environment variables, to prevent GitHub's search API from rejecting anonymous requests.

```fish
set -x GITHUB_USER your_username
set -x GITHUB_TOKEN your_github_api_token_for_fisherman
```
