### ISSUE TITLE
files in conf.d get sourced twice

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/fisherman#354]
Does fisherman handle conf.d files in a different way from vanilla fish?

I'm trying to add a warning to the `fzf` plugin, but it seems that the warning gets printed out twice.

In `conf.d/__fzf_warnings.fish`:

```
if not set -q fzfwarning1
    printf "IMPORTANT: the default keybindings for fzf have been changed.\n"
    printf "This especially affects existing users.\n"
    printf "Please read the README at https://github.com/fisherman/fzf for more details.\n"
    printf "Once understood, enter:\n"
    printf "\t\tset -U fzfwarning1 0\n"
    printf "to remove this warning.\n"
end
```
results in:

```
IMPORTANT: the default keybindings for fzf have been changed.
This especially affects existing users.
Please read the README at https://github.com/fisherman/fzf for more details.
Once understood, enter:
		set -U fzfwarning1 0
to remove this warning.
IMPORTANT: the default keybindings for fzf have been changed.
This especially affects existing users.
Please read the README at https://github.com/fisherman/fzf for more details.
Once understood, enter:
		set -U fzfwarning1 0
to remove this warning.
```

**Comment by jbucaran** [comment]
@jethrokuan What fzf branch?

**Comment by jethrokuan** [comment]
@jbucaran have yet to push it up, will give you one in a sec.

**Comment by jethrokuan** [comment]
https://github.com/fisherman/fzf/tree/dev/keybindings

**Comment by jbucaran** [comment]
@jethrokuan Does it happen on every new shell?

**Comment by jethrokuan** [comment]
Yes, it does. Ideally I wouldn't need to do this. Rather invasive changes are being made to the keybindings of fzf, and I'd like for current users to know about them (https://github.com/fisherman/fzf/issues/22). Can you think of a better way?

**Comment by jbucaran** [comment]
@jethrokuan I mean, does the message get printed twice on every new shell?

I can't repro this after installing from /dev/keybindings. It works as expected, that is, it gets printed only once.

Try commenting `__fzf_install` and see what you get. Maybe is something inside `__fzf_install.fish`.

**Comment by jbucaran** [comment]
@jethrokuan Maybe this is a `await`? I recall it needs to create a subshell to do its thing. The problem could be solved by not using `await` or not bootstraping yourself via conf.d, but lazily, i.e, the first time the user tries to interact with fzf.

**Comment by jethrokuan** [comment]
@jbucaran yeah, this is likely me spawning another shell instance and printing the output in the current shell. I've decided against the whole warning thing anyway; it caused  troubles for fzf reads.
