### ISSUE TITLE
Need info on how to develop a plugin locally. 

### ISSUE THREAD

**Issue by milkypostman** [fisherman/fisherman#357]
I cannot tell from the docs how one would go about developing a plugin or theme locally. More info would be appreciated.

**Comment by jbucaran** [comment]
@milkypostman You are right, the README only explains how to use fisherman. A tutorial would serve this project more.

In the meantime, here you go. 

**Developing a plugin / theme (it's the same thing) locally**:

* Create directory for my_plugin
```sh
 $ mkdir -p path/to/my_plugin
```

* Edit my_plugin.fish file
```sh
 $ cat > path/to/my_plugin/my_plugin.fish
function my_plugin
  echo "hello, world"
end
```

* Install my_plugin
```sh
 $ fisher path/to/my_plugin                                                                                          
Installing path/to/my_plugin 
```

* Test it works
```sh
 $ my_plugin 
hello, world
```

<img width="614" alt="screen shot 2017-01-06 at 0 47 09" src="https://cloud.githubusercontent.com/assets/56996/21686733/bc7f7412-d3a9-11e6-8947-5af0d2aefd33.png">

**Comment by jbucaran** [comment]
<img width="614" alt="screen shot 2017-01-06 at 0 47 09" src="https://cloud.githubusercontent.com/assets/56996/21686733/bc7f7412-d3a9-11e6-8947-5af0d2aefd33.png">

**Comment by iquabius** [comment]
I have a related question:

I'm starting fresh with Fisherman, and I'm wondering which files should I track with git. I know I should track the `fishfile`, but what about my custom functions, completions, and etc. Placing them at the `completions/` and `functions/` directories under `~/.config/fish/` doesn't seem a good idea, since they are full of Fisherman's stuff.

One idea is to make everything a fisherman plugin, and placing them at `~/.config/fish/fisher_plugins/`. That way it seems easier to track.

Any input is appreciated.

**Comment by jbucaran** [comment]
@iquabius This question does not have a clear-cut answer, but I can tell you how I do it. 

Make your custom functions, themes and snippets into plugins. You can then publish those plugins and share them with everyone else.

If sharing is not an option, turn them into local plugins. Like you said, create a directory, anywhere is fine: ~/Code/fish and put each one of your local plugins in it. 

What if you want to keep it private, but still want an option to publish over the network? You can always use a private git URL, but to make things simpler, fisherman supports installing from gists too.

I hope this helps.

**Comment by iquabius** [comment]
It sure helps. Thank you!

**Comment by jbucaran** [comment]
@milkypostman There's still no "official" guide to develop plugins locally, other than what I posted there above, but we'll get there soon. In the meantime, I've been working on a cookbook for fish. Perhaps you'll find that useful.

* https://github.com/jbucaran/fish-shell-cookbook

**Comment by edouard-lopez** [comment]
closing as question has been anwered.

@jbucaran  I created a wiki pages from your post [Developing a plugin or themes locally](https://github.com/fisherman/fisherman/wiki/Developing-a-plugin-or-themes-locally).

**Comment by jbucaran** [comment]
Thanks @edouard-lopez! 🙏
