### ISSUE TITLE
fisher ls error

### ISSUE THREAD

**Issue by predmijat** [fisherman/fisherman#359]
Hi,

`fisher ls` returns:
```
test returned eval errors:
	invalid integer ''
```

`fisher ls-remote` is working ok. `fisher up` updated plugins.

`fish -v` - `fish, version 2.5.0`
`fisher -v` - `fisherman version 2.11.0 ~/.config/fish/functions/fisher.fish`

I have some customizations of the theme I'm using (budspencer), some symlinked directories, but it would be kinda hard to give you info on all that :)

If I can provide something specific to help you help me with this, please ask :)

**Comment by jbucaran** [comment]
@predmijat Fixed! Thanks for reporting.
