### ISSUE TITLE
`fisher install shark scaffold reported wrong index

### ISSUE THREAD

**Issue by kballard** [fisherman/fisherman#36]
After running `fisher search` to see the available projects, I tried running `fisher install shark scaffold` and it reported the wrong indexes:

```
kevin@Erebor ~> fisher install shark scaffold
Installing (2 of 2) >> shark
Installing (3 of 2) >> scaffold
fisher: Repository not found: 'https://github.com/bucaran/fish-scaffold'
Aye! 1 plugin/s installed in 3s
```

fish-scaffold also doesn't seem to exist, but that's a different issue.

**Comment by kballard** [comment]
`fisher uninstall` is even worse:

```
kevin@Erebor ~> fisher uninstall shark scaffold
Uninstalling (3 of 2) >> shark
Uninstalling (4 of 2) >> scaffold
Aye! 2 plugin/s uninstalled in 0s
```

**Comment by bucaran** [comment]
Hi @kballard! 

Thanks. That's a bug I introduced by swapping the lines. I like shorter lines before longer lines. But that totally changed the meaning of the code!

Alos, the other plugins are not available yet! I will publish them as soon as I am done with [0.4.0](https://github.com/fisherman/fisherman/labels).
