### ISSUE TITLE
Where do you find plugins?

### ISSUE THREAD

**Issue by seemsindie** [fisherman/fisherman#360]
Just a simple question, where do you find plugins, do you have some sort of registry or a repo?

**Comment by sotayamashita** [comment]
Here you are. https://fisherman.github.io/

**Comment by laughedelic** [comment]
And that search is powered on this index: https://github.com/fisherman/index (where you can add your own plugins). Plus you can just browse the https://github.com/fisherman org.

**Comment by seemsindie** [comment]
@sotayamashita thanks man
