### ISSUE TITLE
Fisherman 2.11.0 and 2.12.0 not tagged

### ISSUE THREAD

**Issue by nathankleyn** [fisherman/fisherman#370]
The releases of Fisherman 2.11.0 and 2.12.0 were not tagged in Git. I would like to submit a PR to bump the homebrew tap (https://github.com/fisherman/homebrew-tap) but it's not very nice to do that without the tag (would have to use the commit SHA instead).

AFAICT, the tags should be the following:

* **2.11.0** -> 56e80d2
* **2.12.0** -> ab6442e

**Comment by gyakovlev** [comment]
hey, thanks for reporting.
I was waiting for someone to do it but realized I have access =)
tagged.

**Comment by jbucaran** [comment]
@nathankleyn @gyakovlev Thank you! 🙇
