### ISSUE TITLE
Installation should also initialize submodules

### ISSUE THREAD

**Issue by mgee** [fisherman/fisherman#373]
If a plugin or prompt theme contains a submodule it is currently not initialized by fisherman upon installation. The initialization of the submodule has to be done manually in the repository cloned by fisherman.

It would be nice if fisherman automatically initializes the submodules or clones the plugin/prompt with the git option `--recursive`.

An example of an affected prompt is [slimfish](https://github.com/mgee/slimfish) which currently needs extra installation steps.

**Comment by jbucaran** [comment]
Hi @mgee, fisherman already has a dependency mechanism based in fishfiles. 

But, should we introduce yet another way?

**Comment by mgee** [comment]
Hi @jbucaran I was using a submodule and not a dependency since the submodule refers to a python script and not a fish plugin. But maybe that distinction is unnecessary since fisherman can handle this as well.

I just tested it with a dependency in the fishfile instead of a submodule and it works very well. This is an even better solution. Thanks!

**Comment by jbucaran** [comment]
@mgee Glad it works out for you. Keep us posted! 👍
