### ISSUE TITLE
(empty) fishfile necessary to install own plugins ?

### ISSUE THREAD

**Issue by plgruener** [fisherman/fisherman#376]
I wanted to move my custom fish-aliases to a local plugin, so I created a directory

my-aliases/
+ functions/
    + alias1.fish
    + alias2.fish

Now running `fisher my-aliases` threw 'no plugins to install or dependencies missing'.
However, adding an empty `fishfile` to my-aliases solved this.
Is this intended ? (there are plugins without fishfile) Or is there a better way to manage my custom functions (across several computers) ?

**Comment by jbucaran** [comment]
@plgruener What's inside alias1.fish and alias2.fish?

Can you share the contents inside those files?

**Comment by plgruener** [comment]
sure, most of them are very simple, like
```
> cat my-aliases/functions/gc.fish
function gc
  git commit -v $argv
end
```
and
```
> cat my-aliases/functions/g.fish
function g -d "run `git status` or `git <args>`"
  if test 0 -eq (count $argv)
    git stat
  else
    git $argv
  end
end
```

**Comment by jbucaran** [comment]
@plgruener This is odd then, those files looks correct; the file name matches the function name. I don't understand what is the problem?

How I can I repro this?

**Comment by plgruener** [comment]
I'm sorry, I could not reproduce this myself; when I try now everything works as it should. Thanks for your help :)

**Comment by jbucaran** [comment]
@plgruener No probs, if you encounter this behavior again, let us know! 👋
