### ISSUE TITLE
How do you backup and restore your plugins?

### ISSUE THREAD

**Issue by martinffx** [fisherman/fisherman#377]
Is there a to backup and restore your fisherman plugins? kinda like bundler or pip but for all your neat fish plugins. 

So you can keep your shell aligned across environments?

**Comment by jbucaran** [comment]
@martinffx You could commit your [fishfile](https://github.com/fisherman/fisherman#what-is-a-fishfile-and-how-do-i-use-it) to your dotfiles and run `fisher` or `fisher install` to get everything in it installed again on a fresh system.

**Comment by jbucaran** [comment]
@martinffx Did the above solve your issue?
