### ISSUE TITLE
color choices make reading text hard on white/light themes

### ISSUE THREAD

**Issue by balupton** [fisherman/fisherman#378]
pretty much impossible for me to read that `1` and `OK`

<img width="283" alt="screen shot 2017-04-13 at 6 31 18 am" src="https://cloud.githubusercontent.com/assets/61148/24982212/d88baa4e-2012-11e7-9f0c-8e8ac91bf1c6.png">

proposed change:

- if a dark color was used as a background, also set the color of the text to a light color

currently it seems it is assumed the text color is light (that the user is using a dark theme) so there is no need to set the text color when a dark background color is set

**Comment by jbucaran** [comment]
> if a dark color was used as a background, also set the color of the text to a light color

Is there a way to query the console for this info?

**Comment by edouard-lopez** [comment]
It's a bit better with [`pure` theme](https://github.com/rafaelrinaldi/pure) (I'm a maintainer) with [base16-konsole](https://github.com/cskeeters/base16-konsole/) but it's still difficult to read:
![selection_039](https://cloud.githubusercontent.com/assets/1212392/25000232/d4aa5050-2040-11e7-9969-054fcb6c4986.png)

**Comment by jbucaran** [comment]
@balupton Unfortunately this is difficult to solve because **AFIK** there is not way to query the console/terminal to tell you the current background color.

**Comment by balupton** [comment]
from my understanding, the 1st (index 0) ansi colour is meant to be dark and the 8th (index 7) ansi colour is meant to light - however dark themes inverse this

**Comment by Markcial** [comment]
Actually there is a way to check all the session properties, but it is very hacky, is via configuration settings for linux and via osascript for mac.

I have to still dig on a linux box for the linux solution, but for mac would be with this applescript if the console is the iterm2

```shell
tell application "iTerm"
	tell current window
		tell current session
			get background color
		end tell
	end tell
end tell
```

and this one if is a standard terminal

```shell
tell application "Terminal"
	tell startup settings
		get background color
	end tell
end tell
```

**Comment by jbucaran** [comment]
@Markcial This is incredible Mark!

**Comment by balupton** [comment]
Seems the answers on https://unix.stackexchange.com/q/245378/50703 are also a good resource

**Comment by Markcial** [comment]
Maybe we should create a plugin for this. 

We can add ways to dig for the foreground and background saturations and set environment vars to:  
  * LIGHT_FG_SATURATION: when the font color has a saturation lower than the 40%
  * MID_FG_SATURATION: when the font color has a saturation in between 40% and 60%
  * HIGH_FG_SATURATION: when the font color has a saturation higher than the 60%
  * LIGHT_BG_SATURATION: when the background color has a saturation lower than the 40%
  * MID_BG_SATURATION: when the background color has a saturation in between the 40% and 60%
  * HIGH_BG_SATURATION: when the background color has a saturation higher than the 60%
  * BACKGROUND_HAS_IMAGE: when the terminal uses any image as background
  * BACKGROUND_OPACITY: with the value of the opacity set to the terminal background

Those environment vars are a draft and unprefixed, but i start the debate with that.

The ways to dig can be includes that people can write to help outperform the plugin, when there is no way to guess the information from the terminal we must think about a way to pointing up people to the plugin and how to collaborate to get their terminals, displays or emulators to give this information via a include or configuration for the plugin, i already posted the ones for iterm2 and terminal for mac, maybe we can work out more generic configurations like XTERM or so.

**But** the plugin should be optional, fisherman should have no dependencies, once the plugin is installed it helps with the theme setup setting light or dark foreground colors depending on the terminal saturation and background colors based on the font  saturation too.

Without the plugin the actual behaviour should apply

**Comment by balupton** [comment]
whatever you guys think is best

**Comment by jbucaran** [comment]
@balupton My console's background is white too, so I could certainly use this. My current theme is https://github.com/fisherman/boss btw.

**Comment by jbucaran** [comment]
@Markcial I am going to close here since I don't think this has a reasonable solution.
