### ISSUE TITLE
error after running fish_prompt

### ISSUE THREAD

**Issue by lee2sman** [fisherman/fisherman#379]
I launched ```fish_prompt``` and chose a different prompt. THen immediately after I get these errors. (note, for below, i ran ```fisher -v``` which is how first line came up.

any suggestions for what to do? uninstall fisher? fisherman? i tried reinstalling but still got stuck.

```
fisherman version 2.12.0 ~/.config/fish/functions/fisher.fish
fish: Unknown command 'git_branch_name'
~/.config/fish/functions/fish_prompt.fish (line 1): git_branch_name
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'segment'
~/.config/fish/functions/fish_prompt.fish (line 66):     segment "$root" $root_color
                                                         ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'segment_close'
~/.config/fish/functions/fish_prompt.fish (line 68):     segment_close
                                                         ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

**Comment by lee2sman** [comment]
if i remove fish_prompt.fish from my functions then instead i get the following error:

```
source: Error encountered while sourcing file '/Users/2sman/.local/share/fisherman/config.fish':
source: No such file or directory
```

**Comment by jbucaran** [comment]
@lee2sman Try uninstalling all plugins `fisher ls | fisher rm`, but if you could make a step by step sequence that would help repro this, it would be helpful.

I was just able to install a theme, use fish_prompt to switch to another theme, then install another theme on top, uninstall it, and it was okay.

**Comment by lee2sman** [comment]
Thanks for getting back to me so fast.

running ```fisher ls | fisher rm``` unfortunately doesn't solve the issue. I still get the following error message:
```
fish: Unknown command 'git_branch_name'
~/.config/fish/functions/fish_prompt.fish (line 1): git_branch_name
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'segment'
~/.config/fish/functions/fish_prompt.fish (line 66):     segment "$root" $root_color
                                                         ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'segment_close'
~/.config/fish/functions/fish_prompt.fish (line 68):     segment_close
                                                         ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

This whole thing started after i launched ```fish_prompt```. After I had selected a prompt, that's when the errors started.

**Comment by lee2sman** [comment]
step by step to reproduce this (sorry i can't be more detailed)

1. already have been using fisherman for a year or two. so far so good!
2. today i ran ```fish_prompt```, chose a prompt in the gui/browser, and saved, and quit. then got the following error.

you should know that i keep my fish functions in a dotfiles, which i'm wondering if that's related to getting these errors.

**Comment by jbucaran** [comment]
@lee2sman It seems fish_prompt is "corrupted" or fisherman can't get at it for some reason. After you run `fisher ls | fisher rm` all plugins should have been uninstalled, but it seems that didn't happen.

What's inside your fishfile?

**Comment by lee2sman** [comment]
Hmmm.
Here's what's in my fishfile.

```
spin
debug
segment
git-branch-name
git-is-repo
git-is-dirty
git-is-staged
git-is-touched
git-is-stashed
git-is-empty
git_util
```

**Comment by jbucaran** [comment]
@lee2sman Wow, it seems you're being hit by the rename from git-function-name to git_function_name that happened more than a year ago! 😲 

Let's remove:

```
git-branch-name
git-is-repo
git-is-dirty
git-is-staged
git-is-touched
git-is-stashed
git-is-empty
```

from your fishfile first.

**Comment by lee2sman** [comment]
you're right. my fish_prompt is wiped out. i just checked, empty file.

**Comment by lee2sman** [comment]
i removed the git-* things from fishfile

**Comment by jbucaran** [comment]
@lee2sman BTW, if your fish_prompt is empty, then previous fish_prompt function must be loaded in the session, so try opening a new session.

**Comment by lee2sman** [comment]
relaunching doesn't help. 

how do i totally remove fisherman? and then reinstall?

**Comment by lee2sman** [comment]
oh i see, relaunching does work. it loads the following in my fish_prompt.fish

```
function fish_prompt
	set -l status_copy $status
    set -l cwd
    set -l root_color ffc magenta
    set -l root (set_color -o)"  ̸ "(set_color normal)

    switch "$PWD"
        case "$HOME"\*
            set root_color ffc green
            set root (set_color -o)" ~ "(set_color normal)
    end

    set cwd (echo "$PWD" | sed -E "s|$HOME/?||")

    set -l base (basename $cwd)

    switch "$cwd"
        case "" /
        case \*
            segment " $base " black fc0
    end

    set branch_name

    if set branch_name (git_branch_name)
        set -l color black ffc
        set -l repo_status
        set -l padding
        set -l branch_ref ➦

        if git symbolic-ref HEAD ^ /dev/null > /dev/null
            set padding " "
            set color ffc magenta
            set branch_ref 
        end

        if git_is_touched
            set color black ffc
            set padding

            if git_is_staged
                set repo_status "✚ "
            end

            if git_is_dirty
                set repo_status "✦ "
            end

        else if git_is_empty
            set repo_status "● "

        else if git_is_stashed
            set repo_status "•• "
        end

        segment "$padding$branch_ref $branch_name $repo_status" $color
    end

    set -l dir (dirname $cwd | sed -E 's|(^/)?([^/.])[^/]*|\2|g')

    switch "$dir"
        case "" / .
        case \*
            segment " $dir " black ffc
    end

    segment "$root" $root_color

    segment_close
end
```

**Comment by jbucaran** [comment]
If you want to completely remove fisherman, try `fisher self-uninstall`, it's fun!

But don't think that will solve the problem.

**Comment by lee2sman** [comment]
haha, it is fun. but you're right, i still get the exact same errors.

**Comment by lee2sman** [comment]
for fun, i also uninstalled fish and reinstalled. at startup i get these errors:

```
source: Error encountered while sourcing file '/Users/2sman/.local/share/fisherman/config.fish':
source: No such file or directory
```
and then the whole error message above that starts with ```fish: Unknown command 'git_branch_name'```

**Comment by jbucaran** [comment]
You said in https://github.com/fisherman/fisherman/issues/379#issuecomment-294382714 that the contents of your fish_prompt is that, so the problem is obviously fish is running the wrong fish_prompt.

What's the contents inside ~/.config/fish/functions?

**Comment by jbucaran** [comment]
@lee2sman What's in /Users/2sman/.local/share/fisherman/config.fish?

**Comment by lee2sman** [comment]
very ineresting, there is no config.fish there. a guess, maybe i was symlinking from dotfiles and that got removed?

for previous question, all my functions are there in the ~/.config/fish/functions directory.

thanks for sticking with me! :)

**Comment by lee2sman** [comment]
[here](https://github.com/lee2sman/dotfiles/blob/master/fish/config.fish)'s my dotfiles' config.fish

**Comment by jbucaran** [comment]
@lee2sman 

Are you completely sure this is good?

```
set fisher_home ~/.local/share/fisherman
set fisher_config ~/.config/fisherman
```

I ask because fisherman _requires no configuration_, but it used to (like 2 years ago) so if you are an old-timer you may have never heard about it.

**Comment by lee2sman** [comment]
i've been using fish maybe 2 years or more.
hmmm.
i just commented out those two lines and now my terminal hangs on launch.

**Comment by jbucaran** [comment]
BTW there's a Slack room, which you are welcome to join for real-time support! :P

**Comment by lee2sman** [comment]
haha, that would be great. where is that?

**Comment by jbucaran** [comment]
https://fisherman-wharf.herokuapp.com/
