### ISSUE TITLE
Downloading plugins gives error (behind Proxy)

### ISSUE THREAD

**Issue by bertdecock** [fisherman/fisherman#382]
I'm running fish and fisher in Cygwin behind a proxy, and when I try to install a plugin (z for example), I get the following response.
```
fisher z
Installing 1 plugin/s
z github.com/fisherman/z
! There was an error installing z or more plugin/s.
Try using a namespace before the plugin name: owner/z
```
I set the HTTP_PROXY and HTTPS_PROXY env variables.

Any idea if this can be solved, or if it even is related to being behind a proxy?

Thanks,
Bert

**Comment by jbucaran** [comment]
@bertdecock 🤔 I'm not sure if it has anything to do with that, but I bet it is.

How do HTTP_PROXY and HTTPS_PROXY work?

**Comment by bertdecock** [comment]
Shell commands like curl can use these environment variables to use proxy settings. As far as I know there are 4 of these variables: HTTP_PROXY, HTTPS_PROXY, FTP_PROXY and ALL_PROXY. In my environment, curl didn't work until I set ALL_PROXY to the correct value.

I've played around with them a bit they don't seem to impact the result I get with Fisherman.

**Comment by jbucaran** [comment]
Thanks @bertdecock! If you are completely sure the problem is in your environment, feel free to close, otherwise leave it open and do report back if you find out anything else.

**Comment by bertdecock** [comment]
Update: the issue is related to Cygwin. I use a virtual machine Linux now with the same proxy setup and fisherman works like a charm there!

**Comment by jbucaran** [comment]
@b4b4r07 Thanks for the update! 👍
