### ISSUE TITLE
Unknown command 'isatty'

### ISSUE THREAD

**Issue by imsus** [fisherman/fisherman#386]
### Environment
**Fish version**: 2.6.0 (install via brew macos sierra 10.12.5)
**Fisherman version**: 2.12.0

### How to Repro:
**Type**: `fisher u`

**Expected**: Fisherman updates all plugins

**Error output**:
```
fish: Unknown command 'isatty'
~/.config/fish/functions/fisher.fish (line 247):             if isatty
                                                                ^
in function 'fisher'
	called on standard input
	with parameter list 'u'
```

**Comment by jbucaran** [comment]
Just upgraded to fish 2.6 and tried `fisher u` and all was good.

**Comment by jbucaran** [comment]
<img width="1280" alt="screen shot 2017-06-05 at 22 20 11" src="https://cloud.githubusercontent.com/assets/56996/26785418/3110722c-4a3d-11e7-9a66-b9f751bcbd04.png">

**Comment by jbucaran** [comment]
@imsus Please make sure you were not a victim of #241. 😅

**Comment by imsus** [comment]
Reinstalling fisherman (removing all folders related to fisherman) fix the problem.
