### ISSUE TITLE
Wrong source command printed when warning

### ISSUE THREAD

**Issue by igrep** [fisherman/fisherman#389]
```
> fish --version
fish, version 2.2.0

> fisher -v
You need fish 2.3.0 or higher to take advantage of snippets.
Without it some plugins might not work.

Refer to your package manager documentation
for instructions on how to upgrade your fish build.

If you can not upgrade, append the following code
to your ~/.config/fish/config.fish:

for file in ~/.config/fish/conf.d/*.fish
        source
end

fisherman version 2.12.0 ~/.config/fish/functions/fisher.fish
```

The warning message above seems wrong:
The `source` command should be fed with `"$file"` argument.
I'm new to fish shell, so it was a bit confusing...

**Comment by jbucaran** [comment]
@igrep Whoops, you are totally right.

- https://github.com/fisherman/fisherman/blob/master/fisher.fish#L50

To fix this, just add a backslash before `$file` like this `\$file`.

Do you want to send a PR?

**Comment by igrep** [comment]
Okay, let me make my contribution map more green! 😏
