### ISSUE TITLE
`fisher --list` lists uninstalled plugins

### ISSUE THREAD

**Issue by kballard** [fisherman/fisherman#39]
After uninstalling a plugin, `fisher --list` continues to list the plugin. It may still be in the cache (though is there any point to caching uninstalled plugins?), and `fisher --list` is documented as reporting what's in the cache, but really that command is only useful if it lists the actual installed plugins.

**Comment by bucaran** [comment]
Right. Install/Uninstall basically enables or disables the plugin. 

If you uninstall the plugin you don't want to remove it from the cache before the user may be uninstalling to mean "disable this", rather than remove.

This was decided early on. I thought about adding `fisher enable/disable`, but then you end up with more commands that also need documentation and their own function and I figured it was neater to keep everything simple in one command.

**Comment by kballard** [comment]
With the way things are now, there appears to be no way to find out what plugins are "enabled".

Also, `fisher install shark` actually does almost 2 seconds of work, which if it's just enabling an already-downloaded plugin, you'd think it would be faster. It makes me think that it's possibly re-downloading.

Although, when I watch my Terminal window title bar, I'm actually seeing Terminal report that a lot of that time is spent running the `sleep` utility, which seems pretty weird.

**Comment by bucaran** [comment]
Correct. There is no way to find out which plugins are enabled right now.

No. It's not re-downloading. It's updating the index. As you may have noticed already or not, the index, which is just a plain text record database is not in this repository, but [here](https://github.com/fisherman/fisher-index) (you could customize that btw, but I doubt anyone would in the near future as the official index is, well the "official" index).

**Comment by bucaran** [comment]
EDIT: I do want a mechanism to know which plugins are enabled/disabled though. That's obviously useful and the usage is already planned.

``
fisher --list=enabled | disabled | ...
```

**Comment by kballard** [comment]
I think it makes sense to position `fisher --list` as a plumbing command suitable for use by scripts, so maybe it could do something like list all enabled plugins first with a `*` prefix (to mean installed) and then all disabled plugins with a space prefix (so it lines up with installed ones), e.g.

```
> fisher --list
*shark
 scaffold
```

And then you can introduce a separate `fisher list` that's intended for human-readable output. By default it would list just enabled plugins, but would also support specifying one or more of `enabled`, `disabled`, `index`, or `all` (where `all` is the same thing as `enabled disabled index`). This command would also update the index by default if it's printing the index, but it could have a `--no-update-index` flag to disable that. Examples:

```
> fisher list
Enabled plugins:
  shark - Sparkline Generator
  scaffold - Scaffold out a fish plugin
```

```
> fisher list enabled disabled
Enabled plugins:
  shark - Sparkline Generator
  scaffold - Scaffold out a fish plugin
Disabled plugins:
  fishtape - TAP producer and test harness for fish
  submit - Submit a plugin to the Fisherman Index
```

```
> fisher list all
Enabled plugins:
  shark - Sparkline Generator
  scaffold - Scaffold out a fish plugin
Disabled plugins:
  fishtape - TAP producer and test harness for fish
  submit - Submit a plugin to the Fisherman Index
Available plugins;
  get - Press any key to continue
  bobthefish - A Powerline-style, Git-aware fish theme optimized for awesome
```

When running `fisher list index` without both `enabled` and `disabled`, the Available plugins section should list any plugins not printed in any other displayed section. This means that disabled plugins show up as Available if not otherwise shown, and enabled plugins would also show up but perhaps with an "(installed)" note if not otherwise displayed. For example:

```
> fisher list enabled index
Enabled plugins:
  shark - Sparkline Generator
  scaffold - Scaffold out a fish plugin
Available plugins:
  fishtape - TAP producer and test harness for fish
  get - Press any key to continue
  submit - Submit a plugin to the Fisherman Index
  bobthefish - A Powerline-style, Git-aware fish theme optimized for awesome
```

```
> fisher list disabled index
Disabled plugins:
  fishtape - TAP producer and test harness for fish
  submit - Submit a plugin to the Fisherman Index
Available plugins:
  shark (installed) - Sparkline Generator
  scaffold (installed) - Scaffold out a fish plugin
  get - Press any key to continue
  bobthefish - A Powerline-style, Git-aware fish theme optimized for awesome
```

```
> fisher list index
Available plugins;
  fishtape - TAP producer and test harness for fish
  shark (installed) - Sparkline Generator
  scaffold (installed) - Scaffold out a fish plugin
  get - Press any key to continue
  submit - Submit a plugin to the Fisherman Index
  bobthefish - A Powerline-style, Git-aware fish theme optimized for awesome
```

**Comment by kballard** [comment]
To clarify: I'm in favor of supporting `fisher --list=enabled | disabled | index` as well. When printing just one type, no need for `*`/space prefixes. Although in that case, I'm not sure if there's any point in having `fisher --list` show disabled plugins and prefixes at all, it might make more sense just to treat `fisher --list` the same as `fisher --list=enabled`. Also, `fisher --list=index` shouldn't update the index (since this is a plumbing command, it should just return the existing info; maybe a separate plumbing command `fisher --update-index` if the script calling it wants to trigger an index update, and possibly `fisher --update-index --show-progress` to have fisher print the spinner).

**Comment by bucaran** [comment]
> Although, when I watch my Terminal window title bar, I'm actually seeing Terminal report that a lot of that time is spent running the sleep utility, which seems pretty weird.

Maybe `wait` is waiting too much _too_.

Thoughts:

* Make --quiet bypass the wait altogether. I should have done this from the beginning :sweat: 
* The `*` is definitely coming soon :smile: 
* Separate the current `fisher update --index` to `__fisher_update_index`, since that is an intentionally private function anyway.


I'll address the rest of the issues later.

**Comment by bucaran** [comment]
@kballard 

Added the following extensions to `fisher --list` to query local plugins:

```
fisher -l | --list=<category>

fisher -l enabled
fisher -l disabled
fisher -l cache
```

And like you suggested I am using these for internal operations that need to be fast, like auto-complete. This gained us quite the speed improvement (tested with all the existing omf and wahoo themes and plugins).

I could easily add `fisher --list=remote` too, but I am not sure if we want it.

**Comment by bucaran** [comment]
I think we are mostly done here, closing in favor of #49.
