### ISSUE TITLE
fisher.fish completion always installed into wrong folder

### ISSUE THREAD

**Issue by externl** [fisherman/fisherman#391]
I keep my fisherman install in a separate folder from my user config. In my `config.fish` I have:

```
set fish_path (dirname (status -f))/fisherman
set fish_function_path $fish_path/functions $fish_function_path
set fish_complete_path $fish_path/completions $fish_complete_path
for file in $fish_path/conf.d/*.fish
    source $file
end
```

Everything is installed into the correct location except for the fisher.fish completion. It's installed to `~/.config/fish/completions/fisher.fish`, instead of `~/.config/fish/fisherman/completions/fisher.fish` like everything else.

**Comment by jbucaran** [comment]
@externl I don't understand your config.fish. Why don't you let fisher to put stuff in the default fish_function/complete_path?

**Comment by jbucaran** [comment]
@externl The line we want to edit is [here](https://github.com/fisherman/fisherman/blob/d2db99402367810dfc666d7d204fd24ad6d6ac17/fisher.fish#L120).

**Comment by externl** [comment]
@jbucaran Fisher installs too much stuff into the functions folder. I have many other functions in there that I've written, it's painful to maintain them while having to sift through the fisher installed ones.

**Comment by jbucaran** [comment]
@externl Yes, I can understand some people feel that way. For that reason, there is $fish_path.

**Comment by externl** [comment]
Ah, I did not think fisher was updating these values.

**Comment by jbucaran** [comment]
@externl Fisherman will put stuff into fish fish_function/complete_path by default (but it doesn't update or touch their values). 

You can opt out this behavior by setting $fish_path. If you do so, fisherman will put stuff under $fish_path/{functions,complete}, etc., which is what you probably need.

**Comment by externl** [comment]
@jbucaran. That's what I'm doing. See my first message.

The issue is that fisher installs one file (fisher.fish completion) into the wrong location. It should be in `$fish_path/completions`, but it's not.

**Comment by externl** [comment]
So, after staring that this I realized I was not exporting `fish_path`.

**Comment by externl** [comment]
Actually, I was mistaken to close this issue. There is a bug.

In https://github.com/fisherman/fisherman/blob/d2db99402367810dfc666d7d204fd24ad6d6ac17/fisher.fish#L120, 

```
set -l completions "$fish_config/completions/$fisher_cmd_name.fish"
```

`$fish_config` is incorrect. This should be `$fish_path`.

**Comment by jbucaran** [comment]
@externl Then we should replace all `$fish_config`s with `$fish_path`. 🤔 

If you want you can make the change and test if things still work as expected.

**Comment by externl** [comment]
Sure, will do.

**Comment by externl** [comment]
Fixed with https://github.com/fisherman/fisherman/issues/391

**Comment by greenie** [comment]
Apologies for re-opening an old issue, but I think what I'm experiencing is relevant to some of the changes made here.

I'm using `fish_path` to seperate out fisherman from non-fisherman functions and completions. In my `~/.config/fish/config.fish` file I have the following:

```
set -U fish_path ~/.config/fish/fisherman

for file in $fish_path/conf.d/*.fish
  builtin source $file ^/dev/null
end

set fish_function_path $fish_path/functions $fish_function_path
set fish_complete_path $fish_path/completions $fish_complete_path
```

This all works fine, except for when I run `fisher up`. Fisherman always puts `fisher.fish` into `~/.config/fish/completions` instead of `$fish_path/completions`. Is this the correct behaviour, or does `__fisher_self_update` need changing to take `$fish_path` into account if set?

**Comment by JorgeBucaran** [comment]
@greenie Hmm IIRC fisherman always tries to install itself globally, regardless of fish_path, which is preferred for installing plugins/themes. Then came along @externl and fixed it with the correct behavior. So, maybe completions was not taken into account? It should not be too hard to debug yourself? 🤔

**Comment by greenie** [comment]
Thanks @JorgeBucaran. At a glance, I believe that it's because `__fisher_self_update` is referencing `$fish_config` instead of `$fish_path`. I'm happy to take a look and open a new PR if that fixes the problem.

**Comment by JorgeBucaran** [comment]
@greenie That'd be awesome! 🎉
