### ISSUE TITLE
Installing with homebrew

### ISSUE THREAD

**Issue by Dorian** [fisherman/fisherman#393]
e.g. doing `brew install fisherman`

https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

I'm not sure how complicated this would be.

**Comment by jbucaran** [comment]
@Dorian IIRC you can install fisherman via brew, but it is not recommended. The same way you install brew manually using a script, you should install fisherman manually. Fortunately, the process is simple. Copy `fisher.fish` and put it into your ~/.config/fish/functions. That's it. 😄

**Comment by Dorian** [comment]
It's not in homebrew-core, but in a separate tap: https://github.com/fisherman/homebrew-tap/blob/master/fisherman.rb

**Comment by jbucaran** [comment]
Yes, I should've posted the link! Whoops. 😅 

If if it works for you then fine.

BTW if you installed fisherman using the recommended procedure and then what to uninstall, you can run `fisher self-uninstall`. 😉 

Alright, is it okay to close here?

**Comment by Dorian** [comment]
I opened a pull request on homebrew-core, you got 2300+ stars, should be more than enough to quality

**Comment by jbucaran** [comment]
@Dorian That's awesome! Can you take care of that? I can help if you need help, but I am not well versed in the arts of brew.
