### ISSUE TITLE
How do I uninstall fisherman?

### ISSUE THREAD

**Issue by wgordon17** [fisherman/fisherman#396]
I'm having issues running `fisher up` as well as installing any plugins. Fisherman just shows the spinner and nothing happens. I would to uninstall and reinstall to see if that resolves the issue, but I'm unsure of specifically how to do that.

Thanks!

**Comment by jbucaran** [comment]
@wgordon17 Did you install fisherman possibly around 2 years ago? If so, you may have inadvertently upgraded to the current version from a much ancient and broken version. This is not a problem nowadays, but it may be the problem you are having.

See https://github.com/fisherman/fisherman/issues/241.

---

**Comment by jbucaran** [comment]
There is a new command `fisher self-uninstall`, try that too. 👋

**Comment by javatarz** [comment]
This command is now `fisher remove jorgebucaran/fisher` if I've understood usage correctly.

**Comment by jorgebucaran** [comment]
Documented [here](https://github.com/jorgebucaran/fisher#removing-plugins).

**Comment by jorgebucaran** [comment]
[More documentation here](https://github.com/jorgebucaran/fisher#removing-plugins).

**Comment by jorgebucaran** [comment]
More documentation [here](https://github.com/jorgebucaran/fisher#removing-plugins).
