### ISSUE TITLE
ls-remote doesn't work

### ISSUE THREAD

**Issue by sanyer** [fisherman/fisherman#399]
Issuing `fisher ls-remote` keeps showing this:
```
! I could not update the remote index.
...
```

I've tried running `curl -u$GITHUB_USER:$GITHUB_TOKEN -Is "https://api.github.com/orgs/fisherman/repos?per_page=100"` from the fisher.fish and it returns `HTTP/1.1 200 OK`. So, apparently it's not an issue with api.github.com.

Don't know much more as not sure how to properly debug function `__fisher_remote_index_update`.

**Comment by jbucaran** [comment]
Can you try again? It's extremely difficult to debug this because I can't repro it.

<img width="1280" alt="screen shot 2017-09-05 at 18 15 32" src="https://user-images.githubusercontent.com/56996/30054190-3cd238c2-9266-11e7-935a-ceda5004f87a.png">

**Comment by sanyer** [comment]
Doesn't help, same result.
I was mostly wondering if there is an official way to debug. If not, then maybe I can run this function line by line and see what breaks.

**Comment by jbucaran** [comment]
@sanyer Hmm. Yeah, there is no official way to debug at the moment. 😄

**Comment by zazazack** [comment]
Was having same issue. `fisher ls-remote` was only listing `omf/<plugin>`'s. 

I deleted `~/.config/fin` and `~/.config/omf` and now `fisher ls-remote` appears to be working properly again. I have no idea why that would be the case, but whatevs, it's working.

**Comment by sanyer** [comment]
Found a reason.
Lines 1169, 1173, 1177 have an extra space in regex.
After removing it and adjusting substr length everything started working.
Also added some debug with debug plugin.

**Comment by JorgeBucaran** [comment]
@sanyer Could you send a PR with that please? 👍

**Comment by sanyer** [comment]
Yeah, sure.

**Comment by yyyc514** [comment]
Confirming this is still a problem and the fix of the regex seems to be the correct solution.

**Comment by jorgebucaran** [comment]
Where is the PR? @sanyer

**Comment by bondmike** [comment]
Nice post,i want to play with you .Please contact me at.:
annalisa13763.@gmail.com . i hope you are real..

**Comment by sanyer** [comment]
@jorgebucaran I've reinstalled my mac completely recently. But I have a backup of my user folder still. I'll check tomorrow :-)

**Comment by bondmike** [comment]
Nice post,i want to play with you .Please contact me at.:
nighthookup9.@gmail.com . i hope you are real..

**Comment by sanyer** [comment]
@jorgebucaran https://github.com/fisherman/fisherman/pull/412
