### ISSUE TITLE
`fisher uninstall` is happy to uninstall already-uninstalled plugins

### ISSUE THREAD

**Issue by kballard** [fisherman/fisherman#40]
If you install a plugin, then uninstall it, you can repeat the `fisher uninstall pluginname` command as many times as you like and it continues to "uninstall" it. I think this is because uninstalling leaves the plugin in the cache, and `fisher uninstall` is happy to "uninstall" anything in the cache.

```
kevin@Erebor ~> fisher install shark
Installing >> shark
Aye! 1 plugin/s installed in 1s
kevin@Erebor ~> fisher uninstall shark
Uninstalling >> shark
Aye! 1 plugin/s uninstalled in 0s
kevin@Erebor ~> fisher uninstall shark
Uninstalling >> shark
Aye! 1 plugin/s uninstalled in 0s
```

**Comment by bucaran** [comment]
Good catch. That's because it is just passing through in its way to disable the plugin.

It should not say anything because it is already disabled.

Related #39
