### ISSUE TITLE
fisher command not found

### ISSUE THREAD

**Issue by tastyminerals** [fisherman/fisherman#402]
I have installed **fisher** via a package manager, however only **fisher-me-up** is available after installation. 
```bash
$ fisher-up-me 
Erasing old fisherman's functions.
Erasing old fisherman's variables.


Seems like we made it cap!
If you have questions or found any issues:
http://join.fisherman.sh
  or
github.com/fisherman/fisherman/issues

fisherman version 2.8.0 $__fish_datadir/functions/fisher.fish

Usage: fisher [COMMAND] [PLUGINS]

where COMMAND is one of:
      install (default)
      update
      rm
      ls (or ls-remote [--format=FORMAT])
      help
```
Typing `fisher` complains `command not found`.  I tried using the installation instructions provided here but the result is the same.

**Comment by JorgeBucaran** [comment]
@tastyminerals The recommended way to install fisherman is described in the README. It consists in putting a single file `fisher.fish` inside any of your fish functions directory.

What do the `fisher-up-me` instructions say? :)

**Comment by tastyminerals** [comment]
I don't understand. What is the recommended way if the #Install section clearly says `curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher` and this is what I did.

**Comment by tastyminerals** [comment]
Ok, I have uninstalled **fisherman** package which installs `fisher-up-me` script and  did `curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher`. However, I still cannot use `fisher`.

**Comment by JorgeBucaran** [comment]
@tastyminerals Then there must be a problem with your system or you must have some unconventional fish configuration where ~/.config/fish/functions is not part of your `$fish_function_path`. etc.

There is really no science to installing fisherman. It's literally a single function.

**Comment by tastyminerals** [comment]
Meaning that if I install **fish** from git repo following official instructions and then use your **fisher** script, everything should work, unless there is something odd with my bash config.

**Comment by JorgeBucaran** [comment]
@tastyminerals Yes, but I am sure we can fix this with your current configuration too. Where do you save your `.fish` files / functions?

**Comment by tastyminerals** [comment]
I have removed my `.fish` dir because I thought it might be the cause. Now, I have only `fish` executable installed via package manager. I previously installed `oh-my-fish` which was giving me warnings whenever I entered a git dir just fyi.

**Comment by JorgeBucaran** [comment]
@tastyminerals Run this:

```
echo $fish_function_path
```

to find out what your function directories are.

**Comment by JorgeBucaran** [comment]
@tastyminerals 

> fish_function_path is not set, echo $fish_function_path returns nothing.

Now we know your issue is not related to fisherman. You'll need to fix your installation or install fish again.

I have put together instructions on how to install fish [here](https://github.com/JorgeBucaran/fish-shell-cookbook#how-to-install-fish). You should be able to install fisherman after you figure that out.

**Comment by jorgebucaran** [comment]
Possibly related: https://github.com/jorgebucaran/fisher/issues/476
