### ISSUE TITLE
Auto-install fisherman when functions not present

### ISSUE THREAD

**Issue by enricobacis** [fisherman/fisherman#420]
At the moment I'm using this snippet to auto-install fisherman if it is not present in the system:

```
# fisherman
if not functions -q fisher; eval (curl -sfL https://git.io/fisher-install); end
```

It's good because when moving to another system I just drop in my dotfiles and it downloads the new version for me, without the need of adding the old version to my dotfiles.

If you like the idea, it would probably be better to move the file directly in the repository and then generate a new git.io link and use that one instead of the one to my gist.

**Comment by jorgebucaran** [comment]
Thanks for sharing that snippet. It seems like everything that was needed to say here was said, so I'm closing.

**Comment by plainas** [comment]
Can't this be added to the readme?

**Comment by jorgebucaran** [comment]
@plainas https://github.com/fisherman/fisherman/blob/master/README.md#bootstrap
