### ISSUE TITLE
Saving to dotfiles

### ISSUE THREAD

**Issue by patrickf3139** [fisherman/fisherman#424]
Hi if I want to save the state of my fisherman into my dotfiles so that on a new machine, what do you guys recommend I include in the dotfiles and what to leave out? My initial guess is to include my `fishfile` and leave out everything else?

**Comment by amir20** [comment]
I currently do just that. I try to mostly use default settings with many plugins. I also use stow utility create symlinks. 

Sent via my iPhone

**Comment by patrickf3139** [comment]
I also see this file `config/fish/functions/fisher.fish.1527910129`. It's completely empty. What's it for and should I check it in?

**Comment by jethrokuan** [comment]
yes, just the `fishfile` is sufficient. Running `fisher` after symlinking the `fishfile` in the correct place will download the listed plugins.
