### ISSUE TITLE
When you try to install a plugin you already have, exit code is 0

### ISSUE THREAD

**Issue by BarbzYHOOL** [fisherman/fisherman#426]
Is it normal?

Shouldn't it be something more appropriate (>=2) ?

This is causing me troubles when automating the installation but since it's new for me, I wasn't sure where the issue lied so I wasted several hours to find a workaround :D

**Comment by amir20** [comment]
Maybe I don't get your point, but if you already have a plugin then a return code of `0` means it was successful as it didn't have to do anything. Why would you expect it to be different? 

> This is causing me troubles when automating the installation but since it's new for me, I wasn't sure where the issue lied so I wasted several hours to find a workaround :D

Why do you need a workaround? Why can't you just move on to the next plugin? If it's already installed, then there isn't anything that needs to be done.

**Comment by BarbzYHOOL** [comment]
"Why would you expect it to be different?"

because it didn't install a plugin, it told me the plugin is already there, that's rather different to me but I don't know the convention on exit codes at all so I just asked ^^

At first I supposed that the error codes were meant to describe errors but also warnings

**Comment by amir20** [comment]
Think about what needs to happen after the command is done. You would expect the plugin to be there. If it is already installed then do nothing because after the command is done, it is in the state you expect it to be. IMO installing plugins should be idempotent. Like doing a `PUT`, I'd expect it to make the change and not complain if the change has already been made.

**Comment by BarbzYHOOL** [comment]
I don't know, are all exit code above 1 = a complaint/an error?

**Comment by amir20** [comment]
I looked at other package managers. `pip` and `brew` return 0 when the package is already installed. So I'd say it's safe to assume this is consistent behavior.

**Comment by patrickf3139** [comment]
This concept of being able to install or do something repeatedly and have the same result as running it once is so prevalent in the computer software world that there's a term for it: idempotency. So, I'd say leaving the exit code as success is right call.
