### ISSUE TITLE
After install, typing "fisher" = permission denied

### ISSUE THREAD

**Issue by BarbzYHOOL** [fisherman/fisherman#430]
```
An error occurred while redirecting file '/dev/stderr'
open: Permission denied

```

And the fisher.fish file in /functions/ is set to the right owner (the user)

**Comment by jorgebucaran** [comment]
@gyakovlev Is this related to https://github.com/fisherman/fisherman/pull/416?

**Comment by gyakovlev** [comment]
@jorgebucaran have no idea.
technically it should not be the reason as the only thing we did is change the notation. no direct reference of `/dev/stderr`, just `^` -> `>2` change.

more likely this one is used and fails somewhere.
https://github.com/fisherman/fisherman/blob/0a5e188764b630a8c4b6ce03f000d06830fb6e30/fisher.fish#L69-L76

it would be helpful if @BarbzYHOOL provided a bit more information about the system.
on my system (linux):

```sh
ls -la /dev/stderr 
lrwxrwxrwx 1 root root 15 Jul  2 19:54 /dev/stderr -> /proc/self/fd/2

ls -la /proc/self/fd/2 
lrwx------ 1 ya ya 64 Jul  3 23:44 /proc/self/fd/2 -> /dev/pts/5
```
and everything works.

**Comment by BarbzYHOOL** [comment]
Hmm sorry, I don't remember how it happened. It was on a debian 9 but I kept installing, uninstalling with ansible. I probably did some shit that makes it a very rare case, but it still happened and I had no idea how to fix it.

Also it was in a LXC container.

**Comment by jorgebucaran** [comment]
Haha okay, no point in keeping this open then. 😄

**Comment by BarbzYHOOL** [comment]
still can be useful if someone gets the issue one day

ARGH :P
