### ISSUE TITLE
Error with some omf theme asking for namespace

### ISSUE THREAD

**Issue by sanjibukai** [fisherman/fisherman#431]
Hi,
When I try to install the [*cmorrell* theme](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#cmorrell) I got the following error:

> Installing 1 plugin/s
! Fetch cmorrell github.com/oh-my-fish/theme-cmorrell
! There was an error installing cmorrell or more plugin/s.
Try using a namespace before the plugin name: owner/cmorrell

**Comment by gyakovlev** [comment]
Hi

```fish
fisher omf/theme-cmorrell.com
```
```fish
Installing 1 plugin/s
OK Fetch cmorrell.com github.com/oh-my-fish/theme-cmorrell.com
Backup fish_prompt.fish
Done in 517ms
```

works fine here.
check `fisher ls-remote` output to see the plugin names.
