### ISSUE TITLE
Use # as keybinding not possible

### ISSUE THREAD

**Issue by w1k1n9cc** [fisherman/fisherman#441]
Take a look at oh-my-fish/theme-budspencer#38. This is an annyoing bug but I think the fix should be quite easy. It should be enough to ignore # inside of " " or ' '.

**Comment by jorgebucaran** [comment]
If the fix is quite please send me a PR. Thanks! 👋

**Comment by jorgebucaran** [comment]
Should be fixed with key bindings support now re-implemented in [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉
