### ISSUE TITLE
Inconsistent order in `fish_user_key_bindings` from `fisher` and `fisher up`

### ISSUE THREAD

**Issue by alexbepple** [fisherman/fisherman#444]
`fisher bang-bang; and fisher pisces; and fisher fzy`

results in this order of key bindings:

`less functions/fish_user_key_bindings.fish | grep '#' | uniq | sed s/###//g | string trim`

> bang-bang
> pisces
> fzy

`fisher up` after that – seemingly reproducibly – creates a different order:

> bang-bang
> fzy
> pisces

I would expect `fisher up` to keep the original order.

**Comment by alexbepple** [comment]
More generally, I think that the order in `fish_user_key_bindings` should be independent of the order of installation, i.e. a pure function of the set of the installed plugins.

**Comment by jorgebucaran** [comment]
👋 Hi, @alexbepple. I'm going to remove this feature. See: #443.

**Comment by alexbepple** [comment]
You opened #443 like more of a discussion. But I get your point, @jorgebucaran.

**Comment by jorgebucaran** [comment]
This is a bug, so your creating this issue is perfectly valid, but see my point about key bindings in https://github.com/fisherman/fisherman/issues/443#issuecomment-419751882.
