### ISSUE TITLE
Check all oh-my-fish plugins and themes.

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#46]
## Plugins
* List should be updated soon.

## Themes

Everything works except the following plugins:

+ theme-dangerous
	quited messed up, code is long, buggy and extremely slow theme.

+ theme-technopagan
	missing function `moonmoji`?

* theme-cor
	missing emoji clock dependecy

+ theme-syl20bnr
	fish: Unknown command 'pstree'	

+ post-Wahoo themes
	require the omf (available after 0.4.0) 

### Buggy Themes

+ theme-bobthefish
	incorrectly declaring __toaster_* variables 

+ theme-toaster
	incorrectly declaring __toaster_* variables

+ theme-ocean
	incorretly declaring variables __oceanfish_* variables

These themes work just fine, but they require a shell restart, which is completely unecessary, slow and evaluates completions again. The problem is these themes use global variables for glyphs, etc., and declare them incorrectly without the `-g` flag. The [fix is simple](https://github.com/oh-my-fish/theme-bobthefish/pull/19) and would also add compatibility to _fundle_, but the oh-my-fish folks refuse to fix the bug.

#### Options

* ~~Fork these plugins and fix them.~~
* Create a plugin that fixes these kind of buggy themes. :+1: 

Related:
* https://github.com/fisherman/fisherman/issues/4
* https://github.com/oh-my-fish/oh-my-fish/issues/223
*  https://github.com/oh-my-fish/theme-bobthefish/pull/19
* https://github.com/oh-my-fish/theme-bobthefish/issues/18

**Comment by fishequality** [comment]
https://github.com/oh-my-fish/oh-my-fish/issues/225
https://github.com/oh-my-fish/oh-my-fish/issues/3
https://github.com/oh-my-fish/oh-my-fish/issues/10
https://github.com/oh-my-fish/oh-my-fish/issues/10
https://github.com/oh-my-fish/oh-my-fish/issues/12
https://github.com/oh-my-fish/oh-my-fish/issues/47
https://github.com/oh-my-fish/oh-my-fish/issues/57
https://github.com/oh-my-fish/oh-my-fish/issues/136
https://github.com/oh-my-fish/oh-my-fish/issues/167
https://github.com/oh-my-fish/oh-my-fish/issues/183
https://github.com/oh-my-fish/oh-my-fish/issues/185
https://github.com/oh-my-fish/oh-my-fish/issues/186
https://github.com/oh-my-fish/oh-my-fish/issues/189
https://github.com/oh-my-fish/oh-my-fish/issues/191
https://github.com/oh-my-fish/oh-my-fish/issues/196
https://github.com/oh-my-fish/oh-my-fish/issues/196
https://github.com/oh-my-fish/oh-my-fish/issues/201
https://github.com/oh-my-fish/oh-my-fish/issues/202
https://github.com/oh-my-fish/oh-my-fish/issues/208
https://github.com/oh-my-fish/oh-my-fish/issues/211
https://github.com/oh-my-fish/oh-my-fish/issues/212
https://github.com/oh-my-fish/oh-my-fish/issues/225
