### ISSUE TITLE
make failes

### ISSUE THREAD

**Issue by Fiedzia** [fisherman/fisherman#48]
mdziardziel@PC-076 ~/g/fisherman> make
Adding configuration to ~/.config/fish/config.fish
Downloading the index for the first time...
fish: Could not expand string “"$$spinners"”
/home/mdziardziel/git/fisherman/functions/wait.fish (line 68):             set spinners "$$spinners"
                                                                                        ^
in function “wait”,
        called on line 72 of file “/home/mdziardziel/git/fisherman/functions/fisher_update.fish”,
        with parameter list “--spin=pipe --log=/home/mdziardziel/.config/fisherman/cache/.debug_log 
                curl --max-time 5 -sS https://raw.githubusercontent.com/fisherman/fisher-index/master/INDEX > /home/mdziardziel/.config/fisherman/cache/.index.tmp
            ”

in function “fisher_update”,
        called on standard input,
        with parameter list “--index”

fisher: Connection timeout. Try again.
Ahoy! Reset your shell and type 'fisher <command>'
read: Unknown option “alias”
/home/mdziardziel/git/fisherman/functions/fisher.fish (line 2): while read -la alias
                                                                ^
in function “fisher”,
        called on standard input,
        with parameter list “help -a”

       read - read - read line of input into variables

**Comment by bucaran** [comment]
@Fiedzia 

Hi. What is your fish-shell version?

**Comment by Fiedzia** [comment]
mdziardziel@PC-076 ~/g/fisherman> fish --version
fish, version 2.1.1

**Comment by bucaran** [comment]
_This is a fish-shell_ version problem, one fix that comes to mind is extracting the index update logic to a `__fisher_update_index` and call this directly in the part where make downloads the index for the first time. There is no need to show the progress indicator there (in fact I think you can't even see it, so it's useless).

**Comment by Fiedzia** [comment]
Ok, upgrading fish helped.

**Comment by bucaran** [comment]
@Fiedzia Good to know. I will still ship a simple fix for those non-2.2.0 users (there are some I guess) in the next milestone so I'll have this open for now.

**Comment by bucaran** [comment]
Closing in favor of #50.
