### ISSUE TITLE
link to quickstart broken on index

### ISSUE THREAD

**Issue by Haroenv** [fisherman/fisherman#52]

**Comment by jwulf** [comment]
Points to: https://github.com/fisherman/fisherman/blob/master/man/man7/fisher-tour-tour.md

Should be: https://github.com/fisherman/fisherman/blob/master/man/man7/fisher-tour.md

**Comment by bucaran** [comment]
@Haroenv @jwulf Thanks! Will fix right away.

**Comment by bucaran** [comment]
:+1:
