### ISSUE TITLE
Add a code of conduct!

### ISSUE THREAD

**Issue by josegonzalez** [fisherman/fisherman#6]
You probably don't want yet another file in your repo, but I promise this one is good for like 95% of everyone (the other 5% is busy looking at cat pictures).

I've used the [contributor covenant](http://contributor-covenant.org/version/1/3/0/) in the past, it's pretty easy to read and understand (and translated into a few languages [here](http://contributor-covenant.org/)). Pick the one you like though :)

**Comment by bucaran** [comment]
:+1: Thanks for the link, that seems like a worthy addition to the repo actually. 

Added to the next milestone.

**Comment by bucaran** [comment]
Thanks! @josegonzalez

**Comment by josegonzalez** [comment]
:)
