### ISSUE TITLE
Fish crashes after installing ilancosman/tide

### ISSUE THREAD

**Issue by rchavezj** [fisherman/fisherman#682]
![Screenshot_2](https://user-images.githubusercontent.com/10482151/137048395-6636a1bb-0ae2-49e3-b968-56aafcfc97b4.png)

This prompt happens to all of my laptop/desktop computers inside of Garuda Linux fish shell terminal.

**Comment by jorgebucaran** [comment]
Can you answers the other questions?

Please comment out your config.fish and try again. Does that solve your problem?

Also, you seem to be using Starship? You can't use two prompts.

**Comment by rchavezj** [comment]
fish, version 3.2.1

and fisher plugins I currently have
jorgebucaran/nvm.fish@2.1.0
jorgebucaran/fisher
ilancosman/tide

**Comment by jorgebucaran** [comment]
If the problem only happens with Tide, maybe this is not a Fisher issue. 

Did you open an issue there yet?

**Comment by rchavezj** [comment]
https://github.com/IlanCosman/tide/issues/210

**Comment by rchavezj** [comment]
So I cleaned up the config and updated fish. Taking care of both fixed my problem. :)

I think it was a combination of both because I tested them separately. Much appreciated!
