### ISSUE TITLE
What is the advantage over Oh My Fish?

### ISSUE THREAD

**Issue by beckclib** [fisherman/fisherman#69]
Looks very professional and all, but I have been using Oh my Fish! more or less and now I found this.

Why should I change to Fisherman and what are the advantages over Oh my Fish?

**Comment by bucaran** [comment]
I have been meaning to write a nice explanation [here](https://github.com/fisherman/fisherman/wiki/Why-Fisherman%3F), but had no time actually coding Fisherman. I'll get around to it eventually.

In the mean time here are the main reasons:


1. Fisherman supports Tacklebox, Oh My Fish! and Wahoo plugins / themes. In addition, it extends the plugin system to support more complex plugins like [Fishtape](https://github.com/fisherman/fishtape). Oh My Fish! can only install plugins using Oh My Fish! limited model.

2. Fisherman performs better. The full [benchmarks](https://github.com/fisherman/fisherman/wiki/Performance) are not ready, but Oh My Fish! slow shell start is almost half a second when you start using > 5 plugins.

3. Fisherman has excellent key bindings support. Your plugins can distribute key bindings without risk of conflict with other plugin's (unless they override the _same_ binding Fisherman will merge them correctly).

4. Fisherman has excellent test coverage, we currently have ~300 tests. Most of them unit tests and more than a handful _feature_ tests. Oh My Fish! has *no* tests.

5. Fisherman has a more powerful toolset. Two examples: `getopts` and `wait`. The first one allows plugins as well as Fisherman's own commands to behave **fast** and parse arguments correctly as you would expect if you use a UNIX-like operating system. The second, provides a dynamic spinner that lets you create richer UIs using progress bars, and several other spinner types, etc.

6. Fisherman's index is [outside](https://github.com/fisherman/fisher-index/blob/master/INDEX) of this repository. We don't need to fear the build will break just to merge a plugin submission. In addition, while Oh My Fish! plugins only provide a `name` an `url`, the Fisherman index is much richer with the following fields: name, url, description, any number of tags and author. This information can be easily queries using `fisher search`. There is nothing even comparable in OMF.

7. Fisherman's output is smarter. We use `*` next to a plugin's name to indicate whether the plugin is installed or not. Then a `>` indicates whether it is a theme and a `|` if it is a symbolic link, which leads me to...

8. Fisherman allows you to install plugins that are simply local directories. Similar to `npm link` if you are familiar with that command. Fisherman makes it even simpler by checking whether the plugin is a local directory in which case it installs the plugin contained in that directory as a symbolic link. This means development of plugins is incredibly fast. No need to reset the shell as you change your linked functions, etc.

9. Last, but not least. Documentation. Oh My Fish! has poor documentation. Fisherman has extensive documentation, tutorials, casts, a QuickStart guide and installation guides even for Fish. And more help is on the way. All of this docs you can access both online in the Wiki or at the terminal using `fisher help` based in `man(1)` pages like a any respectable program should do.

Other Points

* The index is always up to date, and you don't need to update it as you always have the "latest" whenever you search anything with `fisher search`. It's more complicated and there is a timeout to avoid updaing the index too many times (as that would be pointless).

* A cache. This means among other things that you can enable/disable plugins offline.

* We have a cool [home page](http://fisherman.sh/).

* This is only the beginning. I have not been able to take care of the plugin ecosystem yet as I have been busy with the system itself.

**Comment by bucaran** [comment]
I am unable to comment in the OMF repo, but I just want to tell @oranja that competion is the mother of invention. I also want to remind him that Fisherman is also, obviously free and open source and wait for it, done just for fun too. I would also like to remind @oranja about [this](https://github.com/oh-my-fish/oh-my-fish/commit/2693a2fd18bd92a439f4d74b10513922d92120f7) and hopefuly hear whether he has an opinion on that or not.

**Comment by bucaran** [comment]
<img width="771" alt="screen shot 2016-02-04 at 8 01 43 pm" src="https://cloud.githubusercontent.com/assets/8317250/12813246/24e7e9dc-cb7a-11e5-8ca9-b734289445a6.png">

**Comment by oranja** [comment]
1. There's no need to remind me about competition. I am all for a freedom of choice. I only mentioned Fisherman once, and that was to encourage people to actually use Fisherman. I really don't see why you feel the need to remind me stuff.
2. I have some criticism as well, but you chose to go on your way and I don't have the time to work on two frameworks. It really doesn't help to my motivation to help when all I see here is "OMF is bad" written over and over again in a myriad of creative ways. Frankly I don't know how you find the time to point out each and every OMF issue and still maintain Fisherman all by yourself, but I admire your skills, because you do a fine job.
3. Look, I'm pretty new to Fish and Oh-My-Fish. I know the people who are there now and my impression is that they are all very open and friendly. If you're going to keep bringing up the Wahoo merge, you're going to have to explain why I never once heard anything positive about it, and why you're now banned from Oh-My-Fish.
4. I'm really hoping that this is the closest we're ever getting to a flame war. Do whatever you want, antagonize OMF as much as you want, and good luck.

**Comment by bucaran** [comment]
> I really don't see why you feel the need to remind me stuff.

Fair enough.

> I have some criticism as well

Would love to hear that. Fisherman is still not half way to 1.0 and there is room for improvement.

> If you're going to keep bringing up the Wahoo merge, you're going to have to explain why I never once heard anything positive about it, and

Of course you have heard nothing about it. It was shortlived and merged (replaced is the right word) with Oh My Fish! after 2 or 3 months. 

> why you're now banned from Oh-My-Fish.

That exlains why I can't post any comments or send PRs.

**Comment by derekstavis** [comment]
>That exlains why I can't post any comments or send PRs.

You are banned because I have asked you in a friendly way to stop advertising Fisherman inside Oh My Fish repositories, and you, with your childish behaviour haven't stopped, so you got blocked organisation-wide.

Also, I wanted to say that I've noticed you created a handful of fake users to reference Fisherman inside Oh My Fish and to cause confusion, manipulating comments, with the innocent idea that the internet doesn't see what you do. You have a history of comment manipulation, showing, one more time, how you do childish competition. You also have *violated people's privacy* hardly, grabbing e-mail addresses from Oh My Fish Slack/Github and spamming people about Fisherman.

I have been scraping every move and documenting it. Github support are informed about your moves and we are working together to further investigate all the user agreement violations you have done, which incur in termination of your account. You have been warned.

**Comment by bucaran** [comment]
> ...spamming people about Fisherman.

You also forgot Tweeting euphorically and posting comments and links in blogs to gain attention. 

> I have been scraping every move and documenting it.
...
> You have been warned.

Scary.

Anyhow, feel free to address the issue at hand if you actually want to have rational discussion.

**Comment by beckclib** [comment]
@bucaran Thank you, that was well thorough. I'll give it a shot and let you know. Sorry, if this has caused some polemic it was not in my intentions.

**Comment by bucaran** [comment]
@beckclib No prob. At the end of the day, we all have one thing in common, we think Fish is great and love to use it.

**Comment by tuvistavie** [comment]
Hi,

I'm a fish user, and the author of [fundle](https://github.com/tuvistavie/fundle).
I think fish is really a great shell, and I would love more people to use it,
but because of what happened with wahoo and omf, fish now has the worst
community I have ever seen, which I think is really a shame.

OMF folks have been really nice when it came to [help with compatibility](https://github.com/oh-my-fish/theme-bobthefish/issues/18),
and I am also trying to help a little to make some [OMF stuff compatible](https://github.com/fishery/git-helpers/commit/744145825612984c4c13315b5a0bfdbac8461866)
with fundle and fisherman, I really think this is how things should go,
and I hope it will go this way from now on, instead of fighting over and over.

I do not really know what happened with OMF and wahoo,
and I really do not care, nor I care if people use omf, fisherman, fundle,
or whatever they think is cool, but I really hope that we can give fish
users a decent community and stop fighting about whatever happened.

If there is anything I can help to bring the fish community in this
direction, I will be very pleased to do it.

Anyway, thank you all for building great stuff, and I hope that
it will help more people to benefit from it, not less.

/cc @bucaran @derekstavis @oranja @bpinto

**Comment by bucaran** [comment]
:clap:  Well said @tuvistavie

**Comment by bucaran** [comment]
<img width="530" alt="screen shot 2016-02-05 at 10 33 46 am" src="https://cloud.githubusercontent.com/assets/8317250/12835510/0cb28ca8-cbf4-11e5-8607-f5f972e80c09.png">

**Comment by bucaran** [comment]
@oranja 

Point 1 is your best argument. Point 2 is just a personal hypothesis. I *assure* you that I would take your ideas and contributions into account and accept your feedback and discuss whatever concerns you may have in depth. The same goes to any other Oh My Fish! contributor.

Point 3 applies to Fisherman too, I have so far produced a TAP producing test framework for Fish that is not locked to Fisherman, you could use it to test Oh My Fish! too which is severely lacking there.

Now, give me a break, I am just one guy and Fisherman has roughly one month, but things are coming along aren't they?. 

Also I just opened the [***Fishery***](https://github.com/fishery), an organization for universal high quality Fish plugins. Some of them should be compatible with Oh My Fish! too.

<p align=center>
<img src="https://cloud.githubusercontent.com/assets/8317250/12835541/882c8000-cbf4-11e5-8bcf-da346940625a.png" width=200>
</p>

**Comment by pickfire** [comment]
@bucaran 300+ tests? That's insane! I had already noticed that as it took **quite some space** on my system, I really hope that it could be separated, if not, I hope that it could be a lot smaller.

@bucaran, @tuvistavie I really hope that the fish community can work together and build a nice plugin manager together by using all the best ideas, this would greatly benefit fish users.

**Comment by bucaran** [comment]
> quite some space

Do you mean bytes? Fisherman is just slightly 4KB bigger than Oh My Fish!

<img width="542" alt="screen shot 2016-02-05 at 7 25 03 pm" src="https://cloud.githubusercontent.com/assets/8317250/12843665/32e777d6-cc3e-11e5-859e-dda63b72c742.png">

**Comment by pickfire** [comment]
@bucaran I don't mean the zipped fisherman. The tests file really do consume most of the space.

**Comment by bucaran** [comment]
That's right, the tests are twice as large as Fisherman's core body. 

<img width="548" alt="screen shot 2016-02-05 at 7 33 59 pm" src="https://cloud.githubusercontent.com/assets/8317250/12843892/733b2ab6-cc3f-11e5-83ba-6c7b28356969.png">

**Comment by tuvistavie** [comment]
@pickfire Is this really important here? If it were targeting an embed device
with only a few MB of storage I would understand, but on a normal computer nowadays
a few MB is really not relevant in my opinion, and I do not think it is worth
separating the tests to gain such a small amount of space.
The unzipped repository with everything including the .git directory
is around 1.3MB, do you really have a use case where this could be problematic?

**Comment by bucaran** [comment]
@tuvistavie Agree with you. In addition, as we move closer towards 1.0, Fisherman is supposed to become more and more feature _locked_. We don't need a forever evolving plugin manager to have great plugins. We need a good plugin manager and great plugins. The first part of the equation is almost done.

<img width="265" alt="screen shot 2016-02-05 at 7 39 05 pm" src="https://cloud.githubusercontent.com/assets/8317250/12844026/3d972940-cc40-11e5-885c-6a1b465c2002.png">

**Comment by pickfire** [comment]
@tuvistavie I am indeed using an embedded device (rpi2), actually I just mean that test isn't necessary and I am not sure why it is in `~/.config/fisherman`.

![2016-02-05-202715_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/12846348/040d9810-cc47-11e5-9b1a-5daf0bf8823f.png)

@bucaran `~/.config/fisherman` costs me about 4 MiB even after removing those tests file and I only use a plugin - `fishtape`.

**Comment by bucaran** [comment]
Interesting stuff!! 

@pickfire Can we track this on another issue? 

TBH I don't mind changing the way we ship Fisherman and move the tests to a differen repo. I just never done it like that before, but if it is for the best I am in. But in order to do that, careful planning and wisdom required will be.

![piq_246432_100x100](https://cloud.githubusercontent.com/assets/8317250/12846537/8388dccc-cc50-11e5-8b3a-9a506a81423b.png)

**Comment by pickfire** [comment]
@bucaran, Why isn't this in wiki instead it is here? It will definitely looks better in wiki. (Someone else can help to add more information to it too.)

**Comment by bucaran** [comment]
OK, let's port this to the wiki.

**Comment by bucaran** [comment]
@PeterFour @arthua196 @inoicouldalwaysturn2u
@cleverlycoding @xu-c @vinchaud @fltermare
@namezhouji @donkalar

**Comment by bucaran** [comment]
@PeterFour @arthua196 @inoicouldalwaysturn2u
@cleverlycoding @xu-c @vinchaud @fltermare
@namezhouji @donkalar

**Comment by bucaran** [comment]
@aximario @v-for-vincent

**Comment by bucaran** [comment]
@aximario @v-for-vincent

**Comment by bucaran** [comment]
@nkatte
@antoniordo
@lightonflux
@liulu72056
@JollySun
@andrewjlm
@JangJaeseok
@hang-h
@HoneyHyeok
@ykelvis
@don-makaron
@masateru
@pelchats

**Comment by bucaran** [comment]
@nkatte
@antoniordo
@lightonflux
@liulu72056
@JollySun
@andrewjlm
@JangJaeseok
@hang-h
@HoneyHyeok
@ykelvis
@don-makaron
@masateru
@pelchats

**Comment by bucaran** [comment]
@nkatte
@antoniordo
@lightonflux
@liulu72056
@JollySun
@andrewjlm
@JangJaeseok
@hang-h
@HoneyHyeok
@ykelvis
@don-makaron
@masateru
@pelchats

**Comment by bucaran** [comment]
@nkatte
@antoniordo
@lightonflux
@liulu72056
@JollySun
@andrewjlm
@JangJaeseok
@hang-h
@HoneyHyeok
@ykelvis
@don-makaron
@masateru
@pelchats

**Comment by bucaran** [comment]
@natrim
@angelrl
@AndreasScheffczyk
@CsCdanNyx
@ly95
@by-the-wei
@thulio
@talexand
@orociic
@zxp86021
@phra
@wo0621
@guweigang
@JoeyTeng
@hernanm92
@qiansen1386
@Wen777
@GYXie
@h0d
@ryuever
@kaibacorp
@debben
@xiaoyi001yeye
@Sparklexs
@logos-lee
@gcdeng
@syokoyama
@Depado
@cola1129
@spappier
@fatelei
@mardigras45
@HappyHackingNinja
@adstastic
@Leovim
@Kooooya
@arooni
@GQHero
@willchen90
@wilsonssss
@methou

**Comment by bucaran** [comment]
@natrim
@angelrl
@AndreasScheffczyk
@CsCdanNyx
@ly95
@by-the-wei
@thulio
@talexand
@orociic
@zxp86021
@phra
@wo0621
@guweigang
@JoeyTeng
@hernanm92
@qiansen1386
@Wen777
@GYXie
@h0d
@ryuever
@kaibacorp
@debben
@xiaoyi001yeye
@Sparklexs
@logos-lee
@gcdeng
@syokoyama
@Depado
@cola1129
@spappier
@fatelei
@mardigras45
@HappyHackingNinja
@adstastic
@Leovim
@Kooooya
@arooni
@GQHero
@willchen90
@wilsonssss
@methou

**Comment by bucaran** [comment]
@natrim
@angelrl
@AndreasScheffczyk
@CsCdanNyx
@ly95
@by-the-wei
@thulio
@talexand
@orociic
@zxp86021
@phra
@wo0621
@guweigang
@JoeyTeng
@hernanm92
@qiansen1386
@Wen777
@GYXie
@h0d
@ryuever
@kaibacorp
@debben
@xiaoyi001yeye
@Sparklexs
@logos-lee
@gcdeng
@syokoyama
@Depado
@cola1129
@spappier
@fatelei
@mardigras45
@HappyHackingNinja
@adstastic
@Leovim
@Kooooya
@arooni
@GQHero
@willchen90
@wilsonssss
@methou

**Comment by bucaran** [comment]
@zukif

**Comment by bucaran** [comment]
@octoroid @LostCore

**Comment by bucaran** [comment]
@eqw3rty

**Comment by bucaran** [comment]
@changyuheng

**Comment by bucaran** [comment]
@quininer

**Comment by bucaran** [comment]
@kelvincobanaj

**Comment by bucaran** [comment]
@yinheli

**Comment by bucaran** [comment]
@stalayhan

**Comment by bucaran** [comment]
@benjohnston

**Comment by bucaran** [comment]
@maoabc1818

**Comment by bucaran** [comment]
@fadion https://github.com/fishery/tirana

**Comment by bucaran** [comment]
@Rex-Diego

**Comment by bucaran** [comment]
@dan-c-underwood

**Comment by bucaran** [comment]
@zhost

**Comment by bucaran** [comment]
@LaurentFough

**Comment by bucaran** [comment]
@GManzato

**Comment by bucaran** [comment]
@oddeirik

**Comment by bucaran** [comment]
@demidovakatya

**Comment by bucaran** [comment]
@alvarete

**Comment by bucaran** [comment]
Ping @chenweiyj

**Comment by bucaran** [comment]
@frapsoft

**Comment by bucaran** [comment]
Ping @lordlycastle

**Comment by bucaran** [comment]
Ping @panshul007

**Comment by bucaran** [comment]
Would love your feedback → @dream1986  @beckclib @CHENGP618 @pedrosnk @rominf @sobolevn @tchellomello @wiseguys963

**Comment by bucaran** [comment]
@ninjatux

**Comment by bucaran** [comment]
@jojuniori

**Comment by bucaran** [comment]
@chenweiyj

**Comment by bucaran** [comment]
@chenweiyj Try the search command `fisher search`.

**Comment by bucaran** [comment]
@sobolevn Ping

**Comment by bucaran** [comment]
Ping guys //

@arvids @billhibazzz @redstar9451 @SuperSpyTX @cntoby @assassinleo @veduket @ttchopper @kail-linux liruizhe exitNA daisuuke zky001 niujx srstevenson xiamingxing cpwork Boldman

**Comment by bucaran** [comment]
Ping guys //

@arvids @billhibazzz @redstar9451 @SuperSpyTX @cntoby @assassinleo @veduket @ttchopper @kail-linux @liruizhe @exitNA @daisuuke @zky001 @niujx @srstevenson @xiamingxing @cpwork @Boldman

**Comment by bucaran** [comment]
@tchellomello

**Comment by bucaran** [comment]
Ping @Cycade

**Comment by bucaran** [comment]
@jojuniori @omartell @niiamon

**Comment by bucaran** [comment]
Ping guys
//
@r8k
@fabiob
@NatuMyers

**Comment by bucaran** [comment]
@lepetitforgeron

**Comment by bucaran** [comment]
Ping @wassiim

**Comment by bucaran** [comment]
Ping @thetooth, have a look?

**Comment by bucaran** [comment]
Pinging @fojouse

**Comment by bucaran** [comment]
@wassiim

**Comment by bucaran** [comment]
@stanzhai

**Comment by bucaran** [comment]
@BruceMaa

**Comment by bucaran** [comment]
@sylvainbannier

**Comment by bucaran** [comment]
Ping /cc @jamesacampbell @8cold8hot @zt2 @gavocanov @canering @madhusudancs
@judasnow @takuji31 @ycardon @OXXD @limatheus @evidex @datitran @ronert @linekin

**Comment by bucaran** [comment]
@stefanpopa @ceejbot @TomShine @pauldgifford

**Comment by bucaran** [comment]
Hey folks! I would love if you give Fisherman a try

@curtdp @redstar9451 @OllieDay @zb214 @turtle11311 @luizfb @satblip @vjcagay @athiwatc @mcveat @likaihere @Gusbenz @olidroide @Bahus

**Comment by bucaran** [comment]
@zhouhualei@nmhnmh@karboom@chenshengzhi@B1gtang@hirotaka11@giwa @kexplo@jShi-git@jk2K @garyayo@yangxuecheng@phpmaple@Sam0523

**Comment by bucaran** [comment]
@zhouhualei @nmhnmh @karboom  @chenshengzhi @B1gtang @hirotaka11 @giwa @kexplo @jShi-git  @jk2K @garyayo @yangxuecheng @phpmaple @Sam0523

**Comment by bucaran** [comment]
Pinging @BruceMaa

**Comment by bucaran** [comment]
Ping @jaiyalas

**Comment by bucaran** [comment]
Ping @huaruiwu

**Comment by bucaran** [comment]
Ping @kooksee

**Comment by bucaran** [comment]
Ping @cmonte905 and @leaveitout 

Have a look?

**Comment by bucaran** [comment]
@RubenG123

**Comment by bucaran** [comment]
Hey @ali6681!

// Ping.

**Comment by bucaran** [comment]
Hi @peng051410!

// Ping :heart:

**Comment by fishequality** [comment]
New members: @ppattern @jerikson @vasylchenko @akowal @mskarbek @Wintus @rememberli @kondra @ElderMael @neodevelop

**Comment by fishequality** [comment]
Please see above.

// @Leolik

**Comment by fishequality** [comment]
Please see above and let me know if you would like to join the project.

// @xor3 @KingCatT

**Comment by bucaran** [comment]
tennc

**Comment by bucaran** [comment]
Please see above @flwh

**Comment by bucaran** [comment]
Ping @jackric

**Comment by bucaran** [comment]
Hi @Invisible4ever, I thought you might be interested in checking out these.

**Comment by bucaran** [comment]
Hi, please have a look? @hhstore

**Comment by bucaran** [comment]
Hi Andrew, @andrewrynhard, can you have a look? Cheers.

**Comment by bucaran** [comment]
Hi, please have a look @wbbim

**Comment by bucaran** [comment]
@murata0705 どうも、fish-shellユーザーなので、こちらを見ていただけますか？

**Comment by bucaran** [comment]
Ping @noikiy

**Comment by bucaran** [comment]
Hi @butzhang, please see above.

**Comment by bucaran** [comment]
Would you mind having a look at this? @cheekybastard

Cheers!

**Comment by bucaran** [comment]
Hi Moritz, @flat235, would you mind having a look at this issue? Cheers.

**Comment by bucaran** [comment]
Hi Luke @lukewang1024, would you mind having a look at this issue? Cheers.

**Comment by bucaran** [comment]
Hi @agamem can you have a look? 

Cheers.

**Comment by bucaran** [comment]
Hi @llorephie, would you mind having a look at this?

Cheers :)

**Comment by bucaran** [comment]
@bassy どうもこんにちわ。このissueを見ていただけますか？

**Comment by bucaran** [comment]
Ping @melotusme

**Comment by bucaran** [comment]
Hi @pldiiw, would you mind have a look? Cheers.

**Comment by bucaran** [comment]
Hi @alex-pat, would you mind having a look at the issue above? Cheers! :)

**Comment by bucaran** [comment]
@thinker3 Hi Ken, would you mind having a look at this issue? Cheers.

**Comment by bucaran** [comment]
@robjac Hello Robbie, would you mind having a look over at this issue? Cheers! :)

**Comment by bucaran** [comment]
Hi @FreeTymeKiyan, would you mind having a look at this issue? Cheers!

**Comment by bucaran** [comment]
Hi @izuo, would you mind having a look at this issue? Cheers!

**Comment by bucaran** [comment]
Hi Fengda @phodal, would you mind having a look over at this issue? Cheers.

**Comment by bucaran** [comment]
Hi @taizilongxu, I just found an article you wrote online. Would you mind having a look at this issue? Cheers.

**Comment by bucaran** [comment]
Hi @TheWizardTower, I was checking out some dotfile repos and stumble upon yours. Would you mind checking out fisherman? Cheers.

**Comment by bucaran** [comment]
Hi @cbennett35, would you mind having a look over at this issue? :) Cheers.

**Comment by bucaran** [comment]
Ping @zqhong :)

**Comment by bucaran** [comment]
Hi Marie @Neit1o!, care to have a look here? Cheers.

**Comment by bucaran** [comment]
Hi Chris, @ChristopherRogers, can you check this out? Cheers.

**Comment by bucaran** [comment]
Hi @coldnew, can you check this?

**Comment by bucaran** [comment]
Hi @bindiry and @lerencao, please check out the pros of fisherman vs omf.

**Comment by bucaran** [comment]
Hi are you using fish? @yf92

**Comment by bucaran** [comment]
Ping @oiojin831, do you want to have a look? :)

**Comment by bucaran** [comment]
Hi @es-lee, would you mind having a look over this issue? Cheers!

**Comment by bucaran** [comment]
Hi @jackric, would you mind having a look over at this issue? Cheers :)

**Comment by bucaran** [comment]
Hi @felipe-campos!, I am no longer maintaining oh-my-fish, please upgrade to fisherman.

**Comment by bucaran** [comment]
Hi @cg505, would you mind having a look over this?

**Comment by bucaran** [comment]
@sstruct I forgot to attached this link, here is the main reason. Thanks.

**Comment by bucaran** [comment]
Hi @bakiro, oh-my-fish is not longer actively maintained, and I have upgraded everything to fisherman. I recommend you to update as well. cheers

**Comment by bucaran** [comment]
Ping @pyprism. Check your inbox ;) Thanks.

**Comment by bucaran** [comment]
Hey @kigawas, please check your inbox ;)

**Comment by bucaran** [comment]
Hi @danieljaouen, would you mind having a look over this comparison? Cheers :)

**Comment by brj** [comment]
Hi @cuekoo! Would you mind having a look over at this issue? Cheers!

**Comment by brj** [comment]
https://github.com/oh-my-fish/oh-my-fish/issues/320

**Comment by brj** [comment]
Hi @bentolor! Would you mind having a look over at this one here? I am no longer maintaining OMF, so I'd appreciate a ton if you could upgrade to fisherman instead.

**Comment by brj** [comment]
Hi @maman, this is the link I talked you about. Cheers.

**Comment by brj** [comment]
Hi @newliver, check this out o/ :)

**Comment by brj** [comment]
Hi @archmagees, is this what you mean?
https://github.com/fisherman/shark

**Comment by brj** [comment]
@JimAmuro This is the issue :)

**Comment by brj** [comment]
Hi @brickgao, this is the post is what you wanted to see :)

**Comment by brj** [comment]
Ping @edblancas. Cheers and happy fishing:)

**Comment by brj** [comment]
Ping @Baaaaam, see here please :) and happy fishing!

**Comment by brj** [comment]
Ping @zpfbuaa, can you check? And happy fishing :)

**Comment by brj** [comment]
Hola @hmaciasc, ya no estoy manteniendo el OMF, te agradecería un montón si te actualizas al fisherman! saludos!

**Comment by brj** [comment]
@helloworlderly

**Comment by brj** [comment]
@MITSUBOSHI こんにちは。こちらをご覧ください。https://github.com/fisherman/fisherman/wiki/%E6%97%A5%E6%9C%AC%E8%AA%9E

**Comment by brj** [comment]
@AbdelQuddous

**Comment by brj** [comment]
Hi @zzag!

**Comment by brj** [comment]
Hi @SpyderSC

**Comment by brj** [comment]
Hi @brokenbeta, check out this comparison omf / fisherman! :)
