### ISSUE TITLE
Should we use more XDG directories?

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#72]
* https://ploum.net/207-modify-your-application-to-use-xdg-folders/

/cc @etu

**Comment by etu** [comment]
Yes! XDG is good! Makes it easier to do good backup routines and easier to sync configuration between computers! ;)

**Comment by bucaran** [comment]
If anything changes, it must be before we hit 1.0, so I promise I will look closely at that article and see if there is anything we could change to be more XDGity.

**Comment by bucaran** [comment]
@etu Alright, I did some research and it seems we could actually start using `$XDG_CACHE_HOME` instead of the current strategy. There is only **one** catch.

How do we update the `$fisher_file` if the user decides to remove everything in the cache?

**Comment by pickfire** [comment]
@bucaran, I didn't found any configuration files, it seems like that fisherman should only be put into `$XDG_DATA_HOME` and `$XDG_CACHE` (for the cache directory) only.

**Comment by bucaran** [comment]
See `$fisher_config` also `fisher help config`.

**Comment by bucaran** [comment]
One problem I see with using `XDG_CACHE` is that if the user deletes the directory, how do we update the Fishfile? The fishfile is used to keep track of what plugins are installed and not.

I think the correct approach here is to modify the name `cache` and start using `stage` or similar. I used the term cache because `$fisher_cache` has characteristics of a cache, but it's more like a mixture between a cache, a config directory and a stage.

**Comment by etu** [comment]
Then the fishfile shouldn't be in the cache folder. It should be in the
data folder.

**Comment by bucaran** [comment]
@etu The fishfile is not in the cache directory, no worries.

So, I've had another chance too look at this and realized that

> One problem I see with using XDG_CACHE is that if the user deletes the directory, then how do we update the fishfile?

does not make much sense, in other words, this is not a problem.

So, _yes!_, we'll be moving `$fisher_cache` to `XDG_CACHE_HOME` in the next release. This change breaks backward compat, but we are still not 1.0, so it's not or never.

This means that Fisherman is pretty much XDG complete now.

/cc @jrobeson

**Comment by bucaran** [comment]
EDIT: New issue showed up.

I just remembered we use the repositories downloaded to the cache to determine what files we should add / delete from $fisher_config. If the user deletes the cache, there will be no reliable method to remove a given plugin as each plugin may have an arbitrarily complex tree. 

I'll think about this more, if no solution is arrived, I'll change the name from `cache` to `stage` to avoid confusion.

**Comment by etu** [comment]
If it's not removable without being able to regenerate it on the fly, put it in Data or possibly config depending on nature of the data.

For example: My Emacs Config depend heavily on installed modules. But I have those in the Cache folder since it installs it on startup, so if I remove the cache-folder, the next startup will take more time.

**Comment by bucaran** [comment]
> put it in Data or possibly config depending on nature of the data.

It _is_ in config actually, not data, because data is only for Fisherman own data and functions.

**Comment by bucaran** [comment]
Closing as it is understood now that Fisherman stores the downloaded plugins into XDG_CONFIG.
