### ISSUE TITLE
Create new high resolution SVG version of the logo.

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#76]

**Comment by pickfire** [comment]
I would like to help on this too.

**Comment by bucaran** [comment]
@pickfire That would be awesome. This is what I have so far, but I am having trouble smoothing out some of the details.

**Comment by pickfire** [comment]
@bucaran Is the `.ai` file that you had sent me the one you just did?

**Comment by bucaran** [comment]
That's correct, did you want the exported .SVG?

**Comment by pickfire** [comment]
@bucaran No, I can't download that as I doesn't have dropbox account.

By the way, I didn't know you are in Tokyo.

**Comment by bucaran** [comment]
I'll email it to you then.

**Comment by bucaran** [comment]
Done! :smile: 

https://github.com/fisherman/logo

**Comment by pickfire** [comment]
@bucaran Nice, yours is only 1.2K and mine is 2.2K. http://dl.pickfire.wha.la/usr/img/ofish.svg

>> By the way, I didn't know you are in Tokyo.
> Yeah, what, you too?

Nope, I am in Malaysia. Still celebrating Chinese New Year so will be busy these few days.

**Comment by bucaran** [comment]
Thanks @pickfire! Enjoy your holiday.

**Comment by pickfire** [comment]
The wiki's footer still is still using the old image, I hope that I can edit it.

**Comment by pickfire** [comment]
Mine is done, it uses a different method during creation, it should be a bit smaller when uncompressed (2K). (Yours should be 2.2K)
I did some edits to make it looks better.

[![https://p.iotek.org/c66.svg][1]][1]

[1]: https://p.iotek.org/c66.svg

**Comment by bucaran** [comment]
Cool, thanks man. I'll compare them later. I don't really mind the extra 0.2K.

I need to start working on the Japanese docs, now. Really appreciate you going the trouble of doing this.

**Comment by pickfire** [comment]
No problem. :smile:

I am a bit slow these few days as I have a burnout. Hope to watch luffy use his second gear fourth this week (One Piece).
