### ISSUE TITLE
Revise documentation, use more consistent style, remove deprecated APIs

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#77]

**Comment by pickfire** [comment]
Is there any plan to switch to `md2man` or something similar?

ruby-ronn isn't installed by default in a lot of distributions.

**Comment by bucaran** [comment]
> Is there any plan to switch to md2man or something similar?

Well, `ronn` is older than `md2man` and both are written in Ruby if I am not mistaken. I don't mind either one TBH. Generating the docs is something that only people editing the documentation need to face, therefore most users are not affected.

Also, notice the new rule on the Makefile:


```make
%.1 %.5 %.7: %.md
	-@if type ronn 2>/dev/null 1>&2; then \
		ronn --manual=fisherman --roff $? 1>&2 2> /dev/null;\
	fi;\
```

So, we are deliberately skipping doc generation entirely and silently if you don't have `ronn`.

If you want to give a shot, change it to `md2man` and let me know if there are any improvement on the results and then we can switch if things don't break or if there are any advatages.

**Comment by pickfire** [comment]
If I recall correctly, `md2man` is written in perl. Well, I guess both `md2man` and `ronn` is just the same, I don't see any reason to switch. It should be the same.

**Comment by daenney** [comment]
Pandoc has the ability to export to groff too.

**Comment by pickfire** [comment]
@daenney Ah, a new member.

I wouldn't consider pandoc as it is bloated (100M+), it would costs a lot of my system as I am using rpi2.

**Comment by daenney** [comment]
> @daenney Ah, a new member.

I'm sorry, what?

**Comment by pickfire** [comment]
@daenney I just want to congrats you as you have became a new member. Or probably I am wrong about that (you are an old member).

**Comment by daenney** [comment]
Oh, thanks. Haven't been around that long. :smile:
