### ISSUE TITLE
use fully qualified paths of `cp`, `mv`, etc. or `command` before invoking them

### ISSUE THREAD

**Issue by jab** [fisherman/fisherman#79]
I have common commands like `cp`, `mv`, etc. aliased to `cp -i`, `mv -i`, etc.

When I use fisherman, I see `overwrite /Users/jab/.config/fisherman/fishfile? (y/n [n]) not overwritten`.

I assume this is caused by fisherman referring to a command like cp as just `cp`, rather than as `/bin/cp` or `command cp`. This can cause problems if the user has the command aliased to pass other arguments (such as interactive mode, as above), since fisherman is assuming `cp` is the same thing as `/bin/cp`, it isn't. If so, any interest in fixing this? I think well-behaved shell scripts are supposed to use fully-qualified paths or use `command` to avoid this problem.

**Comment by daenney** [comment]
Using `command` is probably a good idea but if you're using Fish I'd recommend using abbreviations over aliases. They have the advantage of being automatically expanded on your shell (so the command you end up executing doesn't contain "hidden" options) and wouldn't mess with scripts like this.

**Comment by jab** [comment]
Thanks @daenney, switched to using `abbr` and glad to have another way to accomplish the same thing that doesn't get in the way of fisherman. And glad you agree it's worth using `command` in fisherman.

**Comment by bucaran** [comment]
@jab You are absolutely right, so I have added it to the next milestone. I'll patch this ASAP and push after all tests pass and I see things to be working as they should.

**Comment by bucaran** [comment]
* [ ] mkdir
* [ ] cp
* [ ] ln
* [ ] rm

**Comment by daenney** [comment]
Bash seems to have an `unalias` so you can remove aliases. It might be worth seeing if we can recreate that somehow so we can call that at the top/whenever we start a script and then not have to worry about the command invocations at all.

**Comment by daenney** [comment]
Oh ha, since aliases are just functions we could `function -e` instead.

**Comment by bucaran** [comment]
@daenney Yes, but it's not that easy, we would need to copy the function first, and then define it again later.

**Comment by daenney** [comment]
Oh, bummer. I was hoping it could scope that to the process currently being executed.

**Comment by bucaran** [comment]
>  scope that to the process currently being executed.

That's clever, and I wish it was like that too. But that trick only works for variables in Fish.

```fish
function foo
    set -l x 1
    begin
        set -l x 
    end
    echo $x # 1
end
```

**Comment by daenney** [comment]
In theory though, `functions` has `-c` which would allow you to copy the function to a backup and back but it would affect all other running sessions too which is unpleasant.

**Comment by bucaran** [comment]
I we need to `command` patch stuff like `cp` and `rm` first, but we can spare most of the other commands for the time being.

**Comment by daenney** [comment]
I've updated it to call `command` on `rm`, `ln`, `mkdir` and `mv`.
