### ISSUE TITLE
Do not allow `fisher install` to install `..`

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#81]
I think typing `fisher install ..` is probably more an error than the user intention.

**Comment by pickfire** [comment]
Oh, it seems like this is a probably a bug, it shows that it is installing `..`, but actually nothing is installed.

**Comment by bucaran** [comment]
Actually not a bug. What's happening in your case is that you probably have no files that Fisherman could copy or move maybe in that parent directory. The catch is doing this for example in a sub directory of another directory where you keep a lot of plugins.
