### ISSUE TITLE
`fisher uninstall -f foo` reads from stdin instead of uninstalling foo

### ISSUE THREAD

**Issue by kballard** [fisherman/fisherman#84]
If I run `fisher uninstall -f foo`, it sits there trying to read from stdin instead of uninstalling the plugin `foo`.

**Comment by bucaran** [comment]
@kballard 

```fish
fisher uninstall -f -- foo
# or
fisher uninstall foo -f
```

The problem is in `getopts` which does not handle _"short flags that must not take an argument"_.

**Comment by bucaran** [comment]
I am going to track this here https://github.com/fishery/getopts/issues/11

**Comment by pickfire** [comment]
@bucaran, by the way, `fisher uninstall -h` shows:
```
    -f --force  Delete copy from cache
    -q --quiet  Enable quiet mode
     -h --help  Show usage help
```

**Comment by bucaran** [comment]
@pickfire Yeah, that's the usage help. :question:

**Comment by pickfire** [comment]
@bucaran, just a simple change, no need for a pull request. I am suggesting for an aligned help. e.g. omxplayer is a good example of this, their `--help` is awesome. Just:
```
    -f --force  Delete copy from cache
    -q --quiet  Enable quiet mode
    -h --help   Show usage help
```

**Comment by bucaran** [comment]
@pickfire I think you may be misunderstanding the issue here :sweat: 

And, yeah, we could improve the usage help display. I based Fisherman usage help in Git, but I liked the example you showed me. Very neat.
