### ISSUE TITLE
oh-my-fish DMCA takedown

### ISSUE THREAD

**Issue by peterjosling** [fisherman/fisherman#85]
I'm just wondering if you can provide any clarification on what's going on with oh-my-fish's recent DMCA takedown. I've seen that another one was previously filed (https://news.ycombinator.com/item?id=10271304), but that was resolved — what's changed now?

**Comment by TeddyDD** [comment]
:+1:

**Comment by daenney** [comment]
The DMCA was filed because the author's copyright was violated. The MIT license under which the code was released requires that attributions/copyright notices remain in place, which the maintainer of oh-my-fish decided to strip after their fallout.

**Comment by peterjosling** [comment]
From looking at Google's cache, the oh-my-fish AUTHORS and LICENCE files haven't been modified in five months (i.e. since they were updated after the original DMCA notice). Looking at the cache for one of the other mentioned repos, I can see "MIT © Jorge Bucaran" at the bottom of the README for oh-my-fish/plugin-tiny. I'm struggling to see what's changed since the LICENCE files were updated after the previous takedown.

**Comment by bucaran** [comment]
> LICENCE files were updated after the previous takedown.

Look harder.

**Comment by TeddyDD** [comment]
@bucaran That's very helpful ^^ Thanks for exhaustive explanation. @daenney Thank you too! In fact I'v read DMCA myself but thanks anyway :+1:

**Comment by bucaran** [comment]
@TeddyDD No problem! :smile:

**Comment by peterjosling** [comment]
That was as far as I was able to look unfortunately - Google don't cache indivual file contents from Github. I didn't really know where else to go for discussion (as the OMF issues are gone too). This seemed the logical place to go given it was referenced in the DMCA. I'm not trying to question your claims or anything — I just wanted some more details on what happened. It kinda sucks to just have code disappear like that, y'know?

**Comment by bucaran** [comment]
I don't think it was referenced in the DMCA. Are you sure you don't mean [Wahoo](https://github.com/bucaran/wahoo)?

**Comment by bucaran** [comment]
The following comment by @TeddyDD, deleted by himself, not sure why, for posterity:

<img width="868" alt="screen shot 2016-02-09 at 11 10 03 pm" src="https://cloud.githubusercontent.com/assets/8317250/12918409/5c0fbe42-cf82-11e5-871a-bbbe1b1354cc.png">

:+1:

**Comment by TeddyDD** [comment]
My comment was sarcastic reply to your comment 
> Look harder

After your edited your comment, my become irrelevant and misleading so I removed them

**Comment by bucaran** [comment]
@TeddyDD No problem, keep up the good work!

**Comment by eugenesvk** [comment]
So, my fork already has the attribution
"Copyright (c) 2015, Jorge Bucaran <jbucaran@me.com> for code taken from https://github.com/bucaran/wahoo/tree/master/lib"
You're also listed in the authors file
What else do you need? 
You don't have the right to demand removal of the libs since you have them under MIT license.
You also can't demand that you're the only copyright holder in the license because the other folks also added code, so it's derivative work and it's copyrightable (and if I remove them, they can issue a DMCA of their own).
