### ISSUE TITLE
Create multi-language versions of the QuickStart Guide

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#87]
The QuickStart guide is just a tidbit of the docs and should not take more than 1 hour to translate into a language you are already fluent in.

If someone wants to take a stab at it, that would be awesome.

I will start working on the Spanish and Japanese versions.

* https://github.com/fisherman/fisherman/wiki/Quickstart-Guide

**Comment by bucaran** [comment]
* [Español](https://github.com/fisherman/fisherman/wiki/Quickstart-Guide-ES). :heavy_check_mark:

**Comment by pickfire** [comment]
[ ] 中文 :cn:  (Probably both simplified and traditional chinese)

**Comment by bucaran** [comment]
@pickfire Thanks! I'll start working on the Japanese version soon.

**Comment by pickfire** [comment]
How do I help? I can't edit the wiki page.

**Comment by bucaran** [comment]
Sorry about that, you should be able to now!

https://github.com/fisherman/fisherman/wiki/Quickstart-Guide-CN

**Comment by pickfire** [comment]
It seems like the `home` link is duplicated quite a few times. In my humble opinion, just the `FISHERMAN` picture that link to the home page is enough.

**Comment by bucaran** [comment]
Where would that be? Wiki? README?

**Comment by pickfire** [comment]
I just think that the footer seems a bit useless, I hope you can consider merging it with the sidebar, it's a bit confusing.

**Comment by bucaran** [comment]
Well, I'll give you that it is a bit repetitive, but it sure looks pretty. Pretty is one of the reasons it's there. I took inspiration looking at other great Wikis [here](https://github.com/showcases/projects-with-great-wikis).

**Comment by bucaran** [comment]
I finished the Español and Japanese guides. That's all I can do until I learn a new language :laughing: 

@pickfire No pressure writing the Chinese docs, whenever you can_!_

**Comment by pickfire** [comment]
Done, but it is not very nicely translated, I don't know a lot of the terminology in chinese.

**Comment by bucaran** [comment]
Awesome! Thanks @pickfire!
