### ISSUE TITLE
More information for plugin creation or good sample which covers all aspects 

### ISSUE THREAD

**Issue by kulynyak** [fisherman/fisherman#88]
Where to put key bindings (right approach) ?
my_plugin
|-- fisher_my_plugin.fish - **what should be done here?**
|-- my_plugin.fish
|-- fish_prompt.fish
|-- fish_right_prompt.fish
|-- my_plugin.config.fish
|-- functions
|   |-- my_plugin_helper.fish
|-- conf.d
|   |-- *.fish
|-- completions
|   |-- my_plugin.fish
|-- man
    |-- man1
        |-- my_plugin.1

Thanks, 
Andriy

**Comment by bucaran** [comment]
@kulynyak For a _very_ simple tutorial, try `fisher help plugins`.

For information about key bindings, this is a very new feature and it's not very well documented, but you can read a lot about it in the change log for [0.5.0](https://github.com/fisherman/fisherman/releases/tag/0.5.0).

Basically, put your plugin key bindings inside `key_bindings.fish` at the root of your project or inside `functions/` (actually this is not even enforced, could be anywhere, but maybe we _should_ enforce a few locations in the future).

As for `fisher_my_plugin.fish` here is the typical pattern:

* Create a function with the same name of the file `fisher_my_plugin`. And that's it. If you need additional functions, and if they are only used privately use a prefix like `__my_plugin` is **recommended**.

**Comment by kulynyak** [comment]
Thanks for quick reply, I’m working on few plugins - so your info is very useful for me

**Comment by bucaran** [comment]
Just for fun, have a look at this [compatibility chart](https://github.com/fisherman/fisherman/blob/master/test/plugin-walk.fish).

**Comment by bucaran** [comment]
@kulynyak Besides `fisher help plugins`, what else do you think we could do to improve the help in this area? I would like to create a goal and add it to a milestone before we close this.

**Comment by kulynyak** [comment]
1) what file is executed only during install (same for uninstall)
2) how to define package private functions
3) where to put session variable definitions
4) key binding config
5) some info how to install/uninstall local package for debug reason
6) evidently say that package (in the cache) named xx-yy should be named plugin-xx-yy in git repo

**Comment by bucaran** [comment]
@kulynyak I can answer all these questions right now, but perhaps we want to put those answers in the wiki instead.

**Comment by bucaran** [comment]
Closing in favor of #94. @kulynyak Join me there.
