### ISSUE TITLE
`fisher install submit` asks for credentials.

### ISSUE THREAD

**Issue by carlosjhr64** [fisherman/fisherman#89]
And 'https://github.com/bucaran/fisher-submit' does not exist.
Maybe this feature was not meant to go live yet?
And maybe there needs to be a way to check if url is really there on install?
BTW, really liking Fisherman so far.

**Comment by bucaran** [comment]
Why does it ask for credentials? Could this be a local thing with your git configuration or am I missing something.

Now, `submit` is not ready for prime yet, just wait a bit :ok_hand: more.

Actually, it's coded, but it has no tests or documentation, and those are just as important as the code.

Thanks, and welcome aboard captain!

**Comment by carlosjhr64** [comment]
I've not looked at the code, but I suspect that because `fisher install` is working with git asking about a non-existing url, it's doing...  :-??  Anyways, even after when `submit` is ready, the case of when a url is yanked might need to be caught.

**Comment by bucaran** [comment]
Yes, defintely.

Could you provide me a way to reproduce this, here is what I get on my end:

```fish
 ~  fisher install submit
Installing >> submit
fisher: Repository not found: 'https://github.com/bucaran/fisher-submit'
No plugins were installed.
```

**Comment by carlosjhr64** [comment]
Ok, because I don't have "rights" on https://github.com/bucaran.
It would not ask you for credentials.
I don't know why the logic of a download from a "not found" would turn into
a credential check.  Maybe it's in git.

**Comment by bucaran** [comment]
You don't need rights on `bucaran` in order to `git clone`, only if you were doing `git push` or using the GitHub API. I presume this could be an issue on your Git's configuration.

1. Are you on OS X or Linux?
2. Are you using [2FA](https://help.github.com/articles/providing-your-2fa-authentication-code/) on GitHub?

**Comment by carlosjhr64** [comment]
I'm on Linux.
For you to duplicate the problem is a bit involved.
On Linux, the easiest way I can think to do it is to create a new user.
Log out of "bucharan" or whatever on you computer, and log in back as the new user.
Set things up the way a new user would.
Then try the command (under the previous conditions, I suppose).

Anyways, this is obviously an edge case.
I'd love to know when the new release is ready.
I have a "theme-local" and a "pkg-goto" I'd like to register.
They work perfectly (for me, of course).

**Comment by carlosjhr64** [comment]
Bucaran:

I did a quick test
    git clone -q --depth 1 'https://github.com/carlosjhr64/theme-nope' ./test
trying to clone a none existing repo.
It asked for my credentials.
So it's something git is doing.  Looks like a bug in git to me.
So this would normally never happen unless a url got yanked, and
if you're now checking the url first (or don't care to)
I think you can close this issue.

BTW, looks like Fisherman is now version 1.0.0.
Can I assume I can safely pull now at any time?
I tend to use github as a backup and
kinda push bad code sometimes.  LOL

**Comment by bucaran** [comment]
@carlosjhr64 This is odd, I really want to test this out right now, but I don't have time until I am done with publishing some basic plugins, but I will get around to it later today.

Fisherman is 0.7.0 now.

<img width="360" alt="screen shot 2016-02-12 at 10 19 24 am" src="https://cloud.githubusercontent.com/assets/8317250/12996333/356dae1a-d172-11e5-82b4-f07a9d8f29af.png">

You can `fisher update` any time you want. The update mechanism still needs more improvement, but you should not run into any problems unless you are upgrading from 0.4.0 or older.

What is your --version?

**Comment by carlosjhr64** [comment]
I was 0.6.0.
I just tried `fisher update`, but I'm still 0.6.0.
So, I deleted original installation, redid the curl, and I'm now at 0.7.0.
OK, thanks!

**Comment by bucaran** [comment]
Are you still having this problem @carlosjhr64 ? :smile:

**Comment by pickfire** [comment]
@bucaran, I think I have this problem too, when I did `fisher update`, it is still the same version.

**Comment by bucaran** [comment]
@pickfire Can you explain what problem you are having, I still don't really understand this. Also, is this related to Fisherman?

**Comment by pickfire** [comment]
@bucaran Sorry that I didn't provide more info, I just doesn't have any idea why it wasn't updated, I was updating from 0.4 to 0.6, but after I run `fisher update`, it is still in 0.4, I can't reproduce this now as I can't reinstall fisherman.

**Comment by bucaran** [comment]
?

**Comment by carlosjhr64** [comment]
So in version 0.7.0, submit is a plugin.
After running `fisher install submit`,
~/.config/fisherman/cache/submit
just has the LICENSE file and a basically empty README.md file.

**Comment by pickfire** [comment]
@bucaran I want to be as helpful as I could, using the latest fish git should solve the issue now, I really can't reproduce it, it's in the past.

**Comment by bucaran** [comment]
@pickfire Thanks for the good news! :relieved:

**Comment by pickfire** [comment]
@carlosjhr64 So it works now? Should this issue be closed?

**Comment by carlosjhr64** [comment]
If you mean it doesn't ask for credentials anymore, that's fixed.

**Comment by bucaran** [comment]
@carlosjhr64 Thanks Carlos!
