### ISSUE TITLE
Create a FAQ or extended tutorial for authoring plugins

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#94]
* [ ] What file is executed only during install (same for uninstall)
* [ ] How to define package private functions
* [ ] Where to put session variable definitions
* [ ] key binding config
* [ ] Some info how to install/uninstall local package for debug reason
* [ ] Evidently say that package (in the cache) named xx-yy should be named plugin-xx-yy in git repo

/ cc @kulynyak 

If you have anything else to add, feel free to do so, I'll start working on this new document soon. If you have any ideas regarding the _title_ for the manual, please let me know that too.

**Comment by bucaran** [comment]
I will start answering the questions here as I still haven't decided into which guide I will add this information.

1. What file is executed only during install (same for uninstall)?

When you install a plugin, any file with a `fish` extension is sourced. This way we force fish to load any functions within the same shell session. Without this you would have to reload your shell, `exec fish` or create a new window/tab in order to start using the plugin.

When you uninstall a plugin typically nothing runs, but there is a convention to call a file named `uninstall.fish` if it's inside the plugin project. I use this to restore overridden functions in the [`autoinit`](https://github.com/fishery/autoinit/blob/master/functions/uninstall.fish) plugin.

2. How to define package private functions?

Fish does not have functions, so you can't do this. What you _can_ do, is prepend a prefix to your functions based in the name of your plugin. If your plugin is named `my_plugin`, you can declare you intent to create a private function by calling it `__my_plugin_<name of the function>`.

3.  Where to put session variable definitions?

In your personal / user configuration, variables and any code you wish to run at the start of the shell should go in your fish `~/.config/fish/config.fish` as usual. Fisherman is not a configuration framework in the sense that there is no convention. In fact, I recommend you follow fish recommended practice to add this stuff into your `config.fish`.

If you mean plugins and what you are trying to do is to run initialization code you have a few options. If your plugin is named `my_plugin`, you can create a `my_plugin.config.fish` at the root of your project or inside a `functions` directory. If you prefer to separate configuration code from functions, you can create a directory `conf.d` and store any files with code that should run at the start of the shell in there.

4. How to define key bindings?

Create a file `key_bindings.fish` at the root of your project or inside a `functions` directory and add your code / key bindings there. This is a regular `.fish` file and there are no special rules. If you favor the structure of using a function, you can follow the same approach, but instead of dumping the code in the file you can create a `fish_user_key_bindings` functions and put your key bindings inside. Fisherman will take care of extracting the bindings and concatenate them with other plugin's bindings. **ItJustWorks™**

5. Some info how to install/uninstall local package for debug reason?

You can pass a path to `fisher install` by using the full path or a relative path like this: `fisher install .` or `fisher install ./path/to/plugin`.

![](https://cloud.githubusercontent.com/assets/8317250/12836552/5d8c554c-cbfd-11e5-91b6-4aeb9b53cc4b.gif)

6. Evidently say that package (in the cache) named xx-yy should be named plugin-xx-yy in git repo

If you are looking for a way to explicitly declare the _base_ name of a plugin, there is none. A plugin name is always the same as the repository or directory. Now, Fisherman is **aware** of the following prefixes which can help you organize your plugins either locally or on GitHub: `pkg-`, `fish-`, `fisher-`, `theme-` and `plugin-`.

**Comment by bucaran** [comment]
/ cc @kulynyak

**Comment by kulynyak** [comment]
Cool, it answers my questions
(please fix numbering)

**Comment by bucaran** [comment]
@kulynyak Great! I'll be closing this, but hope to add this to the documentation eventually.
