### ISSUE TITLE
install.fisher.sh script fails on FreeBSD

### ISSUE THREAD

**Issue by duck** [fisherman/fisherman#95]
The installs script fails on FreeBSD because the Makefile is a GNU make Makefile vs a pmake Makefile. FreeBSD does have the GNU make as a port called **gmake**.  Recommended fix would be for the install script to do a quick OS type check, and then call **make** for Linux and OSX, and **gmake** for at least FreeBSD (not sure about other *BSDs at this point).

**uname** on my host simply returns 'FreeBSD':
````
don@little ~> uname 
FreeBSD
````

Thanks

**Comment by bucaran** [comment]
Hi @duck! That should be very easy to fix. I will get around this very soon as I want to start adding some basic security features to the script. See [here](https://github.com/fisherman/fisherman/issues/90#issuecomment-182528010) if you are interested.

Thanks!

**Comment by bucaran** [comment]
@duck Done! :fist: 

https://github.com/fisherman/install/blob/master/install.fish#L89
