### ISSUE TITLE
Best practices for syncing basic configuration?

### ISSUE THREAD

**Issue by ViViDboarder** [fisherman/fisherman#97]
I'm in the process of switching my setup over to using Fisherman but I'm running into some confusion around how config files are loaded...

Previously I would have [this](https://github.com/ViViDboarder/shoestrap/tree/clean-shoes/assets/default/fish-config) symblinked to my config dir and then on load, `init.fish` would be run and that would init my other configuration files.

I tried putting it in `config.d/` as well as appending `*.config.fish` but that doesn't seem to do anything. Is there some good place for this? Should I wrap up all my configs into their own local plugin? Or should I just put these in my `.config/fish/` dir?

Thanks!

**Comment by bucaran** [comment]
@ViViDboarder Thanks for trying Fisherman.

IMO the best place to put your personal and unique configuration is in your fish user `config.fish` file.

If you have a massive configuration then maybe you want to start considering splitting that up, but looking at your `init.fish` it seems very light, so it could go into `~/.config/fish/config.fish`. I recommend adding it **after** Fisherman's configuration.

Please track this issue too: https://github.com/fisherman/fisherman/issues/98

**Comment by bucaran** [comment]
@ViViDboarder By the way, your code should work the way it is now with Fisherman, only `source` your `init.fish` inside your `config.fish` or **even better**, move the `source_config` fish to a function and store it inside `~/.config/fish/functions` and move:

```fish
source_config paths
source_config alias
```

to your `~/.config/fish/config.fish`. The best place in that file would be after the Fisherman configuration (this is not a rule, just a recommendation btw).

**Comment by ViViDboarder** [comment]
Great advice. Thanks. I'll give that a go.

Checking out #98 too. That's really funny that two people opened such similar tickets within hours of each other!

**Comment by bucaran** [comment]
Awesome. Let me know if you figure it out and what you came up with to help documenting this for future users.

**Comment by ViViDboarder** [comment]
Awesome! Moved `source_config.fish` to `fish/functions` and that solved that.

I think the only thing that needs to be made clearer, is that Fisherman doesn't seem to be a framework for managing your config, but instead a plugin framework. Init scripts you want to run should still go in `~/.config/fish`

Does that sound right? Or am I misinterpreting?

**Comment by bucaran** [comment]
> I think the only thing that needs to be made clearer, is that Fisherman doesn't seem to be a framework for managing your config...

That's correct. I think we can agree Fish works just fine out of the box with its sensible defaults and a "configuration framework" for Fish does not make as much sense as it does on Bash/Zsh.

> Init scripts you want to run should still go in ~/.config/fish

Yes. And if you can extract that code into a plugin that also works. If the code is general enough that it can be used by other people it would be great to share it, _else_ you can use it locally.

Creating a "local" plugin is incredibly easy with Fisherman, I added this feature to help me prototype future plugins, but you could use it to manage your configuration too.

h![](ttps://cloud.githubusercontent.com/assets/8317250/12836552/5d8c554c-cbfd-11e5-91b6-4aeb9b53cc4b.gif)

**Comment by ViViDboarder** [comment]
Cool. Yea, I'll try to extract some. Thanks for the help. I'm casting away now.

**Comment by bucaran** [comment]
![config](https://cloud.githubusercontent.com/assets/8317250/12996558/36d26938-d174-11e5-8fb8-fb9c18b6c730.gif)

**Comment by ViViDboarder** [comment]
Thanks for the demo! That should be easy enough. Do you think I should do that for config only things like these files? Or is it not really worth it since they are so user specific?

**Comment by bucaran** [comment]
If it's something trivial that you could simply add to your `config.fish`, just add it there, I have some silly functions in my `config.fish` that I use all the time, like for debugging and other stuff. While I would like to make a plugin out of them eventually, they are fine there for now.

Very user specific things, things that often change or if you are just lazy, `config.fish` is your friend.

By the way, new in 0.7.0 is support for Gists. So, now you have that option too. Check it out.

![gist](https://cloud.githubusercontent.com/assets/8317250/12996762/129c9d0c-d176-11e5-9d43-b2facd90054b.gif)

I am pretty sure using Gists could be another way to organize one's config

**Comment by bucaran** [comment]
@ViViDboarder How are things? Do you think we can close this or do you have any further questions? Freel free to ask anything you want.

**Comment by ViViDboarder** [comment]
Everything set up well. You can close. I'll reach out on Slack or something
if I have any other questions.

**Comment by bucaran** [comment]
:+1: Thanks.
